// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// ChannelSyncStatuses is the ChannelSyncStatuses model.
type ChannelSyncStatuses struct {
	FailedCount  *int32  `graphql:"failedCount"`
	Id           string  `graphql:"id"`
	LastError    *string `graphql:"lastError"`
	LastSyncTime *string `graphql:"lastSyncTime"`
	Name         string  `graphql:"name"`
	PendingCount *int32  `graphql:"pendingCount"`
	State        *string `graphql:"state"`
}

// ChannelSyncStatusesAggExp is the ChannelSyncStatusesAggExp model.
type ChannelSyncStatusesAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	FailedCount struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"failedCount"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	LastError struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"lastError"`
	LastSyncTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"lastSyncTime"`
	Name struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"name"`
	PendingCount struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"pendingCount"`
	State struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"state"`
}

// DeleteChannelSyncStatusesByIdResponse is the DeleteChannelSyncStatusesByIdResponse model.
type DeleteChannelSyncStatusesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		FailedCount  *int32  `graphql:"failedCount"`
		Id           string  `graphql:"id"`
		LastError    *string `graphql:"lastError"`
		LastSyncTime *string `graphql:"lastSyncTime"`
		Name         string  `graphql:"name"`
		PendingCount *int32  `graphql:"pendingCount"`
		State        *string `graphql:"state"`
	} `graphql:"returning"`
}

// InsertChannelSyncStatusesResponse is the InsertChannelSyncStatusesResponse model.
type InsertChannelSyncStatusesResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		FailedCount  *int32  `graphql:"failedCount"`
		Id           string  `graphql:"id"`
		LastError    *string `graphql:"lastError"`
		LastSyncTime *string `graphql:"lastSyncTime"`
		Name         string  `graphql:"name"`
		PendingCount *int32  `graphql:"pendingCount"`
		State        *string `graphql:"state"`
	} `graphql:"returning"`
}

// UpdateChannelSyncStatusesByIdResponse is the UpdateChannelSyncStatusesByIdResponse model.
type UpdateChannelSyncStatusesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		FailedCount  *int32  `graphql:"failedCount"`
		Id           string  `graphql:"id"`
		LastError    *string `graphql:"lastError"`
		LastSyncTime *string `graphql:"lastSyncTime"`
		Name         string  `graphql:"name"`
		PendingCount *int32  `graphql:"pendingCount"`
		State        *string `graphql:"state"`
	} `graphql:"returning"`
}
