// Code generated by generate-ql. DO NOT EDIT.

package entity

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceEntityByIdResponse, error) {
	var out schema.DeleteResourceEntityByIdResponse
	args := map[string]any{
		"keyId": keyId,
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("deleteResourceEntityById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceEntityObjectInput, params InsertParams) (schema.InsertResourceEntityResponse, error) {
	var out schema.InsertResourceEntityResponse
	args := map[string]any{
		"objects": objects,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	res := <-h.gql.MutateFields("insertResourceEntity", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceEntityByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceEntityByIdResponse, error) {
	var out schema.UpdateResourceEntityByIdResponse
	args := map[string]any{
		"keyId":         keyId,
		"updateColumns": updateColumns,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("updateResourceEntityById", &out, args)
	return out, res.Error
}
