// Code generated by generate-ql. DO NOT EDIT.

package entity

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceEntityByIdResponse, error) {
	var q struct {
		DeleteResourceEntityById schema.DeleteResourceEntityByIdResponse `graphql:"deleteResourceEntityById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteResourceEntityById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceEntityObjectInput, params InsertParams) (schema.InsertResourceEntityResponse, error) {
	var q struct {
		InsertResourceEntity schema.InsertResourceEntityResponse `graphql:"insertResourceEntity(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertResourceEntity, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceEntityByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceEntityByIdResponse, error) {
	var q struct {
		UpdateResourceEntityById schema.UpdateResourceEntityByIdResponse `graphql:"updateResourceEntityById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateResourceEntityById, res.Error
}
