// Code generated by generateql. DO NOT EDIT.

package membershipsummaries

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// ListParams holds the optional arguments for List.
type ListParams struct {
	Limit   *int
	Offset  *int
	OrderBy *[]inputs.IdentityMembershipSummariesOrderByExp
	Where   *inputs.IdentityMembershipSummariesBoolExp
}

// AggregateParams holds the optional arguments for Aggregate.
type AggregateParams struct {
	FilterInput *inputs.IdentityMembershipSummariesFilterInput
}

// DeleteByIdParams holds the optional arguments for DeleteById.
type DeleteByIdParams struct {
	PreCheck *inputs.IdentityMembershipSummariesBoolExp
}

// InsertParams holds the optional arguments for Insert.
type InsertParams struct {
	PostCheck *inputs.IdentityMembershipSummariesBoolExp
}

// UpdateByIdParams holds the optional arguments for UpdateById.
type UpdateByIdParams struct {
	PostCheck *inputs.IdentityMembershipSummariesBoolExp
	PreCheck  *inputs.IdentityMembershipSummariesBoolExp
}

// OnListParams holds the optional arguments for OnList.
type OnListParams struct {
	Limit   *int
	Offset  *int
	OrderBy *[]inputs.IdentityMembershipSummariesOrderByExp
	Where   *inputs.IdentityMembershipSummariesBoolExp
}

// OnAggregateParams holds the optional arguments for OnAggregate.
type OnAggregateParams struct {
	FilterInput *inputs.IdentityMembershipSummariesFilterInput
}

// QueryHandler runs IdentityMembershipSummaries query operations.
type QueryHandler interface {
	// List runs the "identityMembershipSummaries" query.
	List(ctx context.Context, params ListParams) ([]schema.IdentityMembershipSummaries, error)
	// Aggregate runs the "identityMembershipSummariesAggregate" query.
	Aggregate(ctx context.Context, params AggregateParams) (*schema.IdentityMembershipSummariesAggExp, error)
	// ById runs the "identityMembershipSummariesById" query.
	ById(ctx context.Context, id string) (*schema.IdentityMembershipSummaries, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs IdentityMembershipSummaries mutation operations.
type MutationHandler interface {
	// DeleteById runs the "deleteIdentityMembershipSummariesById" mutation.
	DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteIdentityMembershipSummariesByIdResponse, error)
	// Insert runs the "insertIdentityMembershipSummaries" mutation.
	Insert(ctx context.Context, objects []inputs.InsertIdentityMembershipSummariesObjectInput, params InsertParams) (schema.InsertIdentityMembershipSummariesResponse, error)
	// UpdateById runs the "updateIdentityMembershipSummariesById" mutation.
	UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateIdentityMembershipSummariesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateIdentityMembershipSummariesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs IdentityMembershipSummaries subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "identityMembershipSummaries" subscription.
	OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error)
	// OnAggregate runs the "identityMembershipSummariesAggregate" subscription.
	OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error)
	// OnById runs the "identityMembershipSummariesById" subscription.
	OnById(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
