// Code generated by generate-ql. DO NOT EDIT.

package membershipsummaries

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.IdentityMembershipSummaries, error) {
	var q struct {
		IdentityMembershipSummaries []schema.IdentityMembershipSummaries `graphql:"identityMembershipSummaries(limit: $limit, offset: $offset, order_by: $order_by, where: $where)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"limit":    params.Limit,
		"offset":   params.Offset,
		"order_by": params.OrderBy,
		"where":    params.Where,
	})
	return q.IdentityMembershipSummaries, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.IdentityMembershipSummariesAggExp, error) {
	var q struct {
		IdentityMembershipSummariesAggregate *schema.IdentityMembershipSummariesAggExp `graphql:"identityMembershipSummariesAggregate(filter_input: $filter_input)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"filter_input": params.FilterInput,
	})
	return q.IdentityMembershipSummariesAggregate, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.IdentityMembershipSummaries, error) {
	var q struct {
		IdentityMembershipSummariesById *schema.IdentityMembershipSummaries `graphql:"identityMembershipSummariesById(id: $id)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"id": id,
	})
	return q.IdentityMembershipSummariesById, res.Error
}
