// Code generated by generateql. DO NOT EDIT.

package attachmentsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/sharedql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs SharedAttachments query operations.
type QueryHandler interface {
	// List runs the "sharedAttachments" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.SharedAttachments, error)
	// Find runs the "sharedAttachments" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.SharedAttachments, error)
	// Aggregate runs the "sharedAttachmentsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.SharedAttachmentsAggExp, error)
	// Get runs the "sharedAttachmentsById" query.
	Get(ctx context.Context, id string) (*schemaql.SharedAttachments, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs SharedAttachments mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteSharedAttachmentsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteSharedAttachmentsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteSharedAttachmentsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertSharedAttachments" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertSharedAttachmentsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertSharedAttachmentsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateSharedAttachmentsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateSharedAttachmentsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateSharedAttachmentsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateSharedAttachmentsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs SharedAttachments subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "sharedAttachments" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "sharedAttachmentsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "sharedAttachmentsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.SharedAttachments] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertSharedAttachmentsResponse, schemaql.UpdateSharedAttachmentsByIdResponse, schemaql.DeleteSharedAttachmentsByIdResponse] = (*mutationHandler)(nil)
