// Code generated by generateql. DO NOT EDIT.

package attachmentsql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/sharedql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteSharedAttachmentsByIdResponse = schemaql.DeleteSharedAttachmentsByIdResponse
type InsertSharedAttachmentsResponse = schemaql.InsertSharedAttachmentsResponse
type SharedAttachments = schemaql.SharedAttachments
type SharedAttachmentsAggExp = schemaql.SharedAttachmentsAggExp
type UpdateSharedAttachmentsByIdResponse = schemaql.UpdateSharedAttachmentsByIdResponse
