// Code generated by generateql. DO NOT EDIT.

package members

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteOrganisationMembersByIdResponse, error) {
	var out schema.DeleteOrganisationMembersByIdResponse
	args := map[string]any{
		"keyId": graphql.Var(keyId, "String1"),
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "OrganisationMembersBoolExp")
	}
	res := <-h.gql.MutateFields("deleteOrganisationMembersById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertOrganisationMembersObjectInput, params InsertParams) (schema.InsertOrganisationMembersResponse, error) {
	var out schema.InsertOrganisationMembersResponse
	args := map[string]any{
		"objects": graphql.Var(objects, "[InsertOrganisationMembersObjectInput!]"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "OrganisationMembersBoolExp")
	}
	res := <-h.gql.MutateFields("insertOrganisationMembers", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateOrganisationMembersByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateOrganisationMembersByIdResponse, error) {
	var out schema.UpdateOrganisationMembersByIdResponse
	args := map[string]any{
		"keyId":         graphql.Var(keyId, "String1"),
		"updateColumns": graphql.Var(updateColumns, "UpdateOrganisationMembersByIdUpdateColumnsInput"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "OrganisationMembersBoolExp")
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "OrganisationMembersBoolExp")
	}
	res := <-h.gql.MutateFields("updateOrganisationMembersById", &out, args)
	return out, res.Error
}
