// Code generated by generate-ql. DO NOT EDIT.

package members

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error) {
	var q struct {
		OrganisationMembers []schema.OrganisationMembers `graphql:"organisationMembers(limit: $limit, offset: $offset, order_by: $order_by, where: $where)"`
	}
	return h.gql.Subscribe(&q, map[string]any{
		"limit":    params.Limit,
		"offset":   params.Offset,
		"order_by": params.OrderBy,
		"where":    params.Where,
	})
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error) {
	var q struct {
		OrganisationMembersAggregate *schema.OrganisationMembersAggExp `graphql:"organisationMembersAggregate(filter_input: $filter_input)"`
	}
	return h.gql.Subscribe(&q, map[string]any{
		"filter_input": params.FilterInput,
	})
}

func (h *subscriptionHandler) OnById(ctx context.Context, id string) (*runtime.Subscription, error) {
	var q struct {
		OrganisationMembersById *schema.OrganisationMembers `graphql:"organisationMembersById(id: $id)"`
	}
	return h.gql.Subscribe(&q, map[string]any{
		"id": id,
	})
}
