// Code generated by generateql. DO NOT EDIT.

package schemaql

// MediaResource is the MediaResource model.
type MediaResource struct {
	CreateTime   string  `graphql:"createTime"`
	Filename     *string `graphql:"filename"`
	Id           string  `graphql:"id"`
	MimeType     *string `graphql:"mimeType"`
	Name         string  `graphql:"name"`
	ThumbnailUrl *string `graphql:"thumbnailUrl"`
	Url          *string `graphql:"url"`
	Uuid         *string `graphql:"uuid"`
}
