// Code generated by generateql. DO NOT EDIT.

package losdiscountsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs ResourceLosDiscounts query operations.
type QueryHandler interface {
	// List runs the "resourceLosDiscounts" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.ResourceLosDiscounts, error)
	// Find runs the "resourceLosDiscounts" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.ResourceLosDiscounts, error)
	// Aggregate runs the "resourceLosDiscountsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ResourceLosDiscountsAggExp, error)
	// Get runs the "resourceLosDiscountsById" query.
	Get(ctx context.Context, id string) (*schemaql.ResourceLosDiscounts, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ResourceLosDiscounts mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteResourceLosDiscountsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceLosDiscountsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteResourceLosDiscountsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertResourceLosDiscounts" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceLosDiscountsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertResourceLosDiscountsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateResourceLosDiscountsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceLosDiscountsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateResourceLosDiscountsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateResourceLosDiscountsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ResourceLosDiscounts subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "resourceLosDiscounts" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "resourceLosDiscountsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "resourceLosDiscountsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.ResourceLosDiscounts] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertResourceLosDiscountsResponse, schemaql.UpdateResourceLosDiscountsByIdResponse, schemaql.DeleteResourceLosDiscountsByIdResponse] = (*mutationHandler)(nil)
