// Code generated by generate-ql. DO NOT EDIT.

package resource

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteOrganisationResourceByIdResponse, error) {
	var q struct {
		DeleteOrganisationResourceById schema.DeleteOrganisationResourceByIdResponse `graphql:"deleteOrganisationResourceById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteOrganisationResourceById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertOrganisationResourceObjectInput, params InsertParams) (schema.InsertOrganisationResourceResponse, error) {
	var q struct {
		InsertOrganisationResource schema.InsertOrganisationResourceResponse `graphql:"insertOrganisationResource(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertOrganisationResource, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateOrganisationResourceByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateOrganisationResourceByIdResponse, error) {
	var q struct {
		UpdateOrganisationResourceById schema.UpdateOrganisationResourceByIdResponse `graphql:"updateOrganisationResourceById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateOrganisationResourceById, res.Error
}
