// Code generated by generateql. DO NOT EDIT.

package resource

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.OrganisationResource, error) {
	var out []schema.OrganisationResource
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = graphql.VarPtr(params.Limit, "Int")
	}
	if params.Offset != nil {
		args["offset"] = graphql.VarPtr(params.Offset, "Int")
	}
	if params.OrderBy != nil {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[OrganisationResourceOrderByExp!]")
	}
	if params.Where != nil {
		args["where"] = graphql.VarPtr(params.Where, "OrganisationResourceBoolExp")
	}
	res := <-h.gql.QueryFields("organisationResource", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.OrganisationResourceAggExp, error) {
	var out *schema.OrganisationResourceAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "OrganisationResourceFilterInput")
	}
	res := <-h.gql.QueryFields("organisationResourceAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.OrganisationResource, error) {
	var out *schema.OrganisationResource
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	res := <-h.gql.QueryFields("organisationResourceById", &out, args)
	return out, res.Error
}
