// Code generated by generateql. DO NOT EDIT.

package usagelimitsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeUsageLimits row.
type CreateInput struct {
	Id               string        `json:"id"`
	MaxRedemptions   graphql.Int64 `json:"maxRedemptions,omitzero"`
	PerCustomerLimit int32         `json:"perCustomerLimit,omitzero"`
}

// UpdateInput holds the fields to change on a PromocodeUsageLimits row; each set field becomes a column update.
type UpdateInput struct {
	Id               graphql.Nullable[string]        `json:"id"`
	MaxRedemptions   graphql.Nullable[graphql.Int64] `json:"maxRedemptions"`
	PerCustomerLimit graphql.Nullable[int32]         `json:"perCustomerLimit"`
}
