// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/bookingql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs BookingResource query operations.
type QueryHandler interface {
	// List runs the "bookingResource" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.BookingResource, error)
	// Find runs the "bookingResource" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.BookingResource, error)
	// Aggregate runs the "bookingResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.BookingResourceAggExp, error)
	// Get runs the "bookingResourceById" query.
	Get(ctx context.Context, id string) (*schemaql.BookingResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs BookingResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteBookingResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteBookingResourceByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteBookingResourceByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertBookingResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertBookingResourceResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertBookingResourceResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateBookingResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateBookingResourceByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateBookingResourceByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateBookingResourceByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs BookingResource subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "bookingResource" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "bookingResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "bookingResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.BookingResource] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertBookingResourceResponse, schemaql.UpdateBookingResourceByIdResponse, schemaql.DeleteBookingResourceByIdResponse] = (*mutationHandler)(nil)
