// Code generated by generateql. DO NOT EDIT.

package refundtiersql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ScheduleRefundTiers query operations.
type QueryHandler interface {
	// Find runs the "scheduleRefundTiers" query.
	Find(ctx context.Context, obj CreateInput, req ...*FindRequest) ([]schemaql.ScheduleRefundTiers, error)
	// Aggregate runs the "scheduleRefundTiersAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ScheduleRefundTiersAggExp, error)
	// Get runs the "scheduleRefundTiersById" query.
	Get(ctx context.Context, id string) (*schemaql.ScheduleRefundTiers, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ScheduleRefundTiers mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteScheduleRefundTiersById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleRefundTiersByIdResponse, error)
	// Create runs the "insertScheduleRefundTiers" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleRefundTiersResponse, error)
	// Update runs the "updateScheduleRefundTiersById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleRefundTiersByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ScheduleRefundTiers subscription operations.
type SubscriptionHandler interface {
	// OnFind runs the "scheduleRefundTiers" subscription.
	OnFind(ctx context.Context, obj CreateInput, req ...*OnFindRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "scheduleRefundTiersAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "scheduleRefundTiersById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
