// Code generated by generateql. DO NOT EDIT.

package listsql

import (
	"github.com/oh-tarnished/generateql/examples/mailkite/mailkiteql/campaignql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type CampaignLists = schemaql.CampaignLists
type CampaignListsAggExp = schemaql.CampaignListsAggExp
type DeleteCampaignListsByIdResponse = schemaql.DeleteCampaignListsByIdResponse
type InsertCampaignListsResponse = schemaql.InsertCampaignListsResponse
type UpdateCampaignListsByIdResponse = schemaql.UpdateCampaignListsByIdResponse
