// Code generated by generateql. DO NOT EDIT.

package exceptionsql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// Filter fields for ScheduleExceptions. Build predicates like AvailabilityExceptionId.Eq(v) and combine
// them with And/Or/Not.
var (
	AvailabilityExceptionId = graphql.StringField{Col: "availabilityExceptionId"}
	Id                      = graphql.StringField{Col: "id"}
	ScheduleId              = graphql.StringField{Col: "scheduleId"}
)

// ScheduleAvailabilityException filters by the scheduleAvailabilityException relation, taking a predicate from that resource.
func ScheduleAvailabilityException(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("scheduleAvailabilityException", p)
}

// ScheduleResource filters by the scheduleResource relation, taking a predicate from that resource.
func ScheduleResource(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("scheduleResource", p)
}

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
