// Code generated by generateql. DO NOT EDIT.

package exceptionsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, req ...*ListRequest) ([]schemaql.ScheduleExceptions, error) {
	var out []schemaql.ScheduleExceptions
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		args["limit"] = graphql.VarPtr(r.limit, "Int")
	}
	if !graphql.IsOmitted(r.offset) {
		args["offset"] = graphql.VarPtr(r.offset, "Int")
	}
	if !graphql.IsOmitted(r.orderBy) {
		args["order_by"] = graphql.VarPtr(r.orderBy, "[ScheduleExceptionsOrderByExp!]")
	}
	if !graphql.IsOmitted(r.where) {
		args["where"] = graphql.VarPtr(r.where, "ScheduleExceptionsBoolExp")
	}
	res := <-h.gql.QueryFields(ctx, "scheduleExceptions", &out, args)
	return out, res.Error
}

func (h *queryHandler) Find(ctx context.Context, req ...*ListRequest) (*schemaql.ScheduleExceptions, error) {
	var out []schemaql.ScheduleExceptions
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.offset) {
		args["offset"] = graphql.VarPtr(r.offset, "Int")
	}
	if !graphql.IsOmitted(r.orderBy) {
		args["order_by"] = graphql.VarPtr(r.orderBy, "[ScheduleExceptionsOrderByExp!]")
	}
	if !graphql.IsOmitted(r.where) {
		args["where"] = graphql.VarPtr(r.where, "ScheduleExceptionsBoolExp")
	}
	args["limit"] = graphql.VarPtr(1, "Int")
	res := <-h.gql.QueryFields(ctx, "scheduleExceptions", &out, args)
	if res.Error != nil {
		return nil, res.Error
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

func (h *queryHandler) Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ScheduleExceptionsAggExp, error) {
	var out *schemaql.ScheduleExceptionsAggExp
	var r AggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		filterInput["limit"] = r.limit
	}
	if !graphql.IsOmitted(r.offset) {
		filterInput["offset"] = r.offset
	}
	if !graphql.IsOmitted(r.orderBy) {
		filterInput["order_by"] = r.orderBy
	}
	if !graphql.IsOmitted(r.where) {
		filterInput["where"] = r.where
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "ScheduleExceptionsFilterInput")
	}
	res := <-h.gql.QueryFields(ctx, "scheduleExceptionsAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) Get(ctx context.Context, id string) (*schemaql.ScheduleExceptions, error) {
	var out *schemaql.ScheduleExceptions
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	res := <-h.gql.QueryFields(ctx, "scheduleExceptionsById", &out, args)
	return out, res.Error
}
