// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/mailkite/mailkiteql/templateql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs TemplateResource query operations.
type QueryHandler interface {
	// List runs the "templateResource" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.TemplateResource, error)
	// Find runs the "templateResource" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.TemplateResource, error)
	// Aggregate runs the "templateResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.TemplateResourceAggExp, error)
	// Get runs the "templateResourceById" query.
	Get(ctx context.Context, id string) (*schemaql.TemplateResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs TemplateResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteTemplateResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteTemplateResourceByIdResponse, error)
	// Create runs the "insertTemplateResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertTemplateResourceResponse, error)
	// Update runs the "updateTemplateResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateTemplateResourceByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs TemplateResource subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "templateResource" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "templateResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "templateResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
