// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"github.com/oh-tarnished/generateql/examples/mailkite/mailkiteql/templateql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteTemplateResourceByIdResponse = schemaql.DeleteTemplateResourceByIdResponse
type InsertTemplateResourceResponse = schemaql.InsertTemplateResourceResponse
type TemplateResource = schemaql.TemplateResource
type TemplateResourceAggExp = schemaql.TemplateResourceAggExp
type UpdateTemplateResourceByIdResponse = schemaql.UpdateTemplateResourceByIdResponse
