// Code generated by generateql. DO NOT EDIT.

package recurringrulesql

// CreateInput holds the settable fields for creating one ScheduleRecurringRules row.
type CreateInput struct {
	Closes     string `json:"closes,omitzero"`
	Id         string `json:"id"`
	Opens      string `json:"opens,omitzero"`
	Rrule      string `json:"rrule"`
	ScheduleId string `json:"scheduleId"`
}

// UpdateInput holds the fields to change on a ScheduleRecurringRules row; each set field becomes a column update.
type UpdateInput struct {
	Closes     string `json:"closes,omitzero"`
	Id         string `json:"id,omitzero"`
	Opens      string `json:"opens,omitzero"`
	Rrule      string `json:"rrule,omitzero"`
	ScheduleId string `json:"scheduleId,omitzero"`
}
