// Code generated by generateql. DO NOT EDIT.

package recurringrulesql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleRecurringRulesByIdResponse = schemaql.DeleteScheduleRecurringRulesByIdResponse
type InsertScheduleRecurringRulesResponse = schemaql.InsertScheduleRecurringRulesResponse
type ScheduleRecurringRules = schemaql.ScheduleRecurringRules
type ScheduleRecurringRulesAggExp = schemaql.ScheduleRecurringRulesAggExp
type UpdateScheduleRecurringRulesByIdResponse = schemaql.UpdateScheduleRecurringRulesByIdResponse
