// Code generated by generateql. DO NOT EDIT.

package recurringrulesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleRecurringRulesByIdResponse, error) {
	var out schemaql.DeleteScheduleRecurringRulesByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ScheduleRecurringRulesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deleteScheduleRecurringRulesById", &out, args)
	return out, res.Error
}

// DeleteOp returns Delete as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) DeleteOp(keyId string, result *schemaql.DeleteScheduleRecurringRulesByIdResponse, req ...*DeleteRequest) runtime.BatchOp {
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ScheduleRecurringRulesBoolExp")
	}
	return runtime.BatchOp{Field: "deleteScheduleRecurringRulesById", Args: args, Result: result}
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleRecurringRulesResponse, error) {
	var out schemaql.InsertScheduleRecurringRulesResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertScheduleRecurringRulesObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ScheduleRecurringRulesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertScheduleRecurringRules", &out, args)
	return out, res.Error
}

// CreateOp returns Create as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) CreateOp(obj CreateInput, result *schemaql.InsertScheduleRecurringRulesResponse, req ...*CreateRequest) runtime.BatchOp {
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertScheduleRecurringRulesObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ScheduleRecurringRulesBoolExp")
	}
	return runtime.BatchOp{Field: "insertScheduleRecurringRules", Args: args, Result: result}
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleRecurringRulesByIdResponse, error) {
	var out schemaql.UpdateScheduleRecurringRulesByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ScheduleRecurringRulesBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ScheduleRecurringRulesBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateScheduleRecurringRulesByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updateScheduleRecurringRulesById", &out, args)
	return out, res.Error
}

// UpdateIfMatch runs Update guarded by match, an optimistic-concurrency precondition
// (e.g. Etag.Eq(prev)). It returns graphql.ErrConflict when no row matched the precondition.
func (h *mutationHandler) UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateScheduleRecurringRulesByIdResponse, error) {
	resp, err := h.Update(ctx, keyId, patch, Update().PreCheck(match))
	if err != nil {
		return resp, err
	}
	if resp.AffectedRows == 0 {
		return resp, graphql.ErrConflict
	}
	return resp, nil
}

// UpdateOp returns Update as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateScheduleRecurringRulesByIdResponse, req ...*UpdateRequest) runtime.BatchOp {
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ScheduleRecurringRulesBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ScheduleRecurringRulesBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateScheduleRecurringRulesByIdUpdateColumnsInput")
	return runtime.BatchOp{Field: "updateScheduleRecurringRulesById", Args: args, Result: result}
}
