// Code generated by generateql. DO NOT EDIT.

package policiesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/propertyql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PropertyPolicies query operations.
type QueryHandler interface {
	// List runs the "propertyPolicies" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.PropertyPolicies, error)
	// Find runs the "propertyPolicies" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.PropertyPolicies, error)
	// Aggregate runs the "propertyPoliciesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.PropertyPoliciesAggExp, error)
	// Get runs the "propertyPoliciesById" query.
	Get(ctx context.Context, id string) (*schemaql.PropertyPolicies, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PropertyPolicies mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePropertyPoliciesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeletePropertyPoliciesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeletePropertyPoliciesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPropertyPolicies" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertPropertyPoliciesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertPropertyPoliciesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePropertyPoliciesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdatePropertyPoliciesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdatePropertyPoliciesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdatePropertyPoliciesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PropertyPolicies subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "propertyPolicies" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "propertyPoliciesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "propertyPoliciesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.PropertyPolicies] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertPropertyPoliciesResponse, schemaql.UpdatePropertyPoliciesByIdResponse, schemaql.DeletePropertyPoliciesByIdResponse] = (*mutationHandler)(nil)
