// Code generated by generateql. DO NOT EDIT.

package policiesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyPolicies row.
type CreateInput struct {
	CheckinTime  string    `json:"checkinTime,omitzero"`
	CheckoutTime string    `json:"checkoutTime,omitzero"`
	HouseRules   []*string `json:"houseRules,omitzero"`
	Id           string    `json:"id"`
	Notes        string    `json:"notes,omitzero"`
}

// UpdateInput holds the fields to change on a PropertyPolicies row; each set field becomes a column update.
type UpdateInput struct {
	CheckinTime  graphql.Nullable[string]    `json:"checkinTime"`
	CheckoutTime graphql.Nullable[string]    `json:"checkoutTime"`
	HouseRules   graphql.Nullable[[]*string] `json:"houseRules"`
	Id           graphql.Nullable[string]    `json:"id"`
	Notes        graphql.Nullable[string]    `json:"notes"`
}
