// Code generated by generateql. DO NOT EDIT.

package users

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.IdentityUsers, error) {
	var out []schema.IdentityUsers
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = graphql.VarPtr(params.Limit, "Int")
	}
	if params.Offset != nil {
		args["offset"] = graphql.VarPtr(params.Offset, "Int")
	}
	if params.OrderBy != nil {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[IdentityUsersOrderByExp!]")
	}
	if params.Where != nil {
		args["where"] = graphql.VarPtr(params.Where, "IdentityUsersBoolExp")
	}
	res := <-h.gql.QueryFields("identityUsers", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.IdentityUsersAggExp, error) {
	var out *schema.IdentityUsersAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "IdentityUsersFilterInput")
	}
	res := <-h.gql.QueryFields("identityUsersAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.IdentityUsers, error) {
	var out *schema.IdentityUsers
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	res := <-h.gql.QueryFields("identityUsersById", &out, args)
	return out, res.Error
}
