// Code generated by generate-ql. DO NOT EDIT.

package losdiscounts

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceLosDiscountsByIdResponse, error) {
	var q struct {
		DeleteResourceLosDiscountsById schema.DeleteResourceLosDiscountsByIdResponse `graphql:"deleteResourceLosDiscountsById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteResourceLosDiscountsById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceLosDiscountsObjectInput, params InsertParams) (schema.InsertResourceLosDiscountsResponse, error) {
	var q struct {
		InsertResourceLosDiscounts schema.InsertResourceLosDiscountsResponse `graphql:"insertResourceLosDiscounts(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertResourceLosDiscounts, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceLosDiscountsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceLosDiscountsByIdResponse, error) {
	var q struct {
		UpdateResourceLosDiscountsById schema.UpdateResourceLosDiscountsByIdResponse `graphql:"updateResourceLosDiscountsById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateResourceLosDiscountsById, res.Error
}
