// Code generated by generateql. DO NOT EDIT.

package losdiscounts

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceLosDiscountsByIdResponse, error) {
	var out schema.DeleteResourceLosDiscountsByIdResponse
	args := map[string]any{
		"keyId": graphql.Var(keyId, "String1"),
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ResourceLosDiscountsBoolExp")
	}
	res := <-h.gql.MutateFields("deleteResourceLosDiscountsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceLosDiscountsObjectInput, params InsertParams) (schema.InsertResourceLosDiscountsResponse, error) {
	var out schema.InsertResourceLosDiscountsResponse
	args := map[string]any{
		"objects": graphql.Var(objects, "[InsertResourceLosDiscountsObjectInput!]"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ResourceLosDiscountsBoolExp")
	}
	res := <-h.gql.MutateFields("insertResourceLosDiscounts", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceLosDiscountsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceLosDiscountsByIdResponse, error) {
	var out schema.UpdateResourceLosDiscountsByIdResponse
	args := map[string]any{
		"keyId":         graphql.Var(keyId, "String1"),
		"updateColumns": graphql.Var(updateColumns, "UpdateResourceLosDiscountsByIdUpdateColumnsInput"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ResourceLosDiscountsBoolExp")
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ResourceLosDiscountsBoolExp")
	}
	res := <-h.gql.MutateFields("updateResourceLosDiscountsById", &out, args)
	return out, res.Error
}
