// Code generated by generateql. DO NOT EDIT.

package cancellationpoliciesql

// CreateInput holds the settable fields for creating one ScheduleCancellationPolicies row.
type CreateInput struct {
	Id string `json:"id"`
}

// UpdateInput holds the fields to change on a ScheduleCancellationPolicies row; each set field becomes a column update.
type UpdateInput struct {
	Id string `json:"id,omitzero"`
}
