// Code generated by generateql. DO NOT EDIT.

package cancellationpoliciesql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// Filter fields for ScheduleCancellationPolicies. Build predicates like Id.Eq(v) and combine
// them with And/Or/Not.
var (
	Id = graphql.StringField{Col: "id"}
)

// ScheduleRefundTiers filters by the scheduleRefundTiers relation, taking a predicate from that resource.
func ScheduleRefundTiers(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("scheduleRefundTiers", p)
}

// ScheduleResources filters by the scheduleResources relation, taking a predicate from that resource.
func ScheduleResources(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("scheduleResources", p)
}

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
