// Code generated by generate-ql. DO NOT EDIT.

package offerings

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceOfferingsByIdResponse, error) {
	var q struct {
		DeleteResourceOfferingsById schema.DeleteResourceOfferingsByIdResponse `graphql:"deleteResourceOfferingsById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteResourceOfferingsById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceOfferingsObjectInput, params InsertParams) (schema.InsertResourceOfferingsResponse, error) {
	var q struct {
		InsertResourceOfferings schema.InsertResourceOfferingsResponse `graphql:"insertResourceOfferings(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertResourceOfferings, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceOfferingsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceOfferingsByIdResponse, error) {
	var q struct {
		UpdateResourceOfferingsById schema.UpdateResourceOfferingsByIdResponse `graphql:"updateResourceOfferingsById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateResourceOfferingsById, res.Error
}
