// Code generated by generateql. DO NOT EDIT.

package offerings

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error) {
	var out []schema.ResourceOfferings
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = graphql.VarPtr(params.Limit, "Int")
	}
	if params.Offset != nil {
		args["offset"] = graphql.VarPtr(params.Offset, "Int")
	}
	if params.OrderBy != nil {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[ResourceOfferingsOrderByExp!]")
	}
	if params.Where != nil {
		args["where"] = graphql.VarPtr(params.Where, "ResourceOfferingsBoolExp")
	}
	return h.gql.SubscribeFields("resourceOfferings", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error) {
	var out *schema.ResourceOfferingsAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "ResourceOfferingsFilterInput")
	}
	return h.gql.SubscribeFields("resourceOfferingsAggregate", &out, args)
}

func (h *subscriptionHandler) OnById(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schema.ResourceOfferings
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	return h.gql.SubscribeFields("resourceOfferingsById", &out, args)
}
