// Code generated by generateql. DO NOT EDIT.

package cancellationpolicies

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// ListParams holds the optional arguments for List.
type ListParams struct {
	Limit   param.Opt[int]
	Offset  param.Opt[int]
	OrderBy []inputs.ScheduleCancellationPoliciesOrderByExp
	Where   inputs.ScheduleCancellationPoliciesBoolExp
}

// AggregateParams holds the optional arguments for Aggregate.
type AggregateParams struct {
	FilterInput inputs.ScheduleCancellationPoliciesFilterInput
}

// DeleteByIdParams holds the optional arguments for DeleteById.
type DeleteByIdParams struct {
	PreCheck inputs.ScheduleCancellationPoliciesBoolExp
}

// InsertParams holds the optional arguments for Insert.
type InsertParams struct {
	PostCheck inputs.ScheduleCancellationPoliciesBoolExp
}

// UpdateByIdParams holds the optional arguments for UpdateById.
type UpdateByIdParams struct {
	PostCheck inputs.ScheduleCancellationPoliciesBoolExp
	PreCheck  inputs.ScheduleCancellationPoliciesBoolExp
}

// OnListParams holds the optional arguments for OnList.
type OnListParams struct {
	Limit   param.Opt[int]
	Offset  param.Opt[int]
	OrderBy []inputs.ScheduleCancellationPoliciesOrderByExp
	Where   inputs.ScheduleCancellationPoliciesBoolExp
}

// OnAggregateParams holds the optional arguments for OnAggregate.
type OnAggregateParams struct {
	FilterInput inputs.ScheduleCancellationPoliciesFilterInput
}

// QueryHandler runs ScheduleCancellationPolicies query operations.
type QueryHandler interface {
	// List runs the "scheduleCancellationPolicies" query.
	List(ctx context.Context, params ListParams) ([]schema.ScheduleCancellationPolicies, error)
	// Aggregate runs the "scheduleCancellationPoliciesAggregate" query.
	Aggregate(ctx context.Context, params AggregateParams) (*schema.ScheduleCancellationPoliciesAggExp, error)
	// ById runs the "scheduleCancellationPoliciesById" query.
	ById(ctx context.Context, id string) (*schema.ScheduleCancellationPolicies, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ScheduleCancellationPolicies mutation operations.
type MutationHandler interface {
	// DeleteById runs the "deleteScheduleCancellationPoliciesById" mutation.
	DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteScheduleCancellationPoliciesByIdResponse, error)
	// Insert runs the "insertScheduleCancellationPolicies" mutation.
	Insert(ctx context.Context, objects []inputs.InsertScheduleCancellationPoliciesObjectInput, params InsertParams) (schema.InsertScheduleCancellationPoliciesResponse, error)
	// UpdateById runs the "updateScheduleCancellationPoliciesById" mutation.
	UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateScheduleCancellationPoliciesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateScheduleCancellationPoliciesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ScheduleCancellationPolicies subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "scheduleCancellationPolicies" subscription.
	OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error)
	// OnAggregate runs the "scheduleCancellationPoliciesAggregate" subscription.
	OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error)
	// OnById runs the "scheduleCancellationPoliciesById" subscription.
	OnById(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
