// Code generated by generateql. DO NOT EDIT.

package timewindowsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/bookingql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs BookingTimeWindows query operations.
type QueryHandler interface {
	// Find runs the "bookingTimeWindows" query.
	Find(ctx context.Context, req ...*FindRequest) ([]schemaql.BookingTimeWindows, error)
	// Aggregate runs the "bookingTimeWindowsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.BookingTimeWindowsAggExp, error)
	// Get runs the "bookingTimeWindowsById" query.
	Get(ctx context.Context, id string) (*schemaql.BookingTimeWindows, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs BookingTimeWindows mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteBookingTimeWindowsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteBookingTimeWindowsByIdResponse, error)
	// Create runs the "insertBookingTimeWindows" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertBookingTimeWindowsResponse, error)
	// Update runs the "updateBookingTimeWindowsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateBookingTimeWindowsByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs BookingTimeWindows subscription operations.
type SubscriptionHandler interface {
	// OnFind runs the "bookingTimeWindows" subscription.
	OnFind(ctx context.Context, req ...*OnFindRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "bookingTimeWindowsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "bookingTimeWindowsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
