// Code generated by generateql. DO NOT EDIT.

package timewindowsql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// CreateInput holds the settable fields for creating one BookingTimeWindows row.
type CreateInput struct {
	EndTime   string `json:"endTime"`
	Id        string `json:"id"`
	StartTime string `json:"startTime"`
}

// UpdateInput holds the fields to change on a BookingTimeWindows row; each set field becomes a column update.
type UpdateInput struct {
	EndTime   graphql.Nullable[string] `json:"endTime"`
	Id        graphql.Nullable[string] `json:"id"`
	StartTime graphql.Nullable[string] `json:"startTime"`
}
