// Code generated by generateql. DO NOT EDIT.

package iddocumentsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for IdentityIdDocuments. Build predicates like AttachmentId.Eq(v) and combine
// them with And/Or/Not.
var (
	AttachmentId   = graphql.StringField{Col: "attachmentId"}
	ExpiryDate     = graphql.StringField{Col: "expiryDate"}
	Id             = graphql.StringField{Col: "id"}
	IssueDate      = graphql.StringField{Col: "issueDate"}
	IssuePlace     = graphql.StringField{Col: "issuePlace"}
	IssuingCountry = graphql.StringField{Col: "issuingCountry"}
	Number         = graphql.StringField{Col: "number"}
	Type           = graphql.StringField{Col: "type"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
