// Code generated by generateql. DO NOT EDIT.

package scopesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/promocodeql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PromocodeScopes query operations.
type QueryHandler interface {
	// List runs the "promocodeScopes" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.PromocodeScopes, error)
	// Find runs the "promocodeScopes" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.PromocodeScopes, error)
	// Aggregate runs the "promocodeScopesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.PromocodeScopesAggExp, error)
	// Get runs the "promocodeScopesById" query.
	Get(ctx context.Context, id string) (*schemaql.PromocodeScopes, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PromocodeScopes mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePromocodeScopesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeletePromocodeScopesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeletePromocodeScopesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPromocodeScopes" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertPromocodeScopesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertPromocodeScopesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePromocodeScopesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdatePromocodeScopesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdatePromocodeScopesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdatePromocodeScopesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PromocodeScopes subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "promocodeScopes" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "promocodeScopesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "promocodeScopesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.PromocodeScopes] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertPromocodeScopesResponse, schemaql.UpdatePromocodeScopesByIdResponse, schemaql.DeletePromocodeScopesByIdResponse] = (*mutationHandler)(nil)
