// Code generated by generateql. DO NOT EDIT.

package statsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one CampaignStats row.
type CreateInput struct {
	Bounces        graphql.Int64 `json:"bounces,omitzero"`
	Clicks         graphql.Int64 `json:"clicks,omitzero"`
	Id             string        `json:"id"`
	RecipientCount graphql.Int64 `json:"recipientCount,omitzero"`
	Sent           graphql.Int64 `json:"sent,omitzero"`
	Views          graphql.Int64 `json:"views,omitzero"`
}

// UpdateInput holds the fields to change on a CampaignStats row; each set field becomes a column update.
type UpdateInput struct {
	Bounces        graphql.Int64 `json:"bounces,omitzero"`
	Clicks         graphql.Int64 `json:"clicks,omitzero"`
	Id             string        `json:"id,omitzero"`
	RecipientCount graphql.Int64 `json:"recipientCount,omitzero"`
	Sent           graphql.Int64 `json:"sent,omitzero"`
	Views          graphql.Int64 `json:"views,omitzero"`
}
