// Code generated by generateql. DO NOT EDIT.

package statsql

import (
	"github.com/oh-tarnished/generateql/examples/mailkite/mailkiteql/campaignql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type CampaignStats = schemaql.CampaignStats
type CampaignStatsAggExp = schemaql.CampaignStatsAggExp
type DeleteCampaignStatsByIdResponse = schemaql.DeleteCampaignStatsByIdResponse
type InsertCampaignStatsResponse = schemaql.InsertCampaignStatsResponse
type UpdateCampaignStatsByIdResponse = schemaql.UpdateCampaignStatsByIdResponse
