// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePropertyFeesByIdResponse is the DeletePropertyFeesByIdResponse model.
type DeletePropertyFeesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountId    *string `graphql:"amountId"`
		Code        string  `graphql:"code"`
		DisplayName *string `graphql:"displayName"`
		Id          string  `graphql:"id"`
		Percent     *int32  `graphql:"percent"`
		PricingUnit *string `graphql:"pricingUnit"`
		Taxable     *bool   `graphql:"taxable"`
		UnitId      string  `graphql:"unitId"`
	} `graphql:"returning"`
}

// InsertPropertyFeesResponse is the InsertPropertyFeesResponse model.
type InsertPropertyFeesResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountId    *string `graphql:"amountId"`
		Code        string  `graphql:"code"`
		DisplayName *string `graphql:"displayName"`
		Id          string  `graphql:"id"`
		Percent     *int32  `graphql:"percent"`
		PricingUnit *string `graphql:"pricingUnit"`
		Taxable     *bool   `graphql:"taxable"`
		UnitId      string  `graphql:"unitId"`
	} `graphql:"returning"`
}

// PropertyFees is the PropertyFees model.
type PropertyFees struct {
	AmountId    *string `graphql:"amountId"`
	Code        string  `graphql:"code"`
	DisplayName *string `graphql:"displayName"`
	Id          string  `graphql:"id"`
	Percent     *int32  `graphql:"percent"`
	PricingUnit *string `graphql:"pricingUnit"`
	Taxable     *bool   `graphql:"taxable"`
	UnitId      string  `graphql:"unitId"`
}

// PropertyFeesAggExp is the PropertyFeesAggExp model.
type PropertyFeesAggExp struct {
	Count    graphql.Int64 `graphql:"_count"`
	AmountId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"amountId"`
	Code struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"code"`
	DisplayName struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"displayName"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	Percent struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"percent"`
	PricingUnit struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"pricingUnit"`
	Taxable struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		BoolAnd       *bool         `graphql:"bool_and"`
		BoolOr        *bool         `graphql:"bool_or"`
		Every         *bool         `graphql:"every"`
	} `graphql:"taxable"`
	UnitId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"unitId"`
}

// UpdatePropertyFeesByIdResponse is the UpdatePropertyFeesByIdResponse model.
type UpdatePropertyFeesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountId    *string `graphql:"amountId"`
		Code        string  `graphql:"code"`
		DisplayName *string `graphql:"displayName"`
		Id          string  `graphql:"id"`
		Percent     *int32  `graphql:"percent"`
		PricingUnit *string `graphql:"pricingUnit"`
		Taxable     *bool   `graphql:"taxable"`
		UnitId      string  `graphql:"unitId"`
	} `graphql:"returning"`
}
