// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePropertyUnitMediasByIdResponse is the DeletePropertyUnitMediasByIdResponse model.
type DeletePropertyUnitMediasByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Description *string `graphql:"description"`
		Id          string  `graphql:"id"`
		MimeType    *string `graphql:"mimeType"`
		Primary     *bool   `graphql:"primary"`
		SortOrder   *int32  `graphql:"sortOrder"`
		Title       *string `graphql:"title"`
		Type        string  `graphql:"type"`
		UnitId      string  `graphql:"unitId"`
		Uri         string  `graphql:"uri"`
	} `graphql:"returning"`
}

// InsertPropertyUnitMediasResponse is the InsertPropertyUnitMediasResponse model.
type InsertPropertyUnitMediasResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Description *string `graphql:"description"`
		Id          string  `graphql:"id"`
		MimeType    *string `graphql:"mimeType"`
		Primary     *bool   `graphql:"primary"`
		SortOrder   *int32  `graphql:"sortOrder"`
		Title       *string `graphql:"title"`
		Type        string  `graphql:"type"`
		UnitId      string  `graphql:"unitId"`
		Uri         string  `graphql:"uri"`
	} `graphql:"returning"`
}

// PropertyUnitMedias is the PropertyUnitMedias model.
type PropertyUnitMedias struct {
	Description *string `graphql:"description"`
	Id          string  `graphql:"id"`
	MimeType    *string `graphql:"mimeType"`
	Primary     *bool   `graphql:"primary"`
	SortOrder   *int32  `graphql:"sortOrder"`
	Title       *string `graphql:"title"`
	Type        string  `graphql:"type"`
	UnitId      string  `graphql:"unitId"`
	Uri         string  `graphql:"uri"`
}

// PropertyUnitMediasAggExp is the PropertyUnitMediasAggExp model.
type PropertyUnitMediasAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	Description struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"description"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	MimeType struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"mimeType"`
	Primary struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		BoolAnd       *bool         `graphql:"bool_and"`
		BoolOr        *bool         `graphql:"bool_or"`
		Every         *bool         `graphql:"every"`
	} `graphql:"primary"`
	SortOrder struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"sortOrder"`
	Title struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"title"`
	Type struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"type"`
	UnitId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"unitId"`
	Uri struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"uri"`
}

// UpdatePropertyUnitMediasByIdResponse is the UpdatePropertyUnitMediasByIdResponse model.
type UpdatePropertyUnitMediasByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Description *string `graphql:"description"`
		Id          string  `graphql:"id"`
		MimeType    *string `graphql:"mimeType"`
		Primary     *bool   `graphql:"primary"`
		SortOrder   *int32  `graphql:"sortOrder"`
		Title       *string `graphql:"title"`
		Type        string  `graphql:"type"`
		UnitId      string  `graphql:"unitId"`
		Uri         string  `graphql:"uri"`
	} `graphql:"returning"`
}
