// Code generated by generateql. DO NOT EDIT.

package buffersettingsql

// CreateInput holds the settable fields for creating one ScheduleBufferSettings row.
type CreateInput struct {
	EndDelta   string `json:"endDelta,omitzero"`
	Gap        string `json:"gap,omitzero"`
	Id         string `json:"id"`
	MaxAdvance string `json:"maxAdvance,omitzero"`
	MinNotice  string `json:"minNotice,omitzero"`
	StartDelta string `json:"startDelta,omitzero"`
}

// UpdateInput holds the fields to change on a ScheduleBufferSettings row; each set field becomes a column update.
type UpdateInput struct {
	EndDelta   string `json:"endDelta,omitzero"`
	Gap        string `json:"gap,omitzero"`
	Id         string `json:"id,omitzero"`
	MaxAdvance string `json:"maxAdvance,omitzero"`
	MinNotice  string `json:"minNotice,omitzero"`
	StartDelta string `json:"startDelta,omitzero"`
}
