// Code generated by generateql. DO NOT EDIT.

package buffersettingsql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleBufferSettingsByIdResponse = schemaql.DeleteScheduleBufferSettingsByIdResponse
type InsertScheduleBufferSettingsResponse = schemaql.InsertScheduleBufferSettingsResponse
type ScheduleBufferSettings = schemaql.ScheduleBufferSettings
type ScheduleBufferSettingsAggExp = schemaql.ScheduleBufferSettingsAggExp
type UpdateScheduleBufferSettingsByIdResponse = schemaql.UpdateScheduleBufferSettingsByIdResponse
