// Code generated by generateql. DO NOT EDIT.

package buffersettingsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleBufferSettingsByIdResponse, error) {
	var out schemaql.DeleteScheduleBufferSettingsByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ScheduleBufferSettingsBoolExp")
	}
	res := <-h.gql.MutateFields("deleteScheduleBufferSettingsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleBufferSettingsResponse, error) {
	var out schemaql.InsertScheduleBufferSettingsResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertScheduleBufferSettingsObjectInput!]")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ScheduleBufferSettingsBoolExp")
	}
	res := <-h.gql.MutateFields("insertScheduleBufferSettings", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleBufferSettingsByIdResponse, error) {
	var out schemaql.UpdateScheduleBufferSettingsByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ScheduleBufferSettingsBoolExp")
	}
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ScheduleBufferSettingsBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateScheduleBufferSettingsByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields("updateScheduleBufferSettingsById", &out, args)
	return out, res.Error
}
