// Code generated by generate-ql. DO NOT EDIT.

package resource

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeletePromocodeResourceByIdResponse, error) {
	var out schema.DeletePromocodeResourceByIdResponse
	args := map[string]any{
		"keyId": keyId,
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("deletePromocodeResourceById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertPromocodeResourceObjectInput, params InsertParams) (schema.InsertPromocodeResourceResponse, error) {
	var out schema.InsertPromocodeResourceResponse
	args := map[string]any{
		"objects": objects,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	res := <-h.gql.MutateFields("insertPromocodeResource", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdatePromocodeResourceByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdatePromocodeResourceByIdResponse, error) {
	var out schema.UpdatePromocodeResourceByIdResponse
	args := map[string]any{
		"keyId":         keyId,
		"updateColumns": updateColumns,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("updatePromocodeResourceById", &out, args)
	return out, res.Error
}
