// Code generated by generateql. DO NOT EDIT.

package fees

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// ListParams holds the optional arguments for List.
type ListParams struct {
	Limit   param.Opt[int]
	Offset  param.Opt[int]
	OrderBy []inputs.ResourceFeesOrderByExp
	Where   inputs.ResourceFeesBoolExp
}

// AggregateParams holds the optional arguments for Aggregate.
type AggregateParams struct {
	FilterInput inputs.ResourceFeesFilterInput
}

// DeleteByIdParams holds the optional arguments for DeleteById.
type DeleteByIdParams struct {
	PreCheck inputs.ResourceFeesBoolExp
}

// InsertParams holds the optional arguments for Insert.
type InsertParams struct {
	PostCheck inputs.ResourceFeesBoolExp
}

// UpdateByIdParams holds the optional arguments for UpdateById.
type UpdateByIdParams struct {
	PostCheck inputs.ResourceFeesBoolExp
	PreCheck  inputs.ResourceFeesBoolExp
}

// OnListParams holds the optional arguments for OnList.
type OnListParams struct {
	Limit   param.Opt[int]
	Offset  param.Opt[int]
	OrderBy []inputs.ResourceFeesOrderByExp
	Where   inputs.ResourceFeesBoolExp
}

// OnAggregateParams holds the optional arguments for OnAggregate.
type OnAggregateParams struct {
	FilterInput inputs.ResourceFeesFilterInput
}

// QueryHandler runs ResourceFees query operations.
type QueryHandler interface {
	// List runs the "resourceFees" query.
	List(ctx context.Context, params ListParams) ([]schema.ResourceFees, error)
	// Aggregate runs the "resourceFeesAggregate" query.
	Aggregate(ctx context.Context, params AggregateParams) (*schema.ResourceFeesAggExp, error)
	// ById runs the "resourceFeesById" query.
	ById(ctx context.Context, id string) (*schema.ResourceFees, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ResourceFees mutation operations.
type MutationHandler interface {
	// DeleteById runs the "deleteResourceFeesById" mutation.
	DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceFeesByIdResponse, error)
	// Insert runs the "insertResourceFees" mutation.
	Insert(ctx context.Context, objects []inputs.InsertResourceFeesObjectInput, params InsertParams) (schema.InsertResourceFeesResponse, error)
	// UpdateById runs the "updateResourceFeesById" mutation.
	UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceFeesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceFeesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ResourceFees subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "resourceFees" subscription.
	OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error)
	// OnAggregate runs the "resourceFeesAggregate" subscription.
	OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error)
	// OnById runs the "resourceFeesById" subscription.
	OnById(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
