// Code generated by generate-ql. DO NOT EDIT.

package fees

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.ResourceFees, error) {
	var out []schema.ResourceFees
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = params.Limit
	}
	if params.Offset != nil {
		args["offset"] = params.Offset
	}
	if params.OrderBy != nil {
		args["order_by"] = params.OrderBy
	}
	if params.Where != nil {
		args["where"] = params.Where
	}
	res := <-h.gql.QueryFields("resourceFees", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.ResourceFeesAggExp, error) {
	var out *schema.ResourceFeesAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = params.FilterInput
	}
	res := <-h.gql.QueryFields("resourceFeesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.ResourceFees, error) {
	var out *schema.ResourceFees
	args := map[string]any{
		"id": id,
	}
	res := <-h.gql.QueryFields("resourceFeesById", &out, args)
	return out, res.Error
}
