// Code generated by generate-ql. DO NOT EDIT.

package fees

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.ResourceFees, error) {
	var q struct {
		ResourceFees []schema.ResourceFees `graphql:"resourceFees(limit: $limit, offset: $offset, order_by: $order_by, where: $where)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"limit":    params.Limit,
		"offset":   params.Offset,
		"order_by": params.OrderBy,
		"where":    params.Where,
	})
	return q.ResourceFees, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.ResourceFeesAggExp, error) {
	var q struct {
		ResourceFeesAggregate *schema.ResourceFeesAggExp `graphql:"resourceFeesAggregate(filter_input: $filter_input)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"filter_input": params.FilterInput,
	})
	return q.ResourceFeesAggregate, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.ResourceFees, error) {
	var q struct {
		ResourceFeesById *schema.ResourceFees `graphql:"resourceFeesById(id: $id)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"id": id,
	})
	return q.ResourceFeesById, res.Error
}
