// Code generated by generateql. DO NOT EDIT.

package taxes

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.ResourceTaxes, error) {
	var out []schema.ResourceTaxes
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = graphql.VarPtr(params.Limit, "Int")
	}
	if params.Offset != nil {
		args["offset"] = graphql.VarPtr(params.Offset, "Int")
	}
	if params.OrderBy != nil {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[ResourceTaxesOrderByExp!]")
	}
	if params.Where != nil {
		args["where"] = graphql.VarPtr(params.Where, "ResourceTaxesBoolExp")
	}
	res := <-h.gql.QueryFields("resourceTaxes", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.ResourceTaxesAggExp, error) {
	var out *schema.ResourceTaxesAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "ResourceTaxesFilterInput")
	}
	res := <-h.gql.QueryFields("resourceTaxesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.ResourceTaxes, error) {
	var out *schema.ResourceTaxes
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	res := <-h.gql.QueryFields("resourceTaxesById", &out, args)
	return out, res.Error
}
