// Code generated by generateql. DO NOT EDIT.

package daterangesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ScheduleDateRanges query operations.
type QueryHandler interface {
	// Find runs the "scheduleDateRanges" query.
	Find(ctx context.Context, req ...*FindRequest) ([]schemaql.ScheduleDateRanges, error)
	// Aggregate runs the "scheduleDateRangesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ScheduleDateRangesAggExp, error)
	// Get runs the "scheduleDateRangesById" query.
	Get(ctx context.Context, id string) (*schemaql.ScheduleDateRanges, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ScheduleDateRanges mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteScheduleDateRangesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleDateRangesByIdResponse, error)
	// Create runs the "insertScheduleDateRanges" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleDateRangesResponse, error)
	// Update runs the "updateScheduleDateRangesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleDateRangesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ScheduleDateRanges subscription operations.
type SubscriptionHandler interface {
	// OnFind runs the "scheduleDateRanges" subscription.
	OnFind(ctx context.Context, req ...*OnFindRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "scheduleDateRangesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "scheduleDateRangesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
