// Code generated by generateql. DO NOT EDIT.

package daterangesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ScheduleDateRanges query operations.
type QueryHandler interface {
	// List runs the "scheduleDateRanges" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.ScheduleDateRanges, error)
	// Find runs the "scheduleDateRanges" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.ScheduleDateRanges, error)
	// Aggregate runs the "scheduleDateRangesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ScheduleDateRangesAggExp, error)
	// Get runs the "scheduleDateRangesById" query.
	Get(ctx context.Context, id string) (*schemaql.ScheduleDateRanges, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ScheduleDateRanges mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteScheduleDateRangesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleDateRangesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteScheduleDateRangesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertScheduleDateRanges" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleDateRangesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertScheduleDateRangesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateScheduleDateRangesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleDateRangesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateScheduleDateRangesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateScheduleDateRangesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ScheduleDateRanges subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "scheduleDateRanges" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "scheduleDateRangesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "scheduleDateRangesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.ScheduleDateRanges] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertScheduleDateRangesResponse, schemaql.UpdateScheduleDateRangesByIdResponse, schemaql.DeleteScheduleDateRangesByIdResponse] = (*mutationHandler)(nil)
