// Code generated by generateql. DO NOT EDIT.

package availabilityexceptionsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleAvailabilityExceptionsByIdResponse, error) {
	var out schemaql.DeleteScheduleAvailabilityExceptionsByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ScheduleAvailabilityExceptionsBoolExp")
	}
	res := <-h.gql.MutateFields("deleteScheduleAvailabilityExceptionsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleAvailabilityExceptionsResponse, error) {
	var out schemaql.InsertScheduleAvailabilityExceptionsResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertScheduleAvailabilityExceptionsObjectInput!]")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ScheduleAvailabilityExceptionsBoolExp")
	}
	res := <-h.gql.MutateFields("insertScheduleAvailabilityExceptions", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleAvailabilityExceptionsByIdResponse, error) {
	var out schemaql.UpdateScheduleAvailabilityExceptionsByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ScheduleAvailabilityExceptionsBoolExp")
	}
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ScheduleAvailabilityExceptionsBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields("updateScheduleAvailabilityExceptionsById", &out, args)
	return out, res.Error
}
