// Code generated by generate-ql. DO NOT EDIT.

package contacts

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteBookingContactsByIdResponse, error) {
	var q struct {
		DeleteBookingContactsById schema.DeleteBookingContactsByIdResponse `graphql:"deleteBookingContactsById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteBookingContactsById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertBookingContactsObjectInput, params InsertParams) (schema.InsertBookingContactsResponse, error) {
	var q struct {
		InsertBookingContacts schema.InsertBookingContactsResponse `graphql:"insertBookingContacts(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertBookingContacts, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateBookingContactsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateBookingContactsByIdResponse, error) {
	var q struct {
		UpdateBookingContactsById schema.UpdateBookingContactsByIdResponse `graphql:"updateBookingContactsById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateBookingContactsById, res.Error
}
