// Code generated by generateql. DO NOT EDIT.

package contacts

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteBookingContactsByIdResponse, error) {
	var out schema.DeleteBookingContactsByIdResponse
	args := map[string]any{
		"keyId": graphql.Var(keyId, "String1"),
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "BookingContactsBoolExp")
	}
	res := <-h.gql.MutateFields("deleteBookingContactsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertBookingContactsObjectInput, params InsertParams) (schema.InsertBookingContactsResponse, error) {
	var out schema.InsertBookingContactsResponse
	args := map[string]any{
		"objects": graphql.Var(objects, "[InsertBookingContactsObjectInput!]"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "BookingContactsBoolExp")
	}
	res := <-h.gql.MutateFields("insertBookingContacts", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateBookingContactsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateBookingContactsByIdResponse, error) {
	var out schema.UpdateBookingContactsByIdResponse
	args := map[string]any{
		"keyId":         graphql.Var(keyId, "String1"),
		"updateColumns": graphql.Var(updateColumns, "UpdateBookingContactsByIdUpdateColumnsInput"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "BookingContactsBoolExp")
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "BookingContactsBoolExp")
	}
	res := <-h.gql.MutateFields("updateBookingContactsById", &out, args)
	return out, res.Error
}
