// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/organisationql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs OrganisationResource query operations.
type QueryHandler interface {
	// List runs the "organisationResource" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.OrganisationResource, error)
	// Find runs the "organisationResource" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.OrganisationResource, error)
	// Aggregate runs the "organisationResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.OrganisationResourceAggExp, error)
	// Get runs the "organisationResourceById" query.
	Get(ctx context.Context, id string) (*schemaql.OrganisationResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs OrganisationResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteOrganisationResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteOrganisationResourceByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteOrganisationResourceByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertOrganisationResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertOrganisationResourceResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertOrganisationResourceResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateOrganisationResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateOrganisationResourceByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateOrganisationResourceByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateOrganisationResourceByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs OrganisationResource subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "organisationResource" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "organisationResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "organisationResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.OrganisationResource] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertOrganisationResourceResponse, schemaql.UpdateOrganisationResourceByIdResponse, schemaql.DeleteOrganisationResourceByIdResponse] = (*mutationHandler)(nil)
