// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/organisationql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteOrganisationResourceByIdResponse, error) {
	var out schemaql.DeleteOrganisationResourceByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "OrganisationResourceBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deleteOrganisationResourceById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertOrganisationResourceResponse, error) {
	var out schemaql.InsertOrganisationResourceResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertOrganisationResourceObjectInput!]")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "OrganisationResourceBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertOrganisationResource", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateOrganisationResourceByIdResponse, error) {
	var out schemaql.UpdateOrganisationResourceByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "OrganisationResourceBoolExp")
	}
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "OrganisationResourceBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateOrganisationResourceByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updateOrganisationResourceById", &out, args)
	return out, res.Error
}
