// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for OrganisationResource. Build predicates like BillingEmail.Eq(v) and combine
// them with And/Or/Not.
var (
	BillingEmail = graphql.StringField{Col: "billingEmail"}
	CreateTime   = graphql.StringField{Col: "createTime"}
	DisplayName  = graphql.StringField{Col: "displayName"}
	Etag         = graphql.StringField{Col: "etag"}
	Id           = graphql.StringField{Col: "id"}
	MemberCount  = graphql.Int64Field{Col: "memberCount"}
	Name         = graphql.StringField{Col: "name"}
	Settings     = graphql.JSONField{Col: "settings"}
	Slug         = graphql.StringField{Col: "slug"}
	State        = graphql.StringField{Col: "state"}
	UpdateTime   = graphql.StringField{Col: "updateTime"}
)

// IdentityMembershipSummaries filters by the identityMembershipSummaries relation, taking a predicate from that resource.
func IdentityMembershipSummaries(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("identityMembershipSummaries", p)
}

// OrganisationMembers filters by the organisationMembers relation, taking a predicate from that resource.
func OrganisationMembers(p graphql.Predicate) graphql.Predicate {
	return graphql.Relation("organisationMembers", p)
}

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
