// Code generated by generateql. DO NOT EDIT.

package prisma

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/prisma/migrations"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler aggregates query handlers for the prisma domain.
type QueryHandler struct {
	Migrations migrations.QueryHandler
}

// NewQuery wires every query handler in the domain.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler {
	return QueryHandler{
		Migrations: migrations.NewQuery(gql),
	}
}

// MutationHandler aggregates mutation handlers for the prisma domain.
type MutationHandler struct {
	Migrations migrations.MutationHandler
}

// NewMutation wires every mutation handler in the domain.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler {
	return MutationHandler{
		Migrations: migrations.NewMutation(gql),
	}
}

// SubscriptionHandler aggregates subscription handlers for the prisma domain.
type SubscriptionHandler struct {
	Migrations migrations.SubscriptionHandler
}

// NewSubscription wires every subscription handler in the domain.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return SubscriptionHandler{
		Migrations: migrations.NewSubscription(gql),
	}
}
