// Code generated by generateql. DO NOT EDIT.

package usersql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs IdentityUsers query operations.
type QueryHandler interface {
	// List runs the "identityUsers" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.IdentityUsers, error)
	// Find runs the "identityUsers" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.IdentityUsers, error)
	// Aggregate runs the "identityUsersAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.IdentityUsersAggExp, error)
	// Get runs the "identityUsersById" query.
	Get(ctx context.Context, id string) (*schemaql.IdentityUsers, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs IdentityUsers mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteIdentityUsersById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteIdentityUsersByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteIdentityUsersByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertIdentityUsers" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertIdentityUsersResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertIdentityUsersResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateIdentityUsersById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateIdentityUsersByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateIdentityUsersByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateIdentityUsersByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs IdentityUsers subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "identityUsers" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "identityUsersAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "identityUsersById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.IdentityUsers] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertIdentityUsersResponse, schemaql.UpdateIdentityUsersByIdResponse, schemaql.DeleteIdentityUsersByIdResponse] = (*mutationHandler)(nil)
