// Code generated by generateql. DO NOT EDIT.

package usersql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnFind(ctx context.Context, req ...*OnFindRequest) (*runtime.Subscription, error) {
	var out []schemaql.IdentityUsers
	var r OnFindRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		args["limit"] = graphql.VarPtr(r.limit, "Int")
	}
	if !graphql.IsOmitted(r.offset) {
		args["offset"] = graphql.VarPtr(r.offset, "Int")
	}
	if !graphql.IsOmitted(r.orderBy) {
		args["order_by"] = graphql.VarPtr(r.orderBy, "[IdentityUsersOrderByExp!]")
	}
	if !graphql.IsOmitted(r.where) {
		args["where"] = graphql.VarPtr(r.where, "IdentityUsersBoolExp")
	}
	return h.gql.SubscribeFields("identityUsers", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error) {
	var out *schemaql.IdentityUsersAggExp
	var r OnAggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		filterInput["limit"] = r.limit
	}
	if !graphql.IsOmitted(r.offset) {
		filterInput["offset"] = r.offset
	}
	if !graphql.IsOmitted(r.orderBy) {
		filterInput["order_by"] = r.orderBy
	}
	if !graphql.IsOmitted(r.where) {
		filterInput["where"] = r.where
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "IdentityUsersFilterInput")
	}
	return h.gql.SubscribeFields("identityUsersAggregate", &out, args)
}

func (h *subscriptionHandler) OnGet(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schemaql.IdentityUsers
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	return h.gql.SubscribeFields("identityUsersById", &out, args)
}
