// Code generated by generateql. DO NOT EDIT.

package taxesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ResourceTaxes query operations.
type QueryHandler interface {
	// List runs the "resourceTaxes" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.ResourceTaxes, error)
	// Find runs the "resourceTaxes" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.ResourceTaxes, error)
	// Aggregate runs the "resourceTaxesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ResourceTaxesAggExp, error)
	// Get runs the "resourceTaxesById" query.
	Get(ctx context.Context, id string) (*schemaql.ResourceTaxes, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ResourceTaxes mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteResourceTaxesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceTaxesByIdResponse, error)
	// Create runs the "insertResourceTaxes" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceTaxesResponse, error)
	// Update runs the "updateResourceTaxesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceTaxesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ResourceTaxes subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "resourceTaxes" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "resourceTaxesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "resourceTaxesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
