// Code generated by generateql. DO NOT EDIT.

package taxesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceTaxesByIdResponse, error) {
	var out schemaql.DeleteResourceTaxesByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ResourceTaxesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deleteResourceTaxesById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceTaxesResponse, error) {
	var out schemaql.InsertResourceTaxesResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertResourceTaxesObjectInput!]")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ResourceTaxesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertResourceTaxes", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceTaxesByIdResponse, error) {
	var out schemaql.UpdateResourceTaxesByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ResourceTaxesBoolExp")
	}
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ResourceTaxesBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateResourceTaxesByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updateResourceTaxesById", &out, args)
	return out, res.Error
}
