// Code generated by generateql. DO NOT EDIT.

package redemptionsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/promocodeql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PromocodeRedemptions query operations.
type QueryHandler interface {
	// List runs the "promocodeRedemptions" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.PromocodeRedemptions, error)
	// Find runs the "promocodeRedemptions" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.PromocodeRedemptions, error)
	// Aggregate runs the "promocodeRedemptionsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.PromocodeRedemptionsAggExp, error)
	// Get runs the "promocodeRedemptionsById" query.
	Get(ctx context.Context, id string) (*schemaql.PromocodeRedemptions, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PromocodeRedemptions mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePromocodeRedemptionsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeletePromocodeRedemptionsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeletePromocodeRedemptionsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPromocodeRedemptions" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertPromocodeRedemptionsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertPromocodeRedemptionsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePromocodeRedemptionsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdatePromocodeRedemptionsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdatePromocodeRedemptionsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdatePromocodeRedemptionsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PromocodeRedemptions subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "promocodeRedemptions" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "promocodeRedemptionsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "promocodeRedemptionsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.PromocodeRedemptions] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertPromocodeRedemptionsResponse, schemaql.UpdatePromocodeRedemptionsByIdResponse, schemaql.DeletePromocodeRedemptionsByIdResponse] = (*mutationHandler)(nil)
