// Code generated by generate-ql. DO NOT EDIT.

package moneys

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteBookingMoneysByIdResponse, error) {
	var q struct {
		DeleteBookingMoneysById schema.DeleteBookingMoneysByIdResponse `graphql:"deleteBookingMoneysById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteBookingMoneysById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertBookingMoneysObjectInput, params InsertParams) (schema.InsertBookingMoneysResponse, error) {
	var q struct {
		InsertBookingMoneys schema.InsertBookingMoneysResponse `graphql:"insertBookingMoneys(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertBookingMoneys, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateBookingMoneysByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateBookingMoneysByIdResponse, error) {
	var q struct {
		UpdateBookingMoneysById schema.UpdateBookingMoneysByIdResponse `graphql:"updateBookingMoneysById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateBookingMoneysById, res.Error
}
