// Code generated by generateql. DO NOT EDIT.

package moneysql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/commonql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs CommonMoneys query operations.
type QueryHandler interface {
	// List runs the "commonMoneys" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.CommonMoneys, error)
	// Find runs the "commonMoneys" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.CommonMoneys, error)
	// Aggregate runs the "commonMoneysAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.CommonMoneysAggExp, error)
	// Get runs the "commonMoneysById" query.
	Get(ctx context.Context, id string) (*schemaql.CommonMoneys, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs CommonMoneys mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteCommonMoneysById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteCommonMoneysByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteCommonMoneysByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertCommonMoneys" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertCommonMoneysResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertCommonMoneysResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateCommonMoneysById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateCommonMoneysByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateCommonMoneysByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateCommonMoneysByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs CommonMoneys subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "commonMoneys" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "commonMoneysAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "commonMoneysById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.CommonMoneys] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertCommonMoneysResponse, schemaql.UpdateCommonMoneysByIdResponse, schemaql.DeleteCommonMoneysByIdResponse] = (*mutationHandler)(nil)
