// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeleteIdentityMembershipSummariesByIdResponse is the DeleteIdentityMembershipSummariesByIdResponse model.
type DeleteIdentityMembershipSummariesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id             string  `graphql:"id"`
		OrgDisplayName *string `graphql:"orgDisplayName"`
		Organisation   *string `graphql:"organisation"`
		Role           *string `graphql:"role"`
		UserId         string  `graphql:"userId"`
	} `graphql:"returning"`
}
