// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteIdentityGuestsByBookingIdResponse is the DeleteIdentityGuestsByBookingIdResponse model.
type DeleteIdentityGuestsByBookingIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id string `graphql:"id"`
	} `graphql:"returning"`
}

// DeleteIdentityGuestsByIdResponse is the DeleteIdentityGuestsByIdResponse model.
type DeleteIdentityGuestsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AgeGroup           *string `graphql:"ageGroup"`
		BirthDate          *string `graphql:"birthDate"`
		BookingId          string  `graphql:"bookingId"`
		DisplayName        string  `graphql:"displayName"`
		Email              *string `graphql:"email"`
		ForeignerId        *string `graphql:"foreignerId"`
		Gender             *string `graphql:"gender"`
		Id                 string  `graphql:"id"`
		IdDocumentId       *string `graphql:"idDocumentId"`
		LocalAddressId     *string `graphql:"localAddressId"`
		Nationality        *string `graphql:"nationality"`
		PermanentAddressId *string `graphql:"permanentAddressId"`
		PhoneNumber        *string `graphql:"phoneNumber"`
		PreferencesId      *string `graphql:"preferencesId"`
		Primary            *bool   `graphql:"primary"`
	} `graphql:"returning"`
}

// IdentityGuests is the IdentityGuests model.
type IdentityGuests struct {
	AgeGroup           *string `graphql:"ageGroup"`
	BirthDate          *string `graphql:"birthDate"`
	BookingId          string  `graphql:"bookingId"`
	DisplayName        string  `graphql:"displayName"`
	Email              *string `graphql:"email"`
	ForeignerId        *string `graphql:"foreignerId"`
	Gender             *string `graphql:"gender"`
	Id                 string  `graphql:"id"`
	IdDocumentId       *string `graphql:"idDocumentId"`
	LocalAddressId     *string `graphql:"localAddressId"`
	Nationality        *string `graphql:"nationality"`
	PermanentAddressId *string `graphql:"permanentAddressId"`
	PhoneNumber        *string `graphql:"phoneNumber"`
	PreferencesId      *string `graphql:"preferencesId"`
	Primary            *bool   `graphql:"primary"`
}

// IdentityGuestsAggExp is the IdentityGuestsAggExp model.
type IdentityGuestsAggExp struct {
	Count    graphql.Int64 `graphql:"_count"`
	AgeGroup struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"ageGroup"`
	BirthDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"birthDate"`
	BookingId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"bookingId"`
	DisplayName struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"displayName"`
	Email struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"email"`
	ForeignerId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"foreignerId"`
	Gender struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"gender"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	IdDocumentId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"idDocumentId"`
	LocalAddressId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"localAddressId"`
	Nationality struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"nationality"`
	PermanentAddressId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"permanentAddressId"`
	PhoneNumber struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"phoneNumber"`
	PreferencesId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"preferencesId"`
	Primary struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		BoolAnd       *bool         `graphql:"bool_and"`
		BoolOr        *bool         `graphql:"bool_or"`
		Every         *bool         `graphql:"every"`
	} `graphql:"primary"`
}

// InsertIdentityGuestsResponse is the InsertIdentityGuestsResponse model.
type InsertIdentityGuestsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AgeGroup           *string `graphql:"ageGroup"`
		BirthDate          *string `graphql:"birthDate"`
		BookingId          string  `graphql:"bookingId"`
		DisplayName        string  `graphql:"displayName"`
		Email              *string `graphql:"email"`
		ForeignerId        *string `graphql:"foreignerId"`
		Gender             *string `graphql:"gender"`
		Id                 string  `graphql:"id"`
		IdDocumentId       *string `graphql:"idDocumentId"`
		LocalAddressId     *string `graphql:"localAddressId"`
		Nationality        *string `graphql:"nationality"`
		PermanentAddressId *string `graphql:"permanentAddressId"`
		PhoneNumber        *string `graphql:"phoneNumber"`
		PreferencesId      *string `graphql:"preferencesId"`
		Primary            *bool   `graphql:"primary"`
	} `graphql:"returning"`
}

// UpdateIdentityGuestsByIdResponse is the UpdateIdentityGuestsByIdResponse model.
type UpdateIdentityGuestsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AgeGroup           *string `graphql:"ageGroup"`
		BirthDate          *string `graphql:"birthDate"`
		BookingId          string  `graphql:"bookingId"`
		DisplayName        string  `graphql:"displayName"`
		Email              *string `graphql:"email"`
		ForeignerId        *string `graphql:"foreignerId"`
		Gender             *string `graphql:"gender"`
		Id                 string  `graphql:"id"`
		IdDocumentId       *string `graphql:"idDocumentId"`
		LocalAddressId     *string `graphql:"localAddressId"`
		Nationality        *string `graphql:"nationality"`
		PermanentAddressId *string `graphql:"permanentAddressId"`
		PhoneNumber        *string `graphql:"phoneNumber"`
		PreferencesId      *string `graphql:"preferencesId"`
		Primary            *bool   `graphql:"primary"`
	} `graphql:"returning"`
}
