// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteIdentityForeignerDetailsByIdResponse is the DeleteIdentityForeignerDetailsByIdResponse model.
type DeleteIdentityForeignerDetailsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		ArrivalDate     *string `graphql:"arrivalDate"`
		EntryPort       *string `graphql:"entryPort"`
		Id              string  `graphql:"id"`
		NextDestination *string `graphql:"nextDestination"`
		Origin          *string `graphql:"origin"`
		VisaExpiryDate  *string `graphql:"visaExpiryDate"`
		VisaIssueDate   *string `graphql:"visaIssueDate"`
		VisaIssuePlace  *string `graphql:"visaIssuePlace"`
		VisaNumber      *string `graphql:"visaNumber"`
		VisaType        *string `graphql:"visaType"`
		VisitPurpose    *string `graphql:"visitPurpose"`
	} `graphql:"returning"`
}

// IdentityForeignerDetails is the IdentityForeignerDetails model.
type IdentityForeignerDetails struct {
	ArrivalDate     *string `graphql:"arrivalDate"`
	EntryPort       *string `graphql:"entryPort"`
	Id              string  `graphql:"id"`
	NextDestination *string `graphql:"nextDestination"`
	Origin          *string `graphql:"origin"`
	VisaExpiryDate  *string `graphql:"visaExpiryDate"`
	VisaIssueDate   *string `graphql:"visaIssueDate"`
	VisaIssuePlace  *string `graphql:"visaIssuePlace"`
	VisaNumber      *string `graphql:"visaNumber"`
	VisaType        *string `graphql:"visaType"`
	VisitPurpose    *string `graphql:"visitPurpose"`
}

// IdentityForeignerDetailsAggExp is the IdentityForeignerDetailsAggExp model.
type IdentityForeignerDetailsAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	ArrivalDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"arrivalDate"`
	EntryPort struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"entryPort"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	NextDestination struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"nextDestination"`
	Origin struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"origin"`
	VisaExpiryDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visaExpiryDate"`
	VisaIssueDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visaIssueDate"`
	VisaIssuePlace struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visaIssuePlace"`
	VisaNumber struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visaNumber"`
	VisaType struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visaType"`
	VisitPurpose struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"visitPurpose"`
}

// InsertIdentityForeignerDetailsResponse is the InsertIdentityForeignerDetailsResponse model.
type InsertIdentityForeignerDetailsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		ArrivalDate     *string `graphql:"arrivalDate"`
		EntryPort       *string `graphql:"entryPort"`
		Id              string  `graphql:"id"`
		NextDestination *string `graphql:"nextDestination"`
		Origin          *string `graphql:"origin"`
		VisaExpiryDate  *string `graphql:"visaExpiryDate"`
		VisaIssueDate   *string `graphql:"visaIssueDate"`
		VisaIssuePlace  *string `graphql:"visaIssuePlace"`
		VisaNumber      *string `graphql:"visaNumber"`
		VisaType        *string `graphql:"visaType"`
		VisitPurpose    *string `graphql:"visitPurpose"`
	} `graphql:"returning"`
}

// UpdateIdentityForeignerDetailsByIdResponse is the UpdateIdentityForeignerDetailsByIdResponse model.
type UpdateIdentityForeignerDetailsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		ArrivalDate     *string `graphql:"arrivalDate"`
		EntryPort       *string `graphql:"entryPort"`
		Id              string  `graphql:"id"`
		NextDestination *string `graphql:"nextDestination"`
		Origin          *string `graphql:"origin"`
		VisaExpiryDate  *string `graphql:"visaExpiryDate"`
		VisaIssueDate   *string `graphql:"visaIssueDate"`
		VisaIssuePlace  *string `graphql:"visaIssuePlace"`
		VisaNumber      *string `graphql:"visaNumber"`
		VisaType        *string `graphql:"visaType"`
		VisitPurpose    *string `graphql:"visitPurpose"`
	} `graphql:"returning"`
}
