// Code generated by generateql. DO NOT EDIT.

package exceptions

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.ScheduleExceptions, error) {
	var out []schema.ScheduleExceptions
	args := map[string]any{}
	if params.Limit.IsPresent() {
		args["limit"] = graphql.VarPtr(params.Limit.Value(), "Int")
	}
	if params.Offset.IsPresent() {
		args["offset"] = graphql.VarPtr(params.Offset.Value(), "Int")
	}
	if !param.IsOmitted(params.OrderBy) {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[ScheduleExceptionsOrderByExp!]")
	}
	if !param.IsOmitted(params.Where) {
		args["where"] = graphql.VarPtr(params.Where, "ScheduleExceptionsBoolExp")
	}
	res := <-h.gql.QueryFields("scheduleExceptions", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.ScheduleExceptionsAggExp, error) {
	var out *schema.ScheduleExceptionsAggExp
	args := map[string]any{}
	if !param.IsOmitted(params.FilterInput) {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "ScheduleExceptionsFilterInput")
	}
	res := <-h.gql.QueryFields("scheduleExceptionsAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.ScheduleExceptions, error) {
	var out *schema.ScheduleExceptions
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	res := <-h.gql.QueryFields("scheduleExceptionsById", &out, args)
	return out, res.Error
}
