// Code generated by generateql. DO NOT EDIT.

package guestpreferencesql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteIdentityGuestPreferencesByIdResponse = schemaql.DeleteIdentityGuestPreferencesByIdResponse
type IdentityGuestPreferences = schemaql.IdentityGuestPreferences
type IdentityGuestPreferencesAggExp = schemaql.IdentityGuestPreferencesAggExp
type InsertIdentityGuestPreferencesResponse = schemaql.InsertIdentityGuestPreferencesResponse
type UpdateIdentityGuestPreferencesByIdResponse = schemaql.UpdateIdentityGuestPreferencesByIdResponse
