// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ScheduleResource query operations.
type QueryHandler interface {
	// Find runs the "scheduleResource" query.
	Find(ctx context.Context, obj CreateInput, req ...*FindRequest) ([]schemaql.ScheduleResource, error)
	// Aggregate runs the "scheduleResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ScheduleResourceAggExp, error)
	// Get runs the "scheduleResourceById" query.
	Get(ctx context.Context, id string) (*schemaql.ScheduleResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ScheduleResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteScheduleResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteScheduleResourceByIdResponse, error)
	// Create runs the "insertScheduleResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertScheduleResourceResponse, error)
	// Update runs the "updateScheduleResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateScheduleResourceByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ScheduleResource subscription operations.
type SubscriptionHandler interface {
	// OnFind runs the "scheduleResource" subscription.
	OnFind(ctx context.Context, obj CreateInput, req ...*OnFindRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "scheduleResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "scheduleResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
