// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleResourceByIdResponse = schemaql.DeleteScheduleResourceByIdResponse
type InsertScheduleResourceResponse = schemaql.InsertScheduleResourceResponse
type ScheduleResource = schemaql.ScheduleResource
type ScheduleResourceAggExp = schemaql.ScheduleResourceAggExp
type UpdateScheduleResourceByIdResponse = schemaql.UpdateScheduleResourceByIdResponse
