// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/scheduleql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnFind(ctx context.Context, obj CreateInput, req ...*OnFindRequest) (*runtime.Subscription, error) {
	var out []schemaql.ScheduleResource
	var r OnFindRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		args["limit"] = graphql.VarPtr(r.limit, "Int")
	}
	if !graphql.IsOmitted(r.offset) {
		args["offset"] = graphql.VarPtr(r.offset, "Int")
	}
	args["order_by"] = graphql.Var([]CreateInput{obj}, "[ScheduleResourceOrderByExp!]")
	if !graphql.IsOmitted(r.where) {
		args["where"] = graphql.VarPtr(r.where, "ScheduleResourceBoolExp")
	}
	return h.gql.SubscribeFields("scheduleResource", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error) {
	var out *schemaql.ScheduleResourceAggExp
	var r OnAggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		filterInput["limit"] = r.limit
	}
	if !graphql.IsOmitted(r.offset) {
		filterInput["offset"] = r.offset
	}
	if !graphql.IsOmitted(r.where) {
		filterInput["where"] = r.where
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "ScheduleResourceFilterInput")
	}
	return h.gql.SubscribeFields("scheduleResourceAggregate", &out, args)
}

func (h *subscriptionHandler) OnGet(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schemaql.ScheduleResource
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	return h.gql.SubscribeFields("scheduleResourceById", &out, args)
}
