// Code generated by generateql. DO NOT EDIT.

package guestsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteIdentityGuestsByIdResponse, error) {
	var out schemaql.DeleteIdentityGuestsByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "IdentityGuestsBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deleteIdentityGuestsById", &out, args)
	return out, res.Error
}

// DeleteOp returns Delete as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) DeleteOp(keyId string, result *schemaql.DeleteIdentityGuestsByIdResponse, req ...*DeleteRequest) runtime.BatchOp {
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "IdentityGuestsBoolExp")
	}
	return runtime.BatchOp{Field: "deleteIdentityGuestsById", Args: args, Result: result}
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertIdentityGuestsResponse, error) {
	var out schemaql.InsertIdentityGuestsResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertIdentityGuestsObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "IdentityGuestsBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertIdentityGuests", &out, args)
	return out, res.Error
}

// CreateOp returns Create as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) CreateOp(obj CreateInput, result *schemaql.InsertIdentityGuestsResponse, req ...*CreateRequest) runtime.BatchOp {
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertIdentityGuestsObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "IdentityGuestsBoolExp")
	}
	return runtime.BatchOp{Field: "insertIdentityGuests", Args: args, Result: result}
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateIdentityGuestsByIdResponse, error) {
	var out schemaql.UpdateIdentityGuestsByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "IdentityGuestsBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "IdentityGuestsBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateIdentityGuestsByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updateIdentityGuestsById", &out, args)
	return out, res.Error
}

// UpdateIfMatch runs Update guarded by match, an optimistic-concurrency precondition
// (e.g. Etag.Eq(prev)). It returns graphql.ErrConflict when no row matched the precondition.
func (h *mutationHandler) UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateIdentityGuestsByIdResponse, error) {
	resp, err := h.Update(ctx, keyId, patch, Update().PreCheck(match))
	if err != nil {
		return resp, err
	}
	if resp.AffectedRows == 0 {
		return resp, graphql.ErrConflict
	}
	return resp, nil
}

// UpdateOp returns Update as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateIdentityGuestsByIdResponse, req ...*UpdateRequest) runtime.BatchOp {
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "IdentityGuestsBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "IdentityGuestsBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateIdentityGuestsByIdUpdateColumnsInput")
	return runtime.BatchOp{Field: "updateIdentityGuestsById", Args: args, Result: result}
}

func (h *mutationHandler) DeleteByBookingId(ctx context.Context, bookingId string) (schemaql.DeleteIdentityGuestsByBookingIdResponse, error) {
	var out schemaql.DeleteIdentityGuestsByBookingIdResponse
	args := map[string]any{}
	args["bookingId"] = graphql.Var(bookingId, "String1")
	res := <-h.gql.MutateFields(ctx, "deleteIdentityGuestsByBookingId", &out, args)
	return out, res.Error
}

// DeleteByBookingIdOp returns DeleteByBookingId as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) DeleteByBookingIdOp(bookingId string, result *schemaql.DeleteIdentityGuestsByBookingIdResponse) runtime.BatchOp {
	args := map[string]any{}
	args["bookingId"] = graphql.Var(bookingId, "String1")
	return runtime.BatchOp{Field: "deleteIdentityGuestsByBookingId", Args: args, Result: result}
}
