// Code generated by generateql. DO NOT EDIT.

package pricecomponents

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.BookingPriceComponents, error) {
	var out []schema.BookingPriceComponents
	args := map[string]any{}
	if params.Limit.IsPresent() {
		args["limit"] = graphql.VarPtr(params.Limit.Value(), "Int")
	}
	if params.Offset.IsPresent() {
		args["offset"] = graphql.VarPtr(params.Offset.Value(), "Int")
	}
	if !param.IsOmitted(params.OrderBy) {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[BookingPriceComponentsOrderByExp!]")
	}
	if !param.IsOmitted(params.Where) {
		args["where"] = graphql.VarPtr(params.Where, "BookingPriceComponentsBoolExp")
	}
	res := <-h.gql.QueryFields("bookingPriceComponents", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.BookingPriceComponentsAggExp, error) {
	var out *schema.BookingPriceComponentsAggExp
	args := map[string]any{}
	if !param.IsOmitted(params.FilterInput) {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "BookingPriceComponentsFilterInput")
	}
	res := <-h.gql.QueryFields("bookingPriceComponentsAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.BookingPriceComponents, error) {
	var out *schema.BookingPriceComponents
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	res := <-h.gql.QueryFields("bookingPriceComponentsById", &out, args)
	return out, res.Error
}
