// Code generated by generate-ql. DO NOT EDIT.

package pricecomponents

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.BookingPriceComponents, error) {
	var q struct {
		BookingPriceComponents []schema.BookingPriceComponents `graphql:"bookingPriceComponents(limit: $limit, offset: $offset, order_by: $order_by, where: $where)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"limit":    params.Limit,
		"offset":   params.Offset,
		"order_by": params.OrderBy,
		"where":    params.Where,
	})
	return q.BookingPriceComponents, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.BookingPriceComponentsAggExp, error) {
	var q struct {
		BookingPriceComponentsAggregate *schema.BookingPriceComponentsAggExp `graphql:"bookingPriceComponentsAggregate(filter_input: $filter_input)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"filter_input": params.FilterInput,
	})
	return q.BookingPriceComponentsAggregate, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.BookingPriceComponents, error) {
	var q struct {
		BookingPriceComponentsById *schema.BookingPriceComponents `graphql:"bookingPriceComponentsById(id: $id)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"id": id,
	})
	return q.BookingPriceComponentsById, res.Error
}
