// Code generated by generateql. DO NOT EDIT.

package entityql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceEntityByIdResponse, error) {
	var out schemaql.DeleteResourceEntityByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ResourceEntityBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deleteResourceEntityById", &out, args)
	return out, res.Error
}

// DeleteOp returns Delete as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) DeleteOp(keyId string, result *schemaql.DeleteResourceEntityByIdResponse, req ...*DeleteRequest) runtime.BatchOp {
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ResourceEntityBoolExp")
	}
	return runtime.BatchOp{Field: "deleteResourceEntityById", Args: args, Result: result}
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceEntityResponse, error) {
	var out schemaql.InsertResourceEntityResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertResourceEntityObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ResourceEntityBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertResourceEntity", &out, args)
	return out, res.Error
}

// CreateOp returns Create as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) CreateOp(obj CreateInput, result *schemaql.InsertResourceEntityResponse, req ...*CreateRequest) runtime.BatchOp {
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertResourceEntityObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ResourceEntityBoolExp")
	}
	return runtime.BatchOp{Field: "insertResourceEntity", Args: args, Result: result}
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceEntityByIdResponse, error) {
	var out schemaql.UpdateResourceEntityByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ResourceEntityBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ResourceEntityBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateResourceEntityByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updateResourceEntityById", &out, args)
	return out, res.Error
}

// UpdateIfMatch runs Update guarded by match, an optimistic-concurrency precondition
// (e.g. Etag.Eq(prev)). It returns graphql.ErrConflict when no row matched the precondition.
func (h *mutationHandler) UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateResourceEntityByIdResponse, error) {
	resp, err := h.Update(ctx, keyId, patch, Update().PreCheck(match))
	if err != nil {
		return resp, err
	}
	if resp.AffectedRows == 0 {
		return resp, graphql.ErrConflict
	}
	return resp, nil
}

// UpdateOp returns Update as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateResourceEntityByIdResponse, req ...*UpdateRequest) runtime.BatchOp {
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "ResourceEntityBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "ResourceEntityBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateResourceEntityByIdUpdateColumnsInput")
	return runtime.BatchOp{Field: "updateResourceEntityById", Args: args, Result: result}
}
