// Code generated by generateql. DO NOT EDIT.

package entityql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceEntityByIdResponse, error) {
	var out schemaql.DeleteResourceEntityByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ResourceEntityBoolExp")
	}
	res := <-h.gql.MutateFields("deleteResourceEntityById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceEntityResponse, error) {
	var out schemaql.InsertResourceEntityResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertResourceEntityObjectInput!]")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ResourceEntityBoolExp")
	}
	res := <-h.gql.MutateFields("insertResourceEntity", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceEntityByIdResponse, error) {
	var out schemaql.UpdateResourceEntityByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.postCheck) {
		args["postCheck"] = graphql.VarPtr(r.postCheck, "ResourceEntityBoolExp")
	}
	if !graphql.IsOmitted(r.preCheck) {
		args["preCheck"] = graphql.VarPtr(r.preCheck, "ResourceEntityBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdateResourceEntityByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields("updateResourceEntityById", &out, args)
	return out, res.Error
}
