// Code generated by generateql. DO NOT EDIT.

package contactsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for SharedContacts. Build predicates like DisplayName.Eq(v) and combine
// them with And/Or/Not.
var (
	DisplayName = graphql.StringField{Col: "displayName"}
	Email       = graphql.StringField{Col: "email"}
	Id          = graphql.StringField{Col: "id"}
	PhoneNumber = graphql.StringField{Col: "phoneNumber"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
