// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeleteScheduleCancellationPoliciesByIdResponse is the DeleteScheduleCancellationPoliciesByIdResponse model.
type DeleteScheduleCancellationPoliciesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id string `graphql:"id"`
	} `graphql:"returning"`
}
