// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteScheduleBufferSettingsByIdResponse is the DeleteScheduleBufferSettingsByIdResponse model.
type DeleteScheduleBufferSettingsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndDelta   *string `graphql:"endDelta"`
		Gap        *string `graphql:"gap"`
		Id         string  `graphql:"id"`
		MaxAdvance *string `graphql:"maxAdvance"`
		MinNotice  *string `graphql:"minNotice"`
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}

// InsertScheduleBufferSettingsResponse is the InsertScheduleBufferSettingsResponse model.
type InsertScheduleBufferSettingsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndDelta   *string `graphql:"endDelta"`
		Gap        *string `graphql:"gap"`
		Id         string  `graphql:"id"`
		MaxAdvance *string `graphql:"maxAdvance"`
		MinNotice  *string `graphql:"minNotice"`
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}

// ScheduleBufferSettings is the ScheduleBufferSettings model.
type ScheduleBufferSettings struct {
	EndDelta   *string `graphql:"endDelta"`
	Gap        *string `graphql:"gap"`
	Id         string  `graphql:"id"`
	MaxAdvance *string `graphql:"maxAdvance"`
	MinNotice  *string `graphql:"minNotice"`
	StartDelta *string `graphql:"startDelta"`
}

// ScheduleBufferSettingsAggExp is the ScheduleBufferSettingsAggExp model.
type ScheduleBufferSettingsAggExp struct {
	Count    graphql.Int64 `graphql:"_count"`
	EndDelta struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"endDelta"`
	Gap struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"gap"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	MaxAdvance struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"maxAdvance"`
	MinNotice struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"minNotice"`
	StartDelta struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"startDelta"`
}

// UpdateScheduleBufferSettingsByIdResponse is the UpdateScheduleBufferSettingsByIdResponse model.
type UpdateScheduleBufferSettingsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndDelta   *string `graphql:"endDelta"`
		Gap        *string `graphql:"gap"`
		Id         string  `graphql:"id"`
		MaxAdvance *string `graphql:"maxAdvance"`
		MinNotice  *string `graphql:"minNotice"`
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}
