// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// ScheduleStayConstraintsAggExp is the ScheduleStayConstraintsAggExp model.
type ScheduleStayConstraintsAggExp struct {
	Count          graphql.Int64 `graphql:"_count"`
	AdvanceMaxDays struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"advanceMaxDays"`
	AdvanceMinDays struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"advanceMinDays"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	MaxNights struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"maxNights"`
	MinNights struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"minNights"`
}
