// Code generated by generateql. DO NOT EDIT.

package schemaql

// UpdateScheduleCancellationPoliciesByIdResponse is the UpdateScheduleCancellationPoliciesByIdResponse model.
type UpdateScheduleCancellationPoliciesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id string `graphql:"id"`
	} `graphql:"returning"`
}
