// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePromocodeScopeApplicableUnitsByIdResponse is the DeletePromocodeScopeApplicableUnitsByIdResponse model.
type DeletePromocodeScopeApplicableUnitsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id       string `graphql:"id"`
		ScopeId  string `graphql:"scopeId"`
		UnitId   string `graphql:"unitId"`
		UnitName string `graphql:"unitName"`
	} `graphql:"returning"`
}

// InsertPromocodeScopeApplicableUnitsResponse is the InsertPromocodeScopeApplicableUnitsResponse model.
type InsertPromocodeScopeApplicableUnitsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id       string `graphql:"id"`
		ScopeId  string `graphql:"scopeId"`
		UnitId   string `graphql:"unitId"`
		UnitName string `graphql:"unitName"`
	} `graphql:"returning"`
}

// PromocodeScopeApplicableUnits is the PromocodeScopeApplicableUnits model.
type PromocodeScopeApplicableUnits struct {
	Id       string `graphql:"id"`
	ScopeId  string `graphql:"scopeId"`
	UnitId   string `graphql:"unitId"`
	UnitName string `graphql:"unitName"`
}

// PromocodeScopeApplicableUnitsAggExp is the PromocodeScopeApplicableUnitsAggExp model.
type PromocodeScopeApplicableUnitsAggExp struct {
	Count graphql.Int64 `graphql:"_count"`
	Id    struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	ScopeId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"scopeId"`
	UnitId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"unitId"`
	UnitName struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"unitName"`
}

// UpdatePromocodeScopeApplicableUnitsByIdResponse is the UpdatePromocodeScopeApplicableUnitsByIdResponse model.
type UpdatePromocodeScopeApplicableUnitsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id       string `graphql:"id"`
		ScopeId  string `graphql:"scopeId"`
		UnitId   string `graphql:"unitId"`
		UnitName string `graphql:"unitName"`
	} `graphql:"returning"`
}
