// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePromocodeDiscountsByIdResponse is the DeletePromocodeDiscountsByIdResponse model.
type DeletePromocodeDiscountsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountCase  *string `graphql:"amountCase"`
		AmountOffId *string `graphql:"amountOffId"`
		Id          string  `graphql:"id"`
		PercentOff  *int32  `graphql:"percentOff"`
	} `graphql:"returning"`
}

// InsertPromocodeDiscountsResponse is the InsertPromocodeDiscountsResponse model.
type InsertPromocodeDiscountsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountCase  *string `graphql:"amountCase"`
		AmountOffId *string `graphql:"amountOffId"`
		Id          string  `graphql:"id"`
		PercentOff  *int32  `graphql:"percentOff"`
	} `graphql:"returning"`
}

// PromocodeDiscounts is the PromocodeDiscounts model.
type PromocodeDiscounts struct {
	AmountCase  *string `graphql:"amountCase"`
	AmountOffId *string `graphql:"amountOffId"`
	Id          string  `graphql:"id"`
	PercentOff  *int32  `graphql:"percentOff"`
}

// PromocodeDiscountsAggExp is the PromocodeDiscountsAggExp model.
type PromocodeDiscountsAggExp struct {
	Count      graphql.Int64 `graphql:"_count"`
	AmountCase struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"amountCase"`
	AmountOffId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"amountOffId"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	PercentOff struct {
		Count         graphql.Int64       `graphql:"_count"`
		CountDistinct graphql.Int64       `graphql:"_count_distinct"`
		Avg           *graphql.Bigdecimal `graphql:"avg"`
		BitAnd        *int32              `graphql:"bit_and"`
		BitOr         *int32              `graphql:"bit_or"`
		BitXor        *int32              `graphql:"bit_xor"`
		Max           *int32              `graphql:"max"`
		Min           *int32              `graphql:"min"`
		Stddev        *graphql.Bigdecimal `graphql:"stddev"`
		StddevPop     *graphql.Bigdecimal `graphql:"stddev_pop"`
		StddevSamp    *graphql.Bigdecimal `graphql:"stddev_samp"`
		Sum           *graphql.Int64      `graphql:"sum"`
		VarPop        *graphql.Bigdecimal `graphql:"var_pop"`
		VarSamp       *graphql.Bigdecimal `graphql:"var_samp"`
		Variance      *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"percentOff"`
}

// UpdatePromocodeDiscountsByIdResponse is the UpdatePromocodeDiscountsByIdResponse model.
type UpdatePromocodeDiscountsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountCase  *string `graphql:"amountCase"`
		AmountOffId *string `graphql:"amountOffId"`
		Id          string  `graphql:"id"`
		PercentOff  *int32  `graphql:"percentOff"`
	} `graphql:"returning"`
}
