// Code generated by generateql. DO NOT EDIT.

package unitapplicablepromocodesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for PropertyUnitApplicablePromoCodes. Build predicates like Id.Eq(v) and combine
// them with And/Or/Not.
var (
	Id          = graphql.StringField{Col: "id"}
	PromoCodeId = graphql.StringField{Col: "promoCodeId"}
	UnitId      = graphql.StringField{Col: "unitId"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
