// Code generated by generateql. DO NOT EDIT.

package contactsql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/bookingql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type BookingContacts = schemaql.BookingContacts
type BookingContactsAggExp = schemaql.BookingContactsAggExp
type DeleteBookingContactsByIdResponse = schemaql.DeleteBookingContactsByIdResponse
type InsertBookingContactsResponse = schemaql.InsertBookingContactsResponse
type UpdateBookingContactsByIdResponse = schemaql.UpdateBookingContactsByIdResponse
