// Code generated by generateql. DO NOT EDIT.

package foreignerdetailsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for IdentityForeignerDetails. Build predicates like ArrivalDate.Eq(v) and combine
// them with And/Or/Not.
var (
	ArrivalDate     = graphql.StringField{Col: "arrivalDate"}
	EntryPort       = graphql.StringField{Col: "entryPort"}
	Id              = graphql.StringField{Col: "id"}
	NextDestination = graphql.StringField{Col: "nextDestination"}
	Origin          = graphql.StringField{Col: "origin"}
	VisaExpiryDate  = graphql.StringField{Col: "visaExpiryDate"}
	VisaIssueDate   = graphql.StringField{Col: "visaIssueDate"}
	VisaIssuePlace  = graphql.StringField{Col: "visaIssuePlace"}
	VisaNumber      = graphql.StringField{Col: "visaNumber"}
	VisaType        = graphql.StringField{Col: "visaType"}
	VisitPurpose    = graphql.StringField{Col: "visitPurpose"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
