// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/promocodeql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PromocodeResource query operations.
type QueryHandler interface {
	// List runs the "promocodeResource" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.PromocodeResource, error)
	// Find runs the "promocodeResource" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.PromocodeResource, error)
	// Aggregate runs the "promocodeResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.PromocodeResourceAggExp, error)
	// Get runs the "promocodeResourceById" query.
	Get(ctx context.Context, id string) (*schemaql.PromocodeResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PromocodeResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePromocodeResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeletePromocodeResourceByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeletePromocodeResourceByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPromocodeResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertPromocodeResourceResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertPromocodeResourceResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePromocodeResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdatePromocodeResourceByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdatePromocodeResourceByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdatePromocodeResourceByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PromocodeResource subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "promocodeResource" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "promocodeResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "promocodeResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.PromocodeResource] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertPromocodeResourceResponse, schemaql.UpdatePromocodeResourceByIdResponse, schemaql.DeletePromocodeResourceByIdResponse] = (*mutationHandler)(nil)
