// Code generated by generateql. DO NOT EDIT.

package dateranges

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteScheduleDateRangesByIdResponse, error) {
	var out schema.DeleteScheduleDateRangesByIdResponse
	args := map[string]any{
		"keyId": graphql.Var(keyId, "String1"),
	}
	if !param.IsOmitted(params.PreCheck) {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ScheduleDateRangesBoolExp")
	}
	res := <-h.gql.MutateFields("deleteScheduleDateRangesById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertScheduleDateRangesObjectInput, params InsertParams) (schema.InsertScheduleDateRangesResponse, error) {
	var out schema.InsertScheduleDateRangesResponse
	args := map[string]any{
		"objects": graphql.Var(objects, "[InsertScheduleDateRangesObjectInput!]"),
	}
	if !param.IsOmitted(params.PostCheck) {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ScheduleDateRangesBoolExp")
	}
	res := <-h.gql.MutateFields("insertScheduleDateRanges", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateScheduleDateRangesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateScheduleDateRangesByIdResponse, error) {
	var out schema.UpdateScheduleDateRangesByIdResponse
	args := map[string]any{
		"keyId":         graphql.Var(keyId, "String1"),
		"updateColumns": graphql.Var(updateColumns, "UpdateScheduleDateRangesByIdUpdateColumnsInput"),
	}
	if !param.IsOmitted(params.PostCheck) {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ScheduleDateRangesBoolExp")
	}
	if !param.IsOmitted(params.PreCheck) {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ScheduleDateRangesBoolExp")
	}
	res := <-h.gql.MutateFields("updateScheduleDateRangesById", &out, args)
	return out, res.Error
}
