// Code generated by generate-ql. DO NOT EDIT.

package dateranges

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteScheduleDateRangesByIdResponse, error) {
	var q struct {
		DeleteScheduleDateRangesById schema.DeleteScheduleDateRangesByIdResponse `graphql:"deleteScheduleDateRangesById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteScheduleDateRangesById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertScheduleDateRangesObjectInput, params InsertParams) (schema.InsertScheduleDateRangesResponse, error) {
	var q struct {
		InsertScheduleDateRanges schema.InsertScheduleDateRangesResponse `graphql:"insertScheduleDateRanges(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertScheduleDateRanges, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateScheduleDateRangesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateScheduleDateRangesByIdResponse, error) {
	var q struct {
		UpdateScheduleDateRangesById schema.UpdateScheduleDateRangesByIdResponse `graphql:"updateScheduleDateRangesById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateScheduleDateRangesById, res.Error
}
