// Code generated by generateql. DO NOT EDIT.

package feesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs ResourceFees query operations.
type QueryHandler interface {
	// List runs the "resourceFees" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.ResourceFees, error)
	// Find runs the "resourceFees" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.ResourceFees, error)
	// Aggregate runs the "resourceFeesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ResourceFeesAggExp, error)
	// Get runs the "resourceFeesById" query.
	Get(ctx context.Context, id string) (*schemaql.ResourceFees, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs ResourceFees mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteResourceFeesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteResourceFeesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteResourceFeesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertResourceFees" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertResourceFeesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertResourceFeesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateResourceFeesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateResourceFeesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateResourceFeesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateResourceFeesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs ResourceFees subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "resourceFees" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "resourceFeesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "resourceFeesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.ResourceFees] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertResourceFeesResponse, schemaql.UpdateResourceFeesByIdResponse, schemaql.DeleteResourceFeesByIdResponse] = (*mutationHandler)(nil)
