// Code generated by generateql. DO NOT EDIT.

package feesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) Find(ctx context.Context, obj CreateInput, req ...*FindRequest) ([]schemaql.ResourceFees, error) {
	var out []schemaql.ResourceFees
	var r FindRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		args["limit"] = graphql.VarPtr(r.limit, "Int")
	}
	if !graphql.IsOmitted(r.offset) {
		args["offset"] = graphql.VarPtr(r.offset, "Int")
	}
	args["order_by"] = graphql.Var([]CreateInput{obj}, "[ResourceFeesOrderByExp!]")
	if !graphql.IsOmitted(r.where) {
		args["where"] = graphql.VarPtr(r.where, "ResourceFeesBoolExp")
	}
	res := <-h.gql.QueryFields("resourceFees", &out, args)
	return out, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.ResourceFeesAggExp, error) {
	var out *schemaql.ResourceFeesAggExp
	var r AggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.limit) {
		filterInput["limit"] = r.limit
	}
	if !graphql.IsOmitted(r.offset) {
		filterInput["offset"] = r.offset
	}
	if !graphql.IsOmitted(r.where) {
		filterInput["where"] = r.where
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "ResourceFeesFilterInput")
	}
	res := <-h.gql.QueryFields("resourceFeesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) Get(ctx context.Context, id string) (*schemaql.ResourceFees, error) {
	var out *schemaql.ResourceFees
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	res := <-h.gql.QueryFields("resourceFeesById", &out, args)
	return out, res.Error
}
