// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// OrganisationResource is the OrganisationResource model.
type OrganisationResource struct {
	BillingEmail                *string `graphql:"billingEmail"`
	CreateTime                  string  `graphql:"createTime"`
	DisplayName                 string  `graphql:"displayName"`
	Etag                        *string `graphql:"etag"`
	Id                          string  `graphql:"id"`
	IdentityMembershipSummaries []struct {
		Id             string  `graphql:"id"`
		OrgDisplayName *string `graphql:"orgDisplayName"`
		Organisation   *string `graphql:"organisation"`
		Role           *string `graphql:"role"`
		UserId         string  `graphql:"userId"`
	} `graphql:"identityMembershipSummaries"`
	IdentityMembershipSummariesAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"identityMembershipSummariesAggregate"`
	MemberCount         *graphql.Int64 `graphql:"memberCount"`
	Name                string         `graphql:"name"`
	OrganisationMembers []struct {
		CreateTime     string  `graphql:"createTime"`
		DisplayName    *string `graphql:"displayName"`
		Email          string  `graphql:"email"`
		Etag           *string `graphql:"etag"`
		Id             string  `graphql:"id"`
		Inviter        *string `graphql:"inviter"`
		Name           string  `graphql:"name"`
		OrganisationId string  `graphql:"organisationId"`
		Role           string  `graphql:"role"`
		State          *string `graphql:"state"`
		UpdateTime     string  `graphql:"updateTime"`
		User           *string `graphql:"user"`
	} `graphql:"organisationMembers"`
	OrganisationMembersAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"organisationMembersAggregate"`
	Settings   *json.RawMessage `graphql:"settings"`
	Slug       *string          `graphql:"slug"`
	State      *string          `graphql:"state"`
	UpdateTime string           `graphql:"updateTime"`
}
