// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// UpdateOrganisationResourceByIdResponse is the UpdateOrganisationResourceByIdResponse model.
type UpdateOrganisationResourceByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		BillingEmail *string          `graphql:"billingEmail"`
		CreateTime   string           `graphql:"createTime"`
		DisplayName  string           `graphql:"displayName"`
		Etag         *string          `graphql:"etag"`
		Id           string           `graphql:"id"`
		MemberCount  *graphql.Int64   `graphql:"memberCount"`
		Name         string           `graphql:"name"`
		Settings     *json.RawMessage `graphql:"settings"`
		Slug         *string          `graphql:"slug"`
		State        *string          `graphql:"state"`
		UpdateTime   string           `graphql:"updateTime"`
	} `graphql:"returning"`
}
