// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeleteCampaignListsByIdResponse is the DeleteCampaignListsByIdResponse model.
type DeleteCampaignListsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		CampaignId    string `graphql:"campaignId"`
		Id            string `graphql:"id"`
		MailingListId string `graphql:"mailingListId"`
	} `graphql:"returning"`
}
