// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"encoding/json"
)

// InsertCampaignResourceResponse is the InsertCampaignResourceResponse model.
type InsertCampaignResourceResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AltBody         *string          `graphql:"altBody"`
		Archive         *bool            `graphql:"archive"`
		ArchiveMeta     *json.RawMessage `graphql:"archiveMeta"`
		ArchiveSlug     *string          `graphql:"archiveSlug"`
		ArchiveTemplate *string          `graphql:"archiveTemplate"`
		Body            *string          `graphql:"body"`
		CreateTime      string           `graphql:"createTime"`
		DisplayName     string           `graphql:"displayName"`
		Format          string           `graphql:"format"`
		Headers         *json.RawMessage `graphql:"headers"`
		Id              string           `graphql:"id"`
		Messenger       *string          `graphql:"messenger"`
		Name            string           `graphql:"name"`
		ScheduleTime    *string          `graphql:"scheduleTime"`
		SenderEmail     *string          `graphql:"senderEmail"`
		StartTime       *string          `graphql:"startTime"`
		State           *string          `graphql:"state"`
		StatsId         *string          `graphql:"statsId"`
		Subject         string           `graphql:"subject"`
		Tags            []*string        `graphql:"tags"`
		Template        *string          `graphql:"template"`
		Type            *string          `graphql:"type"`
		UpdateTime      string           `graphql:"updateTime"`
		Uuid            *string          `graphql:"uuid"`
	} `graphql:"returning"`
}
