// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// UpdateCampaignStatsByIdResponse is the UpdateCampaignStatsByIdResponse model.
type UpdateCampaignStatsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Bounces        *graphql.Int64 `graphql:"bounces"`
		Clicks         *graphql.Int64 `graphql:"clicks"`
		Id             string         `graphql:"id"`
		RecipientCount *graphql.Int64 `graphql:"recipientCount"`
		Sent           *graphql.Int64 `graphql:"sent"`
		Views          *graphql.Int64 `graphql:"views"`
	} `graphql:"returning"`
}
