// Code generated by generateql. DO NOT EDIT.

package occupanciesql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/bookingql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type BookingOccupancies = schemaql.BookingOccupancies
type BookingOccupanciesAggExp = schemaql.BookingOccupanciesAggExp
type DeleteBookingOccupanciesByIdResponse = schemaql.DeleteBookingOccupanciesByIdResponse
type InsertBookingOccupanciesResponse = schemaql.InsertBookingOccupanciesResponse
type UpdateBookingOccupanciesByIdResponse = schemaql.UpdateBookingOccupanciesByIdResponse
