// Code generated by generateql. DO NOT EDIT.

package inputs

// BookingPriceComponentsBoolExp is the BookingPriceComponentsBoolExp input type.
type BookingPriceComponentsBoolExp struct {
	And             []BookingPriceComponentsBoolExp `json:"_and,omitzero"`
	Not             BookingPriceComponentsBoolExp   `json:"_not,omitzero"`
	Or              []BookingPriceComponentsBoolExp `json:"_or,omitzero"`
	AmountId        TextBoolExp                     `json:"amountId,omitzero"`
	BookingId       TextBoolExp                     `json:"bookingId,omitzero"`
	BookingMoney    BookingMoneysBoolExp            `json:"bookingMoney,omitzero"`
	BookingResource BookingResourceBoolExp          `json:"bookingResource,omitzero"`
	Code            TextBoolExp                     `json:"code,omitzero"`
	DisplayName     TextBoolExp                     `json:"displayName,omitzero"`
	Id              TextBoolExp                     `json:"id,omitzero"`
	Type            BookingTypeBoolExp              `json:"type,omitzero"`
}

func (*BookingPriceComponentsBoolExp) GetGraphQLType() string { return "BookingPriceComponentsBoolExp" }
