// Code generated by generateql. DO NOT EDIT.

package inputs

// BookingTimeWindowsFilterInput is the BookingTimeWindowsFilterInput input type.
type BookingTimeWindowsFilterInput struct {
	Limit   *int                           `json:"limit,omitempty"`
	Offset  *int                           `json:"offset,omitempty"`
	OrderBy []BookingTimeWindowsOrderByExp `json:"order_by,omitempty"`
	Where   *BookingTimeWindowsBoolExp     `json:"where,omitempty"`
}

func (*BookingTimeWindowsFilterInput) GetGraphQLType() string { return "BookingTimeWindowsFilterInput" }
