// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/enums"
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// IdentityMembershipSummariesOrderByExp is the IdentityMembershipSummariesOrderByExp input type.
type IdentityMembershipSummariesOrderByExp struct {
	Id                   param.Opt[enums.OrderBy]       `json:"id,omitzero"`
	IdentityUser         IdentityUsersOrderByExp        `json:"identityUser,omitzero"`
	OrgDisplayName       param.Opt[enums.OrderBy]       `json:"orgDisplayName,omitzero"`
	Organisation         param.Opt[enums.OrderBy]       `json:"organisation,omitzero"`
	OrganisationResource OrganisationResourceOrderByExp `json:"organisationResource,omitzero"`
	Role                 param.Opt[enums.OrderBy]       `json:"role,omitzero"`
	UserId               param.Opt[enums.OrderBy]       `json:"userId,omitzero"`
}

func (*IdentityMembershipSummariesOrderByExp) GetGraphQLType() string {
	return "IdentityMembershipSummariesOrderByExp"
}
