// Code generated by generate-ql. DO NOT EDIT.

package inputs

// IdentityUsersBoolExp is the IdentityUsersBoolExp input type.
type IdentityUsersBoolExp struct {
	And                         []IdentityUsersBoolExp              `json:"_and,omitempty"`
	Not                         *IdentityUsersBoolExp               `json:"_not,omitempty"`
	Or                          []IdentityUsersBoolExp              `json:"_or,omitempty"`
	AvatarUrl                   *TextBoolExp                        `json:"avatarUrl,omitempty"`
	BookingResources            *BookingResourceBoolExp             `json:"bookingResources,omitempty"`
	CreateTime                  *TimestampBoolExp                   `json:"createTime,omitempty"`
	DisplayName                 *TextBoolExp                        `json:"displayName,omitempty"`
	Email                       *TextBoolExp                        `json:"email,omitempty"`
	Etag                        *TextBoolExp                        `json:"etag,omitempty"`
	Id                          *TextBoolExp                        `json:"id,omitempty"`
	IdentityMembershipSummaries *IdentityMembershipSummariesBoolExp `json:"identityMembershipSummaries,omitempty"`
	Locale                      *TextBoolExp                        `json:"locale,omitempty"`
	Name                        *TextBoolExp                        `json:"name,omitempty"`
	OrganisationMembers         *OrganisationMembersBoolExp         `json:"organisationMembers,omitempty"`
	OrganisationMembersByUser   *OrganisationMembersBoolExp         `json:"organisationMembersByUser,omitempty"`
	TimeZone                    *TextBoolExp                        `json:"timeZone,omitempty"`
	UpdateTime                  *TimestampBoolExp                   `json:"updateTime,omitempty"`
}

func (*IdentityUsersBoolExp) GetGraphQLType() string { return "IdentityUsersBoolExp" }
