// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// InsertScheduleStayConstraintsObjectInput is the InsertScheduleStayConstraintsObjectInput input type.
type InsertScheduleStayConstraintsObjectInput struct {
	AdvanceMaxDays   param.Opt[int32] `json:"advanceMaxDays,omitzero"`
	AdvanceMinDays   param.Opt[int32] `json:"advanceMinDays,omitzero"`
	CheckinWeekdays  []*string        `json:"checkinWeekdays,omitzero"`
	CheckoutWeekdays []*string        `json:"checkoutWeekdays,omitzero"`
	Id               string           `json:"id"`
	MaxNights        param.Opt[int32] `json:"maxNights,omitzero"`
	MinNights        param.Opt[int32] `json:"minNights,omitzero"`
}

func (*InsertScheduleStayConstraintsObjectInput) GetGraphQLType() string {
	return "InsertScheduleStayConstraintsObjectInput"
}
