// Code generated by generate-ql. DO NOT EDIT.

package inputs

// InsertOrganisationMembersObjectInput is the InsertOrganisationMembersObjectInput input type.
type InsertOrganisationMembersObjectInput struct {
	CreateTime     *string `json:"createTime,omitempty"`
	DisplayName    *string `json:"displayName,omitempty"`
	Email          string  `json:"email,omitempty"`
	Etag           *string `json:"etag,omitempty"`
	Id             string  `json:"id,omitempty"`
	Inviter        *string `json:"inviter,omitempty"`
	Name           string  `json:"name,omitempty"`
	OrganisationId string  `json:"organisationId,omitempty"`
	Role           *string `json:"role,omitempty"`
	State          *string `json:"state,omitempty"`
	UpdateTime     string  `json:"updateTime,omitempty"`
	User           *string `json:"user,omitempty"`
}

func (*InsertOrganisationMembersObjectInput) GetGraphQLType() string {
	return "InsertOrganisationMembersObjectInput"
}
