// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"encoding/json"
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// InsertResourceEntityObjectInput is the InsertResourceEntityObjectInput input type.
type InsertResourceEntityObjectInput struct {
	Attributes  json.RawMessage   `json:"attributes,omitzero"`
	BookingMode param.Opt[string] `json:"bookingMode,omitzero"`
	Capacity    param.Opt[int32]  `json:"capacity,omitzero"`
	CreateTime  param.Opt[string] `json:"createTime,omitzero"`
	Description param.Opt[string] `json:"description,omitzero"`
	DisplayName string            `json:"displayName"`
	Etag        param.Opt[string] `json:"etag,omitzero"`
	Id          string            `json:"id"`
	Name        string            `json:"name"`
	State       param.Opt[string] `json:"state,omitzero"`
	Tags        []*string         `json:"tags,omitzero"`
	TimeZone    string            `json:"timeZone"`
	Type        param.Opt[string] `json:"type,omitzero"`
	UpdateTime  string            `json:"updateTime"`
}

func (*InsertResourceEntityObjectInput) GetGraphQLType() string {
	return "InsertResourceEntityObjectInput"
}
