// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// InsertScheduleRecurringRulesObjectInput is the InsertScheduleRecurringRulesObjectInput input type.
type InsertScheduleRecurringRulesObjectInput struct {
	Closes     param.Opt[string] `json:"closes,omitzero"`
	Id         string            `json:"id"`
	Opens      param.Opt[string] `json:"opens,omitzero"`
	Rrule      string            `json:"rrule"`
	ScheduleId string            `json:"scheduleId"`
}

func (*InsertScheduleRecurringRulesObjectInput) GetGraphQLType() string {
	return "InsertScheduleRecurringRulesObjectInput"
}
