// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// InsertScheduleAvailabilityExceptionsObjectInput is the InsertScheduleAvailabilityExceptionsObjectInput input type.
type InsertScheduleAvailabilityExceptionsObjectInput struct {
	CreateTime  param.Opt[string] `json:"createTime,omitzero"`
	DateRangeId param.Opt[string] `json:"dateRangeId,omitzero"`
	Id          string            `json:"id"`
	Kind        param.Opt[string] `json:"kind,omitzero"`
	Name        string            `json:"name"`
	Reason      param.Opt[string] `json:"reason,omitzero"`
	ResourceId  string            `json:"resourceId"`
	SpanCase    param.Opt[string] `json:"spanCase,omitzero"`
	WindowId    param.Opt[string] `json:"windowId,omitzero"`
}

func (*InsertScheduleAvailabilityExceptionsObjectInput) GetGraphQLType() string {
	return "InsertScheduleAvailabilityExceptionsObjectInput"
}
