// Code generated by generate-ql. DO NOT EDIT.

package inputs

// InsertScheduleAvailabilityExceptionsObjectInput is the InsertScheduleAvailabilityExceptionsObjectInput input type.
type InsertScheduleAvailabilityExceptionsObjectInput struct {
	CreateTime  *string `json:"createTime,omitempty"`
	DateRangeId *string `json:"dateRangeId,omitempty"`
	Id          string  `json:"id,omitempty"`
	Kind        *string `json:"kind,omitempty"`
	Name        string  `json:"name,omitempty"`
	Reason      *string `json:"reason,omitempty"`
	ResourceId  string  `json:"resourceId,omitempty"`
	SpanCase    *string `json:"spanCase,omitempty"`
	WindowId    *string `json:"windowId,omitempty"`
}

func (*InsertScheduleAvailabilityExceptionsObjectInput) GetGraphQLType() string {
	return "InsertScheduleAvailabilityExceptionsObjectInput"
}
