// Code generated by generateql. DO NOT EDIT.

package inputs

// InsertResourceFeesObjectInput is the InsertResourceFeesObjectInput input type.
type InsertResourceFeesObjectInput struct {
	AmountId    *string `json:"amountId,omitempty"`
	Code        string  `json:"code,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Id          string  `json:"id,omitempty"`
	OfferingId  string  `json:"offeringId,omitempty"`
	Percent     *int32  `json:"percent,omitempty"`
	PricingUnit *string `json:"pricingUnit,omitempty"`
	Taxable     *bool   `json:"taxable,omitempty"`
}

func (*InsertResourceFeesObjectInput) GetGraphQLType() string { return "InsertResourceFeesObjectInput" }
