// Code generated by generateql. DO NOT EDIT.

package inputs

// InsertScheduleRecurringRulesObjectInput is the InsertScheduleRecurringRulesObjectInput input type.
type InsertScheduleRecurringRulesObjectInput struct {
	Closes     *string `json:"closes,omitempty"`
	Id         string  `json:"id,omitempty"`
	Opens      *string `json:"opens,omitempty"`
	Rrule      string  `json:"rrule,omitempty"`
	ScheduleId string  `json:"scheduleId,omitempty"`
}

func (*InsertScheduleRecurringRulesObjectInput) GetGraphQLType() string {
	return "InsertScheduleRecurringRulesObjectInput"
}
