// Code generated by generateql. DO NOT EDIT.

package inputs

// InsertPromocodeApplicableOfferingsObjectInput is the InsertPromocodeApplicableOfferingsObjectInput input type.
type InsertPromocodeApplicableOfferingsObjectInput struct {
	Id          string `json:"id"`
	OfferingId  string `json:"offeringId"`
	PromoCodeId string `json:"promoCodeId"`
}

func (*InsertPromocodeApplicableOfferingsObjectInput) GetGraphQLType() string {
	return "InsertPromocodeApplicableOfferingsObjectInput"
}
