// Code generated by generate-ql. DO NOT EDIT.

package inputs

// InsertIdentityUsersObjectInput is the InsertIdentityUsersObjectInput input type.
type InsertIdentityUsersObjectInput struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	CreateTime  *string `json:"createTime,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Email       *string `json:"email,omitempty"`
	Etag        *string `json:"etag,omitempty"`
	Id          string  `json:"id,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	Name        string  `json:"name,omitempty"`
	TimeZone    *string `json:"timeZone,omitempty"`
	UpdateTime  string  `json:"updateTime,omitempty"`
}

func (*InsertIdentityUsersObjectInput) GetGraphQLType() string {
	return "InsertIdentityUsersObjectInput"
}
