// Code generated by generateql. DO NOT EDIT.

package inputs

// Int4BoolExp is the Int4BoolExp input type.
type Int4BoolExp struct {
	And    []Int4BoolExp `json:"_and,omitempty"`
	Eq     *int32        `json:"_eq,omitempty"`
	Gt     *int32        `json:"_gt,omitempty"`
	Gte    *int32        `json:"_gte,omitempty"`
	In     []int32       `json:"_in,omitempty"`
	IsNull *bool         `json:"_is_null,omitempty"`
	Lt     *int32        `json:"_lt,omitempty"`
	Lte    *int32        `json:"_lte,omitempty"`
	Neq    *int32        `json:"_neq,omitempty"`
	Not    *Int4BoolExp  `json:"_not,omitempty"`
	Or     []Int4BoolExp `json:"_or,omitempty"`
}

func (*Int4BoolExp) GetGraphQLType() string { return "Int4BoolExp" }
