// Code generated by generateql. DO NOT EDIT.

package inputs

// OrganisationResourceFilterInput is the OrganisationResourceFilterInput input type.
type OrganisationResourceFilterInput struct {
	Limit   *int                             `json:"limit,omitempty"`
	Offset  *int                             `json:"offset,omitempty"`
	OrderBy []OrganisationResourceOrderByExp `json:"order_by,omitempty"`
	Where   *OrganisationResourceBoolExp     `json:"where,omitempty"`
}

func (*OrganisationResourceFilterInput) GetGraphQLType() string {
	return "OrganisationResourceFilterInput"
}
