// Code generated by generate-ql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/enums"
)

// OrganisationMembersOrderByExp is the OrganisationMembersOrderByExp input type.
type OrganisationMembersOrderByExp struct {
	CreateTime           *enums.OrderBy                  `json:"createTime,omitempty"`
	DisplayName          *enums.OrderBy                  `json:"displayName,omitempty"`
	Email                *enums.OrderBy                  `json:"email,omitempty"`
	Etag                 *enums.OrderBy                  `json:"etag,omitempty"`
	Id                   *enums.OrderBy                  `json:"id,omitempty"`
	IdentityUser         *IdentityUsersOrderByExp        `json:"identityUser,omitempty"`
	IdentityUserByUser   *IdentityUsersOrderByExp        `json:"identityUserByUser,omitempty"`
	Inviter              *enums.OrderBy                  `json:"inviter,omitempty"`
	Name                 *enums.OrderBy                  `json:"name,omitempty"`
	OrganisationId       *enums.OrderBy                  `json:"organisationId,omitempty"`
	OrganisationResource *OrganisationResourceOrderByExp `json:"organisationResource,omitempty"`
	Role                 *enums.OrderBy                  `json:"role,omitempty"`
	State                *enums.OrderBy                  `json:"state,omitempty"`
	UpdateTime           *enums.OrderBy                  `json:"updateTime,omitempty"`
	User                 *enums.OrderBy                  `json:"user,omitempty"`
}

func (*OrganisationMembersOrderByExp) GetGraphQLType() string { return "OrganisationMembersOrderByExp" }
