// Code generated by generateql. DO NOT EDIT.

package inputs

// PrismaMigrationsBoolExp is the PrismaMigrationsBoolExp input type.
type PrismaMigrationsBoolExp struct {
	And               []PrismaMigrationsBoolExp `json:"_and,omitzero"`
	Not               PrismaMigrationsBoolExp   `json:"_not,omitzero"`
	Or                []PrismaMigrationsBoolExp `json:"_or,omitzero"`
	AppliedStepsCount Int4BoolExp               `json:"appliedStepsCount,omitzero"`
	Checksum          VarcharBoolExp            `json:"checksum,omitzero"`
	FinishedAt        TimestamptzBoolExp        `json:"finishedAt,omitzero"`
	Id                VarcharBoolExp            `json:"id,omitzero"`
	Logs              TextBoolExp               `json:"logs,omitzero"`
	MigrationName     VarcharBoolExp            `json:"migrationName,omitzero"`
	RolledBackAt      TimestamptzBoolExp        `json:"rolledBackAt,omitzero"`
	StartedAt         TimestamptzBoolExp        `json:"startedAt,omitzero"`
}

func (*PrismaMigrationsBoolExp) GetGraphQLType() string { return "PrismaMigrationsBoolExp" }
