// Code generated by generateql. DO NOT EDIT.

package inputs

// PromocodeApplicableOfferingsBoolExp is the PromocodeApplicableOfferingsBoolExp input type.
type PromocodeApplicableOfferingsBoolExp struct {
	And               []PromocodeApplicableOfferingsBoolExp `json:"_and,omitzero"`
	Not               PromocodeApplicableOfferingsBoolExp   `json:"_not,omitzero"`
	Or                []PromocodeApplicableOfferingsBoolExp `json:"_or,omitzero"`
	Id                TextBoolExp                           `json:"id,omitzero"`
	OfferingId        TextBoolExp                           `json:"offeringId,omitzero"`
	PromoCodeId       TextBoolExp                           `json:"promoCodeId,omitzero"`
	PromocodeResource PromocodeResourceBoolExp              `json:"promocodeResource,omitzero"`
	ResourceOffering  ResourceOfferingsBoolExp              `json:"resourceOffering,omitzero"`
}

func (*PromocodeApplicableOfferingsBoolExp) GetGraphQLType() string {
	return "PromocodeApplicableOfferingsBoolExp"
}
