// Code generated by generateql. DO NOT EDIT.

package inputs

// PromocodePromoCodeStateBoolExp is the PromocodePromoCodeStateBoolExp input type.
type PromocodePromoCodeStateBoolExp struct {
	And    []PromocodePromoCodeStateBoolExp `json:"_and,omitempty"`
	Eq     *string                          `json:"_eq,omitempty"`
	Gt     *string                          `json:"_gt,omitempty"`
	Gte    *string                          `json:"_gte,omitempty"`
	In     []string                         `json:"_in,omitempty"`
	IsNull *bool                            `json:"_is_null,omitempty"`
	Lt     *string                          `json:"_lt,omitempty"`
	Lte    *string                          `json:"_lte,omitempty"`
	Neq    *string                          `json:"_neq,omitempty"`
	Not    *PromocodePromoCodeStateBoolExp  `json:"_not,omitempty"`
	Or     []PromocodePromoCodeStateBoolExp `json:"_or,omitempty"`
}

func (*PromocodePromoCodeStateBoolExp) GetGraphQLType() string {
	return "PromocodePromoCodeStateBoolExp"
}
