// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/types/enums"
)

// PromocodeApplicableOfferingsOrderByExp is the PromocodeApplicableOfferingsOrderByExp input type.
type PromocodeApplicableOfferingsOrderByExp struct {
	Id                *enums.OrderBy               `json:"id,omitempty"`
	OfferingId        *enums.OrderBy               `json:"offeringId,omitempty"`
	PromoCodeId       *enums.OrderBy               `json:"promoCodeId,omitempty"`
	PromocodeResource *PromocodeResourceOrderByExp `json:"promocodeResource,omitempty"`
	ResourceOffering  *ResourceOfferingsOrderByExp `json:"resourceOffering,omitempty"`
}

func (*PromocodeApplicableOfferingsOrderByExp) GetGraphQLType() string {
	return "PromocodeApplicableOfferingsOrderByExp"
}
