// Code generated by generateql. DO NOT EDIT.

package inputs

// PromocodeResourceBoolExp is the PromocodeResourceBoolExp input type.
type PromocodeResourceBoolExp struct {
	And                          []PromocodeResourceBoolExp           `json:"_and,omitempty"`
	Not                          *PromocodeResourceBoolExp            `json:"_not,omitempty"`
	Or                           []PromocodeResourceBoolExp           `json:"_or,omitempty"`
	AmountOffId                  *TextBoolExp                         `json:"amountOffId,omitempty"`
	BookingMoney                 *BookingMoneysBoolExp                `json:"bookingMoney,omitempty"`
	BookingMoneyByMinSubtotalId  *BookingMoneysBoolExp                `json:"bookingMoneyByMinSubtotalId,omitempty"`
	BookingResources             *BookingResourceBoolExp              `json:"bookingResources,omitempty"`
	Code                         *TextBoolExp                         `json:"code,omitempty"`
	CreateTime                   *TimestampBoolExp                    `json:"createTime,omitempty"`
	Description                  *TextBoolExp                         `json:"description,omitempty"`
	Disabled                     *BoolBoolExp                         `json:"disabled,omitempty"`
	DiscountType                 *PromocodeDiscountTypeBoolExp        `json:"discountType,omitempty"`
	DisplayName                  *TextBoolExp                         `json:"displayName,omitempty"`
	Etag                         *TextBoolExp                         `json:"etag,omitempty"`
	Id                           *TextBoolExp                         `json:"id,omitempty"`
	MaxRedemptions               *Int8BoolExp                         `json:"maxRedemptions,omitempty"`
	MinSubtotalId                *TextBoolExp                         `json:"minSubtotalId,omitempty"`
	Name                         *TextBoolExp                         `json:"name,omitempty"`
	PerCustomerLimit             *Int4BoolExp                         `json:"perCustomerLimit,omitempty"`
	PercentOff                   *Int4BoolExp                         `json:"percentOff,omitempty"`
	PromocodeApplicableOfferings *PromocodeApplicableOfferingsBoolExp `json:"promocodeApplicableOfferings,omitempty"`
	PromocodeApplicableResources *PromocodeApplicableResourcesBoolExp `json:"promocodeApplicableResources,omitempty"`
	RedeemEndTime                *TimestampBoolExp                    `json:"redeemEndTime,omitempty"`
	RedeemStartTime              *TimestampBoolExp                    `json:"redeemStartTime,omitempty"`
	RedemptionCount              *Int8BoolExp                         `json:"redemptionCount,omitempty"`
	State                        *PromocodePromoCodeStateBoolExp      `json:"state,omitempty"`
	UpdateTime                   *TimestampBoolExp                    `json:"updateTime,omitempty"`
}

func (*PromocodeResourceBoolExp) GetGraphQLType() string { return "PromocodeResourceBoolExp" }
