// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ResourceOfferingStateBoolExp is the ResourceOfferingStateBoolExp input type.
type ResourceOfferingStateBoolExp struct {
	And    []ResourceOfferingStateBoolExp `json:"_and,omitempty"`
	Eq     *string                        `json:"_eq,omitempty"`
	Gt     *string                        `json:"_gt,omitempty"`
	Gte    *string                        `json:"_gte,omitempty"`
	In     []string                       `json:"_in,omitempty"`
	IsNull *bool                          `json:"_is_null,omitempty"`
	Lt     *string                        `json:"_lt,omitempty"`
	Lte    *string                        `json:"_lte,omitempty"`
	Neq    *string                        `json:"_neq,omitempty"`
	Not    *ResourceOfferingStateBoolExp  `json:"_not,omitempty"`
	Or     []ResourceOfferingStateBoolExp `json:"_or,omitempty"`
}

func (*ResourceOfferingStateBoolExp) GetGraphQLType() string { return "ResourceOfferingStateBoolExp" }
