// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// ResourceLosDiscountsFilterInput is the ResourceLosDiscountsFilterInput input type.
type ResourceLosDiscountsFilterInput struct {
	Limit   param.Opt[int]                   `json:"limit,omitzero"`
	Offset  param.Opt[int]                   `json:"offset,omitzero"`
	OrderBy []ResourceLosDiscountsOrderByExp `json:"order_by,omitzero"`
	Where   ResourceLosDiscountsBoolExp      `json:"where,omitzero"`
}

func (*ResourceLosDiscountsFilterInput) GetGraphQLType() string {
	return "ResourceLosDiscountsFilterInput"
}
