// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ResourceEntityFilterInput is the ResourceEntityFilterInput input type.
type ResourceEntityFilterInput struct {
	Limit   *int                       `json:"limit,omitempty"`
	Offset  *int                       `json:"offset,omitempty"`
	OrderBy []ResourceEntityOrderByExp `json:"order_by,omitempty"`
	Where   *ResourceEntityBoolExp     `json:"where,omitempty"`
}

func (*ResourceEntityFilterInput) GetGraphQLType() string { return "ResourceEntityFilterInput" }
