// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/enums"
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// ResourceFeesOrderByExp is the ResourceFeesOrderByExp input type.
type ResourceFeesOrderByExp struct {
	AmountId         param.Opt[enums.OrderBy]    `json:"amountId,omitzero"`
	BookingMoney     BookingMoneysOrderByExp     `json:"bookingMoney,omitzero"`
	Code             param.Opt[enums.OrderBy]    `json:"code,omitzero"`
	DisplayName      param.Opt[enums.OrderBy]    `json:"displayName,omitzero"`
	Id               param.Opt[enums.OrderBy]    `json:"id,omitzero"`
	OfferingId       param.Opt[enums.OrderBy]    `json:"offeringId,omitzero"`
	Percent          param.Opt[enums.OrderBy]    `json:"percent,omitzero"`
	PricingUnit      param.Opt[enums.OrderBy]    `json:"pricingUnit,omitzero"`
	ResourceOffering ResourceOfferingsOrderByExp `json:"resourceOffering,omitzero"`
	Taxable          param.Opt[enums.OrderBy]    `json:"taxable,omitzero"`
}

func (*ResourceFeesOrderByExp) GetGraphQLType() string { return "ResourceFeesOrderByExp" }
