// Code generated by generateql. DO NOT EDIT.

package inputs

// ResourceResourceStateBoolExp is the ResourceResourceStateBoolExp input type.
type ResourceResourceStateBoolExp struct {
	And    []ResourceResourceStateBoolExp `json:"_and,omitempty"`
	Eq     *string                        `json:"_eq,omitempty"`
	Gt     *string                        `json:"_gt,omitempty"`
	Gte    *string                        `json:"_gte,omitempty"`
	In     []string                       `json:"_in,omitempty"`
	IsNull *bool                          `json:"_is_null,omitempty"`
	Lt     *string                        `json:"_lt,omitempty"`
	Lte    *string                        `json:"_lte,omitempty"`
	Neq    *string                        `json:"_neq,omitempty"`
	Not    *ResourceResourceStateBoolExp  `json:"_not,omitempty"`
	Or     []ResourceResourceStateBoolExp `json:"_or,omitempty"`
}

func (*ResourceResourceStateBoolExp) GetGraphQLType() string { return "ResourceResourceStateBoolExp" }
