// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ResourceFeesFilterInput is the ResourceFeesFilterInput input type.
type ResourceFeesFilterInput struct {
	Limit   *int                     `json:"limit,omitempty"`
	Offset  *int                     `json:"offset,omitempty"`
	OrderBy []ResourceFeesOrderByExp `json:"order_by,omitempty"`
	Where   *ResourceFeesBoolExp     `json:"where,omitempty"`
}

func (*ResourceFeesFilterInput) GetGraphQLType() string { return "ResourceFeesFilterInput" }
