// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/types/enums"
)

// ResourceRateOverridesOrderByExp is the ResourceRateOverridesOrderByExp input type.
type ResourceRateOverridesOrderByExp struct {
	BookingMoney      *BookingMoneysOrderByExp      `json:"bookingMoney,omitempty"`
	DateRangeId       *enums.OrderBy                `json:"dateRangeId,omitempty"`
	Id                *enums.OrderBy                `json:"id,omitempty"`
	OfferingId        *enums.OrderBy                `json:"offeringId,omitempty"`
	PriceId           *enums.OrderBy                `json:"priceId,omitempty"`
	ResourceOffering  *ResourceOfferingsOrderByExp  `json:"resourceOffering,omitempty"`
	ScheduleDateRange *ScheduleDateRangesOrderByExp `json:"scheduleDateRange,omitempty"`
}

func (*ResourceRateOverridesOrderByExp) GetGraphQLType() string {
	return "ResourceRateOverridesOrderByExp"
}
