// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// ResourceRateOverridesFilterInput is the ResourceRateOverridesFilterInput input type.
type ResourceRateOverridesFilterInput struct {
	Limit   param.Opt[int]                    `json:"limit,omitzero"`
	Offset  param.Opt[int]                    `json:"offset,omitzero"`
	OrderBy []ResourceRateOverridesOrderByExp `json:"order_by,omitzero"`
	Where   ResourceRateOverridesBoolExp      `json:"where,omitzero"`
}

func (*ResourceRateOverridesFilterInput) GetGraphQLType() string {
	return "ResourceRateOverridesFilterInput"
}
