// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/enums"
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// ResourceOfferingsLinkOrderByExp is the ResourceOfferingsLinkOrderByExp input type.
type ResourceOfferingsLinkOrderByExp struct {
	Id               param.Opt[enums.OrderBy]    `json:"id,omitzero"`
	OfferingId       param.Opt[enums.OrderBy]    `json:"offeringId,omitzero"`
	ResourceEntity   ResourceEntityOrderByExp    `json:"resourceEntity,omitzero"`
	ResourceId       param.Opt[enums.OrderBy]    `json:"resourceId,omitzero"`
	ResourceOffering ResourceOfferingsOrderByExp `json:"resourceOffering,omitzero"`
}

func (*ResourceOfferingsLinkOrderByExp) GetGraphQLType() string {
	return "ResourceOfferingsLinkOrderByExp"
}
