// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ResourceEntityBoolExp is the ResourceEntityBoolExp input type.
type ResourceEntityBoolExp struct {
	And                            []ResourceEntityBoolExp                `json:"_and,omitempty"`
	Not                            *ResourceEntityBoolExp                 `json:"_not,omitempty"`
	Or                             []ResourceEntityBoolExp                `json:"_or,omitempty"`
	Attributes                     *JsonbBoolExp                          `json:"attributes,omitempty"`
	BookingMode                    *ResourceBookingModeBoolExp            `json:"bookingMode,omitempty"`
	BookingResources               *BookingResourceBoolExp                `json:"bookingResources,omitempty"`
	Capacity                       *Int4BoolExp                           `json:"capacity,omitempty"`
	CreateTime                     *TimestampBoolExp                      `json:"createTime,omitempty"`
	Description                    *TextBoolExp                           `json:"description,omitempty"`
	DisplayName                    *TextBoolExp                           `json:"displayName,omitempty"`
	Etag                           *TextBoolExp                           `json:"etag,omitempty"`
	Id                             *TextBoolExp                           `json:"id,omitempty"`
	Name                           *TextBoolExp                           `json:"name,omitempty"`
	PromocodeApplicableResources   *PromocodeApplicableResourcesBoolExp   `json:"promocodeApplicableResources,omitempty"`
	ResourceOfferings              *ResourceOfferingsBoolExp              `json:"resourceOfferings,omitempty"`
	ResourceOfferingsLinks         *ResourceOfferingsLinkBoolExp          `json:"resourceOfferingsLinks,omitempty"`
	ScheduleAvailabilityExceptions *ScheduleAvailabilityExceptionsBoolExp `json:"scheduleAvailabilityExceptions,omitempty"`
	State                          *ResourceResourceStateBoolExp          `json:"state,omitempty"`
	TimeZone                       *TextBoolExp                           `json:"timeZone,omitempty"`
	Type                           *ResourceResourceTypeBoolExp           `json:"type,omitempty"`
	UpdateTime                     *TimestampBoolExp                      `json:"updateTime,omitempty"`
}

func (*ResourceEntityBoolExp) GetGraphQLType() string { return "ResourceEntityBoolExp" }
