// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ScheduleResourceFilterInput is the ScheduleResourceFilterInput input type.
type ScheduleResourceFilterInput struct {
	Limit   *int                         `json:"limit,omitempty"`
	Offset  *int                         `json:"offset,omitempty"`
	OrderBy []ScheduleResourceOrderByExp `json:"order_by,omitempty"`
	Where   *ScheduleResourceBoolExp     `json:"where,omitempty"`
}

func (*ScheduleResourceFilterInput) GetGraphQLType() string { return "ScheduleResourceFilterInput" }
