// Code generated by generateql. DO NOT EDIT.

package inputs

// ScheduleExceptionsBoolExp is the ScheduleExceptionsBoolExp input type.
type ScheduleExceptionsBoolExp struct {
	And                           []ScheduleExceptionsBoolExp            `json:"_and,omitempty"`
	Not                           *ScheduleExceptionsBoolExp             `json:"_not,omitempty"`
	Or                            []ScheduleExceptionsBoolExp            `json:"_or,omitempty"`
	AvailabilityExceptionId       *TextBoolExp                           `json:"availabilityExceptionId,omitempty"`
	Id                            *TextBoolExp                           `json:"id,omitempty"`
	ScheduleAvailabilityException *ScheduleAvailabilityExceptionsBoolExp `json:"scheduleAvailabilityException,omitempty"`
	ScheduleId                    *TextBoolExp                           `json:"scheduleId,omitempty"`
	ScheduleResource              *ScheduleResourceBoolExp               `json:"scheduleResource,omitempty"`
}

func (*ScheduleExceptionsBoolExp) GetGraphQLType() string { return "ScheduleExceptionsBoolExp" }
