// Code generated by generateql. DO NOT EDIT.

package inputs

// ScheduleDateRangesBoolExp is the ScheduleDateRangesBoolExp input type.
type ScheduleDateRangesBoolExp struct {
	And                            []ScheduleDateRangesBoolExp           `json:"_and,omitzero"`
	Not                            ScheduleDateRangesBoolExp             `json:"_not,omitzero"`
	Or                             []ScheduleDateRangesBoolExp           `json:"_or,omitzero"`
	EndDate                        TimestampBoolExp                      `json:"endDate,omitzero"`
	Id                             TextBoolExp                           `json:"id,omitzero"`
	ResourceRateOverrides          ResourceRateOverridesBoolExp          `json:"resourceRateOverrides,omitzero"`
	ScheduleAvailabilityExceptions ScheduleAvailabilityExceptionsBoolExp `json:"scheduleAvailabilityExceptions,omitzero"`
	StartDate                      TimestampBoolExp                      `json:"startDate,omitzero"`
}

func (*ScheduleDateRangesBoolExp) GetGraphQLType() string { return "ScheduleDateRangesBoolExp" }
