// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ScheduleStayConstraintsBoolExp is the ScheduleStayConstraintsBoolExp input type.
type ScheduleStayConstraintsBoolExp struct {
	And               []ScheduleStayConstraintsBoolExp `json:"_and,omitempty"`
	Not               *ScheduleStayConstraintsBoolExp  `json:"_not,omitempty"`
	Or                []ScheduleStayConstraintsBoolExp `json:"_or,omitempty"`
	AdvanceMaxDays    *Int4BoolExp                     `json:"advanceMaxDays,omitempty"`
	AdvanceMinDays    *Int4BoolExp                     `json:"advanceMinDays,omitempty"`
	Id                *TextBoolExp                     `json:"id,omitempty"`
	MaxNights         *Int4BoolExp                     `json:"maxNights,omitempty"`
	MinNights         *Int4BoolExp                     `json:"minNights,omitempty"`
	ScheduleResources *ScheduleResourceBoolExp         `json:"scheduleResources,omitempty"`
}

func (*ScheduleStayConstraintsBoolExp) GetGraphQLType() string {
	return "ScheduleStayConstraintsBoolExp"
}
