// Code generated by generate-ql. DO NOT EDIT.

package inputs

// ScheduleBufferSettingsBoolExp is the ScheduleBufferSettingsBoolExp input type.
type ScheduleBufferSettingsBoolExp struct {
	And               []ScheduleBufferSettingsBoolExp `json:"_and,omitempty"`
	Not               *ScheduleBufferSettingsBoolExp  `json:"_not,omitempty"`
	Or                []ScheduleBufferSettingsBoolExp `json:"_or,omitempty"`
	EndDelta          *TextBoolExp                    `json:"endDelta,omitempty"`
	Gap               *TextBoolExp                    `json:"gap,omitempty"`
	Id                *TextBoolExp                    `json:"id,omitempty"`
	MaxAdvance        *TextBoolExp                    `json:"maxAdvance,omitempty"`
	MinNotice         *TextBoolExp                    `json:"minNotice,omitempty"`
	ScheduleResources *ScheduleResourceBoolExp        `json:"scheduleResources,omitempty"`
	StartDelta        *TextBoolExp                    `json:"startDelta,omitempty"`
}

func (*ScheduleBufferSettingsBoolExp) GetGraphQLType() string { return "ScheduleBufferSettingsBoolExp" }
