// Code generated by generate-ql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/enums"
)

// ScheduleAvailabilityExceptionsOrderByExp is the ScheduleAvailabilityExceptionsOrderByExp input type.
type ScheduleAvailabilityExceptionsOrderByExp struct {
	BookingTimeWindow *BookingTimeWindowsOrderByExp `json:"bookingTimeWindow,omitempty"`
	CreateTime        *enums.OrderBy                `json:"createTime,omitempty"`
	DateRangeId       *enums.OrderBy                `json:"dateRangeId,omitempty"`
	Id                *enums.OrderBy                `json:"id,omitempty"`
	Kind              *enums.OrderBy                `json:"kind,omitempty"`
	Name              *enums.OrderBy                `json:"name,omitempty"`
	Reason            *enums.OrderBy                `json:"reason,omitempty"`
	ResourceEntity    *ResourceEntityOrderByExp     `json:"resourceEntity,omitempty"`
	ResourceId        *enums.OrderBy                `json:"resourceId,omitempty"`
	ScheduleDateRange *ScheduleDateRangesOrderByExp `json:"scheduleDateRange,omitempty"`
	SpanCase          *enums.OrderBy                `json:"spanCase,omitempty"`
	WindowId          *enums.OrderBy                `json:"windowId,omitempty"`
}

func (*ScheduleAvailabilityExceptionsOrderByExp) GetGraphQLType() string {
	return "ScheduleAvailabilityExceptionsOrderByExp"
}
