// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// ScheduleRecurringRulesFilterInput is the ScheduleRecurringRulesFilterInput input type.
type ScheduleRecurringRulesFilterInput struct {
	Limit   param.Opt[int]                     `json:"limit,omitzero"`
	Offset  param.Opt[int]                     `json:"offset,omitzero"`
	OrderBy []ScheduleRecurringRulesOrderByExp `json:"order_by,omitzero"`
	Where   ScheduleRecurringRulesBoolExp      `json:"where,omitzero"`
}

func (*ScheduleRecurringRulesFilterInput) GetGraphQLType() string {
	return "ScheduleRecurringRulesFilterInput"
}
