// Code generated by generateql. DO NOT EDIT.

package inputs

// ScheduleResourceBoolExp is the ScheduleResourceBoolExp input type.
type ScheduleResourceBoolExp struct {
	And                        []ScheduleResourceBoolExp            `json:"_and,omitempty"`
	Not                        *ScheduleResourceBoolExp             `json:"_not,omitempty"`
	Or                         []ScheduleResourceBoolExp            `json:"_or,omitempty"`
	BuffersId                  *TextBoolExp                         `json:"buffersId,omitempty"`
	CancellationPolicyId       *TextBoolExp                         `json:"cancellationPolicyId,omitempty"`
	Etag                       *TextBoolExp                         `json:"etag,omitempty"`
	Id                         *TextBoolExp                         `json:"id,omitempty"`
	Name                       *TextBoolExp                         `json:"name,omitempty"`
	ScheduleBufferSetting      *ScheduleBufferSettingsBoolExp       `json:"scheduleBufferSetting,omitempty"`
	ScheduleCancellationPolicy *ScheduleCancellationPoliciesBoolExp `json:"scheduleCancellationPolicy,omitempty"`
	ScheduleExceptions         *ScheduleExceptionsBoolExp           `json:"scheduleExceptions,omitempty"`
	ScheduleRecurringRules     *ScheduleRecurringRulesBoolExp       `json:"scheduleRecurringRules,omitempty"`
	ScheduleStayConstraint     *ScheduleStayConstraintsBoolExp      `json:"scheduleStayConstraint,omitempty"`
	StayConstraintsId          *TextBoolExp                         `json:"stayConstraintsId,omitempty"`
}

func (*ScheduleResourceBoolExp) GetGraphQLType() string { return "ScheduleResourceBoolExp" }
