// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleAvailabilityExceptionsWindowIdInput is the UpdateColumnScheduleAvailabilityExceptionsWindowIdInput input type.
type UpdateColumnScheduleAvailabilityExceptionsWindowIdInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleAvailabilityExceptionsWindowIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleAvailabilityExceptionsWindowIdInput"
}
