// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnResourceEntityTagsInput is the UpdateColumnResourceEntityTagsInput input type.
type UpdateColumnResourceEntityTagsInput struct {
	Set []string `json:"set,omitempty"`
}

func (*UpdateColumnResourceEntityTagsInput) GetGraphQLType() string {
	return "UpdateColumnResourceEntityTagsInput"
}
