// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnPrismaMigrationsFinishedAtInput is the UpdateColumnPrismaMigrationsFinishedAtInput input type.
type UpdateColumnPrismaMigrationsFinishedAtInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnPrismaMigrationsFinishedAtInput) GetGraphQLType() string {
	return "UpdateColumnPrismaMigrationsFinishedAtInput"
}
