// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateScheduleBufferSettingsByIdUpdateColumnsInput is the UpdateScheduleBufferSettingsByIdUpdateColumnsInput input type.
type UpdateScheduleBufferSettingsByIdUpdateColumnsInput struct {
	EndDelta   *UpdateColumnScheduleBufferSettingsEndDeltaInput   `json:"endDelta,omitempty"`
	Gap        *UpdateColumnScheduleBufferSettingsGapInput        `json:"gap,omitempty"`
	Id         *UpdateColumnScheduleBufferSettingsIdInput         `json:"id,omitempty"`
	MaxAdvance *UpdateColumnScheduleBufferSettingsMaxAdvanceInput `json:"maxAdvance,omitempty"`
	MinNotice  *UpdateColumnScheduleBufferSettingsMinNoticeInput  `json:"minNotice,omitempty"`
	StartDelta *UpdateColumnScheduleBufferSettingsStartDeltaInput `json:"startDelta,omitempty"`
}

func (*UpdateScheduleBufferSettingsByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateScheduleBufferSettingsByIdUpdateColumnsInput"
}
