// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleStayConstraintsAdvanceMaxDaysInput is the UpdateColumnScheduleStayConstraintsAdvanceMaxDaysInput input type.
type UpdateColumnScheduleStayConstraintsAdvanceMaxDaysInput struct {
	Set *int32 `json:"set,omitempty"`
}

func (*UpdateColumnScheduleStayConstraintsAdvanceMaxDaysInput) GetGraphQLType() string {
	return "UpdateColumnScheduleStayConstraintsAdvanceMaxDaysInput"
}
