// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnPromocodeResourcePerCustomerLimitInput is the UpdateColumnPromocodeResourcePerCustomerLimitInput input type.
type UpdateColumnPromocodeResourcePerCustomerLimitInput struct {
	Set param.Opt[int32] `json:"set,omitzero"`
}

func (*UpdateColumnPromocodeResourcePerCustomerLimitInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourcePerCustomerLimitInput"
}
