// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateResourceLosDiscountsByIdUpdateColumnsInput is the UpdateResourceLosDiscountsByIdUpdateColumnsInput input type.
type UpdateResourceLosDiscountsByIdUpdateColumnsInput struct {
	AmountOffId UpdateColumnResourceLosDiscountsAmountOffIdInput `json:"amountOffId,omitzero"`
	Id          UpdateColumnResourceLosDiscountsIdInput          `json:"id,omitzero"`
	MinNights   UpdateColumnResourceLosDiscountsMinNightsInput   `json:"minNights,omitzero"`
	OfferingId  UpdateColumnResourceLosDiscountsOfferingIdInput  `json:"offeringId,omitzero"`
	PercentOff  UpdateColumnResourceLosDiscountsPercentOffInput  `json:"percentOff,omitzero"`
}

func (*UpdateResourceLosDiscountsByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateResourceLosDiscountsByIdUpdateColumnsInput"
}
