// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceOfferingsStateInput is the UpdateColumnResourceOfferingsStateInput input type.
type UpdateColumnResourceOfferingsStateInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnResourceOfferingsStateInput) GetGraphQLType() string {
	return "UpdateColumnResourceOfferingsStateInput"
}
