// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateResourceRateOverridesByIdUpdateColumnsInput is the UpdateResourceRateOverridesByIdUpdateColumnsInput input type.
type UpdateResourceRateOverridesByIdUpdateColumnsInput struct {
	DateRangeId *UpdateColumnResourceRateOverridesDateRangeIdInput `json:"dateRangeId,omitempty"`
	Id          *UpdateColumnResourceRateOverridesIdInput          `json:"id,omitempty"`
	OfferingId  *UpdateColumnResourceRateOverridesOfferingIdInput  `json:"offeringId,omitempty"`
	PriceId     *UpdateColumnResourceRateOverridesPriceIdInput     `json:"priceId,omitempty"`
	Weekdays    *UpdateColumnResourceRateOverridesWeekdaysInput    `json:"weekdays,omitempty"`
}

func (*UpdateResourceRateOverridesByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateResourceRateOverridesByIdUpdateColumnsInput"
}
