// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnPromocodeResourceAmountOffIdInput is the UpdateColumnPromocodeResourceAmountOffIdInput input type.
type UpdateColumnPromocodeResourceAmountOffIdInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnPromocodeResourceAmountOffIdInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceAmountOffIdInput"
}
