// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnOrganisationMembersUserInput is the UpdateColumnOrganisationMembersUserInput input type.
type UpdateColumnOrganisationMembersUserInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnOrganisationMembersUserInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationMembersUserInput"
}
