// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnBookingResourceUpdateTimeInput is the UpdateColumnBookingResourceUpdateTimeInput input type.
type UpdateColumnBookingResourceUpdateTimeInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnBookingResourceUpdateTimeInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceUpdateTimeInput"
}
