// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleRefundTiersIdInput is the UpdateColumnScheduleRefundTiersIdInput input type.
type UpdateColumnScheduleRefundTiersIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleRefundTiersIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleRefundTiersIdInput"
}
