// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnOrganisationMembersEmailInput is the UpdateColumnOrganisationMembersEmailInput input type.
type UpdateColumnOrganisationMembersEmailInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnOrganisationMembersEmailInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationMembersEmailInput"
}
