// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleBufferSettingsIdInput is the UpdateColumnScheduleBufferSettingsIdInput input type.
type UpdateColumnScheduleBufferSettingsIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleBufferSettingsIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleBufferSettingsIdInput"
}
