// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnResourceEntityCapacityInput is the UpdateColumnResourceEntityCapacityInput input type.
type UpdateColumnResourceEntityCapacityInput struct {
	Set *int32 `json:"set,omitempty"`
}

func (*UpdateColumnResourceEntityCapacityInput) GetGraphQLType() string {
	return "UpdateColumnResourceEntityCapacityInput"
}
