// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnBookingResourceRefundPercentInput is the UpdateColumnBookingResourceRefundPercentInput input type.
type UpdateColumnBookingResourceRefundPercentInput struct {
	Set *int32 `json:"set,omitempty"`
}

func (*UpdateColumnBookingResourceRefundPercentInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceRefundPercentInput"
}
