// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceTaxesCodeInput is the UpdateColumnResourceTaxesCodeInput input type.
type UpdateColumnResourceTaxesCodeInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnResourceTaxesCodeInput) GetGraphQLType() string {
	return "UpdateColumnResourceTaxesCodeInput"
}
