// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnPromocodeResourceDisplayNameInput is the UpdateColumnPromocodeResourceDisplayNameInput input type.
type UpdateColumnPromocodeResourceDisplayNameInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnPromocodeResourceDisplayNameInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceDisplayNameInput"
}
