// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnOrganisationMembersCreateTimeInput is the UpdateColumnOrganisationMembersCreateTimeInput input type.
type UpdateColumnOrganisationMembersCreateTimeInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnOrganisationMembersCreateTimeInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationMembersCreateTimeInput"
}
