// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnResourceEntityDescriptionInput is the UpdateColumnResourceEntityDescriptionInput input type.
type UpdateColumnResourceEntityDescriptionInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnResourceEntityDescriptionInput) GetGraphQLType() string {
	return "UpdateColumnResourceEntityDescriptionInput"
}
