// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnBookingResourceContactIdInput is the UpdateColumnBookingResourceContactIdInput input type.
type UpdateColumnBookingResourceContactIdInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnBookingResourceContactIdInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceContactIdInput"
}
