// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnBookingResourceConfirmTimeInput is the UpdateColumnBookingResourceConfirmTimeInput input type.
type UpdateColumnBookingResourceConfirmTimeInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnBookingResourceConfirmTimeInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceConfirmTimeInput"
}
