// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnBookingTimeWindowsIdInput is the UpdateColumnBookingTimeWindowsIdInput input type.
type UpdateColumnBookingTimeWindowsIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnBookingTimeWindowsIdInput) GetGraphQLType() string {
	return "UpdateColumnBookingTimeWindowsIdInput"
}
