// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateScheduleBufferSettingsByIdUpdateColumnsInput is the UpdateScheduleBufferSettingsByIdUpdateColumnsInput input type.
type UpdateScheduleBufferSettingsByIdUpdateColumnsInput struct {
	EndDelta   UpdateColumnScheduleBufferSettingsEndDeltaInput   `json:"endDelta,omitzero"`
	Gap        UpdateColumnScheduleBufferSettingsGapInput        `json:"gap,omitzero"`
	Id         UpdateColumnScheduleBufferSettingsIdInput         `json:"id,omitzero"`
	MaxAdvance UpdateColumnScheduleBufferSettingsMaxAdvanceInput `json:"maxAdvance,omitzero"`
	MinNotice  UpdateColumnScheduleBufferSettingsMinNoticeInput  `json:"minNotice,omitzero"`
	StartDelta UpdateColumnScheduleBufferSettingsStartDeltaInput `json:"startDelta,omitzero"`
}

func (*UpdateScheduleBufferSettingsByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateScheduleBufferSettingsByIdUpdateColumnsInput"
}
