// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateOrganisationMembersByIdUpdateColumnsInput is the UpdateOrganisationMembersByIdUpdateColumnsInput input type.
type UpdateOrganisationMembersByIdUpdateColumnsInput struct {
	CreateTime     *UpdateColumnOrganisationMembersCreateTimeInput     `json:"createTime,omitempty"`
	DisplayName    *UpdateColumnOrganisationMembersDisplayNameInput    `json:"displayName,omitempty"`
	Email          *UpdateColumnOrganisationMembersEmailInput          `json:"email,omitempty"`
	Etag           *UpdateColumnOrganisationMembersEtagInput           `json:"etag,omitempty"`
	Id             *UpdateColumnOrganisationMembersIdInput             `json:"id,omitempty"`
	Inviter        *UpdateColumnOrganisationMembersInviterInput        `json:"inviter,omitempty"`
	Name           *UpdateColumnOrganisationMembersNameInput           `json:"name,omitempty"`
	OrganisationId *UpdateColumnOrganisationMembersOrganisationIdInput `json:"organisationId,omitempty"`
	Role           *UpdateColumnOrganisationMembersRoleInput           `json:"role,omitempty"`
	State          *UpdateColumnOrganisationMembersStateInput          `json:"state,omitempty"`
	UpdateTime     *UpdateColumnOrganisationMembersUpdateTimeInput     `json:"updateTime,omitempty"`
	User           *UpdateColumnOrganisationMembersUserInput           `json:"user,omitempty"`
}

func (*UpdateOrganisationMembersByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateOrganisationMembersByIdUpdateColumnsInput"
}
