// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnResourceRateOverridesDateRangeIdInput is the UpdateColumnResourceRateOverridesDateRangeIdInput input type.
type UpdateColumnResourceRateOverridesDateRangeIdInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnResourceRateOverridesDateRangeIdInput) GetGraphQLType() string {
	return "UpdateColumnResourceRateOverridesDateRangeIdInput"
}
