// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnPrismaMigrationsRolledBackAtInput is the UpdateColumnPrismaMigrationsRolledBackAtInput input type.
type UpdateColumnPrismaMigrationsRolledBackAtInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnPrismaMigrationsRolledBackAtInput) GetGraphQLType() string {
	return "UpdateColumnPrismaMigrationsRolledBackAtInput"
}
