// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleAvailabilityExceptionsResourceIdInput is the UpdateColumnScheduleAvailabilityExceptionsResourceIdInput input type.
type UpdateColumnScheduleAvailabilityExceptionsResourceIdInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnScheduleAvailabilityExceptionsResourceIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleAvailabilityExceptionsResourceIdInput"
}
