// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"encoding/json"
)

// UpdateColumnBookingResourceAttributesInput is the UpdateColumnBookingResourceAttributesInput input type.
type UpdateColumnBookingResourceAttributesInput struct {
	Set json.RawMessage `json:"set,omitzero"`
}

func (*UpdateColumnBookingResourceAttributesInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceAttributesInput"
}
