// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateScheduleDateRangesByIdUpdateColumnsInput is the UpdateScheduleDateRangesByIdUpdateColumnsInput input type.
type UpdateScheduleDateRangesByIdUpdateColumnsInput struct {
	EndDate   UpdateColumnScheduleDateRangesEndDateInput   `json:"endDate,omitzero"`
	Id        UpdateColumnScheduleDateRangesIdInput        `json:"id,omitzero"`
	StartDate UpdateColumnScheduleDateRangesStartDateInput `json:"startDate,omitzero"`
}

func (*UpdateScheduleDateRangesByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateScheduleDateRangesByIdUpdateColumnsInput"
}
