// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleResourceCancellationPolicyIdInput is the UpdateColumnScheduleResourceCancellationPolicyIdInput input type.
type UpdateColumnScheduleResourceCancellationPolicyIdInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleResourceCancellationPolicyIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleResourceCancellationPolicyIdInput"
}
