// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnBookingResourceHoldTtlInput is the UpdateColumnBookingResourceHoldTtlInput input type.
type UpdateColumnBookingResourceHoldTtlInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnBookingResourceHoldTtlInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceHoldTtlInput"
}
