// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleRefundTiersCutoffInput is the UpdateColumnScheduleRefundTiersCutoffInput input type.
type UpdateColumnScheduleRefundTiersCutoffInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnScheduleRefundTiersCutoffInput) GetGraphQLType() string {
	return "UpdateColumnScheduleRefundTiersCutoffInput"
}
