// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnIdentityUsersAvatarUrlInput is the UpdateColumnIdentityUsersAvatarUrlInput input type.
type UpdateColumnIdentityUsersAvatarUrlInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnIdentityUsersAvatarUrlInput) GetGraphQLType() string {
	return "UpdateColumnIdentityUsersAvatarUrlInput"
}
