// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleStayConstraintsAdvanceMinDaysInput is the UpdateColumnScheduleStayConstraintsAdvanceMinDaysInput input type.
type UpdateColumnScheduleStayConstraintsAdvanceMinDaysInput struct {
	Set *int32 `json:"set,omitempty"`
}

func (*UpdateColumnScheduleStayConstraintsAdvanceMinDaysInput) GetGraphQLType() string {
	return "UpdateColumnScheduleStayConstraintsAdvanceMinDaysInput"
}
