// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnPromocodeResourceStateInput is the UpdateColumnPromocodeResourceStateInput input type.
type UpdateColumnPromocodeResourceStateInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnPromocodeResourceStateInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceStateInput"
}
