// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnBookingMoneysIdInput is the UpdateColumnBookingMoneysIdInput input type.
type UpdateColumnBookingMoneysIdInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnBookingMoneysIdInput) GetGraphQLType() string {
	return "UpdateColumnBookingMoneysIdInput"
}
