// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceFeesDisplayNameInput is the UpdateColumnResourceFeesDisplayNameInput input type.
type UpdateColumnResourceFeesDisplayNameInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnResourceFeesDisplayNameInput) GetGraphQLType() string {
	return "UpdateColumnResourceFeesDisplayNameInput"
}
