// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput is the UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput input type.
type UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput struct {
	CreateTime  UpdateColumnScheduleAvailabilityExceptionsCreateTimeInput  `json:"createTime,omitzero"`
	DateRangeId UpdateColumnScheduleAvailabilityExceptionsDateRangeIdInput `json:"dateRangeId,omitzero"`
	Id          UpdateColumnScheduleAvailabilityExceptionsIdInput          `json:"id,omitzero"`
	Kind        UpdateColumnScheduleAvailabilityExceptionsKindInput        `json:"kind,omitzero"`
	Name        UpdateColumnScheduleAvailabilityExceptionsNameInput        `json:"name,omitzero"`
	Reason      UpdateColumnScheduleAvailabilityExceptionsReasonInput      `json:"reason,omitzero"`
	ResourceId  UpdateColumnScheduleAvailabilityExceptionsResourceIdInput  `json:"resourceId,omitzero"`
	SpanCase    UpdateColumnScheduleAvailabilityExceptionsSpanCaseInput    `json:"spanCase,omitzero"`
	WindowId    UpdateColumnScheduleAvailabilityExceptionsWindowIdInput    `json:"windowId,omitzero"`
}

func (*UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateScheduleAvailabilityExceptionsByIdUpdateColumnsInput"
}
