// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnPromocodeResourceEtagInput is the UpdateColumnPromocodeResourceEtagInput input type.
type UpdateColumnPromocodeResourceEtagInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnPromocodeResourceEtagInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceEtagInput"
}
