// Code generated by generate-ql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// UpdateColumnBookingMoneysUnitsInput is the UpdateColumnBookingMoneysUnitsInput input type.
type UpdateColumnBookingMoneysUnitsInput struct {
	Set *graphql.Int64 `json:"set,omitempty"`
}

func (*UpdateColumnBookingMoneysUnitsInput) GetGraphQLType() string {
	return "UpdateColumnBookingMoneysUnitsInput"
}
