// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateResourceLosDiscountsByIdUpdateColumnsInput is the UpdateResourceLosDiscountsByIdUpdateColumnsInput input type.
type UpdateResourceLosDiscountsByIdUpdateColumnsInput struct {
	AmountOffId *UpdateColumnResourceLosDiscountsAmountOffIdInput `json:"amountOffId,omitempty"`
	Id          *UpdateColumnResourceLosDiscountsIdInput          `json:"id,omitempty"`
	MinNights   *UpdateColumnResourceLosDiscountsMinNightsInput   `json:"minNights,omitempty"`
	OfferingId  *UpdateColumnResourceLosDiscountsOfferingIdInput  `json:"offeringId,omitempty"`
	PercentOff  *UpdateColumnResourceLosDiscountsPercentOffInput  `json:"percentOff,omitempty"`
}

func (*UpdateResourceLosDiscountsByIdUpdateColumnsInput) GetGraphQLType() string {
	return "UpdateResourceLosDiscountsByIdUpdateColumnsInput"
}
