// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleStayConstraintsCheckoutWeekdaysInput is the UpdateColumnScheduleStayConstraintsCheckoutWeekdaysInput input type.
type UpdateColumnScheduleStayConstraintsCheckoutWeekdaysInput struct {
	Set []*string `json:"set,omitzero"`
}

func (*UpdateColumnScheduleStayConstraintsCheckoutWeekdaysInput) GetGraphQLType() string {
	return "UpdateColumnScheduleStayConstraintsCheckoutWeekdaysInput"
}
