// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnOrganisationResourceMemberCountInput is the UpdateColumnOrganisationResourceMemberCountInput input type.
type UpdateColumnOrganisationResourceMemberCountInput struct {
	Set *int64 `json:"set,omitempty"`
}

func (*UpdateColumnOrganisationResourceMemberCountInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationResourceMemberCountInput"
}
