// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceLosDiscountsMinNightsInput is the UpdateColumnResourceLosDiscountsMinNightsInput input type.
type UpdateColumnResourceLosDiscountsMinNightsInput struct {
	Set int32 `json:"set"`
}

func (*UpdateColumnResourceLosDiscountsMinNightsInput) GetGraphQLType() string {
	return "UpdateColumnResourceLosDiscountsMinNightsInput"
}
