// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnBookingContactsIdInput is the UpdateColumnBookingContactsIdInput input type.
type UpdateColumnBookingContactsIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnBookingContactsIdInput) GetGraphQLType() string {
	return "UpdateColumnBookingContactsIdInput"
}
