// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnPromocodeApplicableResourcesIdInput is the UpdateColumnPromocodeApplicableResourcesIdInput input type.
type UpdateColumnPromocodeApplicableResourcesIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnPromocodeApplicableResourcesIdInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeApplicableResourcesIdInput"
}
