// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnIdentityUsersIdInput is the UpdateColumnIdentityUsersIdInput input type.
type UpdateColumnIdentityUsersIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnIdentityUsersIdInput) GetGraphQLType() string {
	return "UpdateColumnIdentityUsersIdInput"
}
