// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleDateRangesEndDateInput is the UpdateColumnScheduleDateRangesEndDateInput input type.
type UpdateColumnScheduleDateRangesEndDateInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleDateRangesEndDateInput) GetGraphQLType() string {
	return "UpdateColumnScheduleDateRangesEndDateInput"
}
