// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnOrganisationMembersEtagInput is the UpdateColumnOrganisationMembersEtagInput input type.
type UpdateColumnOrganisationMembersEtagInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnOrganisationMembersEtagInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationMembersEtagInput"
}
