// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnBookingContactsPhoneNumberInput is the UpdateColumnBookingContactsPhoneNumberInput input type.
type UpdateColumnBookingContactsPhoneNumberInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnBookingContactsPhoneNumberInput) GetGraphQLType() string {
	return "UpdateColumnBookingContactsPhoneNumberInput"
}
