// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnScheduleRecurringRulesClosesInput is the UpdateColumnScheduleRecurringRulesClosesInput input type.
type UpdateColumnScheduleRecurringRulesClosesInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnScheduleRecurringRulesClosesInput) GetGraphQLType() string {
	return "UpdateColumnScheduleRecurringRulesClosesInput"
}
