// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleStayConstraintsCheckinWeekdaysInput is the UpdateColumnScheduleStayConstraintsCheckinWeekdaysInput input type.
type UpdateColumnScheduleStayConstraintsCheckinWeekdaysInput struct {
	Set []*string `json:"set,omitzero"`
}

func (*UpdateColumnScheduleStayConstraintsCheckinWeekdaysInput) GetGraphQLType() string {
	return "UpdateColumnScheduleStayConstraintsCheckinWeekdaysInput"
}
