// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleCancellationPoliciesIdInput is the UpdateColumnScheduleCancellationPoliciesIdInput input type.
type UpdateColumnScheduleCancellationPoliciesIdInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnScheduleCancellationPoliciesIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleCancellationPoliciesIdInput"
}
