// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceLosDiscountsPercentOffInput is the UpdateColumnResourceLosDiscountsPercentOffInput input type.
type UpdateColumnResourceLosDiscountsPercentOffInput struct {
	Set *int32 `json:"set,omitempty"`
}

func (*UpdateColumnResourceLosDiscountsPercentOffInput) GetGraphQLType() string {
	return "UpdateColumnResourceLosDiscountsPercentOffInput"
}
