// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnBookingResourceCancelTimeInput is the UpdateColumnBookingResourceCancelTimeInput input type.
type UpdateColumnBookingResourceCancelTimeInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnBookingResourceCancelTimeInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceCancelTimeInput"
}
