// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnBookingResourceDiscountIdInput is the UpdateColumnBookingResourceDiscountIdInput input type.
type UpdateColumnBookingResourceDiscountIdInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnBookingResourceDiscountIdInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceDiscountIdInput"
}
