// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnBookingResourceOfferingInput is the UpdateColumnBookingResourceOfferingInput input type.
type UpdateColumnBookingResourceOfferingInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnBookingResourceOfferingInput) GetGraphQLType() string {
	return "UpdateColumnBookingResourceOfferingInput"
}
