// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnBookingMoneysUnitsInput is the UpdateColumnBookingMoneysUnitsInput input type.
type UpdateColumnBookingMoneysUnitsInput struct {
	Set *int64 `json:"set,omitempty"`
}

func (*UpdateColumnBookingMoneysUnitsInput) GetGraphQLType() string {
	return "UpdateColumnBookingMoneysUnitsInput"
}
