// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnPrismaMigrationsStartedAtInput is the UpdateColumnPrismaMigrationsStartedAtInput input type.
type UpdateColumnPrismaMigrationsStartedAtInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnPrismaMigrationsStartedAtInput) GetGraphQLType() string {
	return "UpdateColumnPrismaMigrationsStartedAtInput"
}
