// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnOrganisationResourceBillingEmailInput is the UpdateColumnOrganisationResourceBillingEmailInput input type.
type UpdateColumnOrganisationResourceBillingEmailInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnOrganisationResourceBillingEmailInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationResourceBillingEmailInput"
}
