// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnResourceEntityBookingModeInput is the UpdateColumnResourceEntityBookingModeInput input type.
type UpdateColumnResourceEntityBookingModeInput struct {
	Set string `json:"set,omitempty"`
}

func (*UpdateColumnResourceEntityBookingModeInput) GetGraphQLType() string {
	return "UpdateColumnResourceEntityBookingModeInput"
}
