// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnResourceOfferingsDurationInput is the UpdateColumnResourceOfferingsDurationInput input type.
type UpdateColumnResourceOfferingsDurationInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnResourceOfferingsDurationInput) GetGraphQLType() string {
	return "UpdateColumnResourceOfferingsDurationInput"
}
