// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleResourceNameInput is the UpdateColumnScheduleResourceNameInput input type.
type UpdateColumnScheduleResourceNameInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnScheduleResourceNameInput) GetGraphQLType() string {
	return "UpdateColumnScheduleResourceNameInput"
}
