// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"encoding/json"
)

// UpdateColumnOrganisationResourceSettingsInput is the UpdateColumnOrganisationResourceSettingsInput input type.
type UpdateColumnOrganisationResourceSettingsInput struct {
	Set json.RawMessage `json:"set,omitzero"`
}

func (*UpdateColumnOrganisationResourceSettingsInput) GetGraphQLType() string {
	return "UpdateColumnOrganisationResourceSettingsInput"
}
