// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnScheduleRecurringRulesIdInput is the UpdateColumnScheduleRecurringRulesIdInput input type.
type UpdateColumnScheduleRecurringRulesIdInput struct {
	Set string `json:"set"`
}

func (*UpdateColumnScheduleRecurringRulesIdInput) GetGraphQLType() string {
	return "UpdateColumnScheduleRecurringRulesIdInput"
}
