// Code generated by generate-ql. DO NOT EDIT.

package inputs

// UpdateColumnPromocodeResourceMaxRedemptionsInput is the UpdateColumnPromocodeResourceMaxRedemptionsInput input type.
type UpdateColumnPromocodeResourceMaxRedemptionsInput struct {
	Set *int64 `json:"set,omitempty"`
}

func (*UpdateColumnPromocodeResourceMaxRedemptionsInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceMaxRedemptionsInput"
}
