// Code generated by generateql. DO NOT EDIT.

package inputs

import (
	"github.com/oh-tarnished/generateql/runtime/go/param"
)

// UpdateColumnScheduleBufferSettingsMaxAdvanceInput is the UpdateColumnScheduleBufferSettingsMaxAdvanceInput input type.
type UpdateColumnScheduleBufferSettingsMaxAdvanceInput struct {
	Set param.Opt[string] `json:"set,omitzero"`
}

func (*UpdateColumnScheduleBufferSettingsMaxAdvanceInput) GetGraphQLType() string {
	return "UpdateColumnScheduleBufferSettingsMaxAdvanceInput"
}
