// Code generated by generateql. DO NOT EDIT.

package inputs

// UpdateColumnPromocodeResourceEtagInput is the UpdateColumnPromocodeResourceEtagInput input type.
type UpdateColumnPromocodeResourceEtagInput struct {
	Set *string `json:"set,omitempty"`
}

func (*UpdateColumnPromocodeResourceEtagInput) GetGraphQLType() string {
	return "UpdateColumnPromocodeResourceEtagInput"
}
