// Code generated by generateql. DO NOT EDIT.

package migrations

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// ListParams holds the optional arguments for List.
type ListParams struct {
	Limit   *int
	Offset  *int
	OrderBy *[]inputs.PrismaMigrationsOrderByExp
	Where   *inputs.PrismaMigrationsBoolExp
}

// AggregateParams holds the optional arguments for Aggregate.
type AggregateParams struct {
	FilterInput *inputs.PrismaMigrationsFilterInput
}

// DeleteByIdParams holds the optional arguments for DeleteById.
type DeleteByIdParams struct {
	PreCheck *inputs.PrismaMigrationsBoolExp
}

// InsertParams holds the optional arguments for Insert.
type InsertParams struct {
	PostCheck *inputs.PrismaMigrationsBoolExp
}

// UpdateByIdParams holds the optional arguments for UpdateById.
type UpdateByIdParams struct {
	PostCheck *inputs.PrismaMigrationsBoolExp
	PreCheck  *inputs.PrismaMigrationsBoolExp
}

// OnListParams holds the optional arguments for OnList.
type OnListParams struct {
	Limit   *int
	Offset  *int
	OrderBy *[]inputs.PrismaMigrationsOrderByExp
	Where   *inputs.PrismaMigrationsBoolExp
}

// OnAggregateParams holds the optional arguments for OnAggregate.
type OnAggregateParams struct {
	FilterInput *inputs.PrismaMigrationsFilterInput
}

// QueryHandler runs PrismaMigrations query operations.
type QueryHandler interface {
	// List runs the "prismaMigrations" query.
	List(ctx context.Context, params ListParams) ([]schema.PrismaMigrations, error)
	// Aggregate runs the "prismaMigrationsAggregate" query.
	Aggregate(ctx context.Context, params AggregateParams) (*schema.PrismaMigrationsAggExp, error)
	// ById runs the "prismaMigrationsById" query.
	ById(ctx context.Context, id string) (*schema.PrismaMigrations, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PrismaMigrations mutation operations.
type MutationHandler interface {
	// DeleteById runs the "deletePrismaMigrationsById" mutation.
	DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeletePrismaMigrationsByIdResponse, error)
	// Insert runs the "insertPrismaMigrations" mutation.
	Insert(ctx context.Context, objects []inputs.InsertPrismaMigrationsObjectInput, params InsertParams) (schema.InsertPrismaMigrationsResponse, error)
	// UpdateById runs the "updatePrismaMigrationsById" mutation.
	UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdatePrismaMigrationsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdatePrismaMigrationsByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PrismaMigrations subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "prismaMigrations" subscription.
	OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error)
	// OnAggregate runs the "prismaMigrationsAggregate" subscription.
	OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error)
	// OnById runs the "prismaMigrationsById" subscription.
	OnById(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
