// Code generated by generateql. DO NOT EDIT.

package schema

import (
	"encoding/json"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// BookingTimeWindows is the BookingTimeWindows model.
type BookingTimeWindows struct {
	BookingResources []struct {
		AssignedUnit   *string          `graphql:"assignedUnit"`
		Attributes     *json.RawMessage `graphql:"attributes"`
		CancelReason   *string          `graphql:"cancelReason"`
		CancelTime     *string          `graphql:"cancelTime"`
		ConfirmTime    *string          `graphql:"confirmTime"`
		ContactId      *string          `graphql:"contactId"`
		CreateTime     string           `graphql:"createTime"`
		Customer       *string          `graphql:"customer"`
		DiscountId     *string          `graphql:"discountId"`
		Etag           *string          `graphql:"etag"`
		HoldExpireTime *string          `graphql:"holdExpireTime"`
		HoldTtl        *string          `graphql:"holdTtl"`
		Id             string           `graphql:"id"`
		Name           string           `graphql:"name"`
		Notes          *string          `graphql:"notes"`
		Offering       *string          `graphql:"offering"`
		PriceId        *string          `graphql:"priceId"`
		PromoCode      *string          `graphql:"promoCode"`
		RefundAmountId *string          `graphql:"refundAmountId"`
		RefundPercent  *int32           `graphql:"refundPercent"`
		Resource       string           `graphql:"resource"`
		State          *string          `graphql:"state"`
		TotalId        *string          `graphql:"totalId"`
		Units          *int32           `graphql:"units"`
		UpdateTime     string           `graphql:"updateTime"`
		WindowId       string           `graphql:"windowId"`
	} `graphql:"bookingResources"`
	BookingResourcesAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"bookingResourcesAggregate"`
	EndTime                        string `graphql:"endTime"`
	Id                             string `graphql:"id"`
	ScheduleAvailabilityExceptions []struct {
		CreateTime  string  `graphql:"createTime"`
		DateRangeId *string `graphql:"dateRangeId"`
		Id          string  `graphql:"id"`
		Kind        string  `graphql:"kind"`
		Name        string  `graphql:"name"`
		Reason      *string `graphql:"reason"`
		ResourceId  string  `graphql:"resourceId"`
		SpanCase    *string `graphql:"spanCase"`
		WindowId    *string `graphql:"windowId"`
	} `graphql:"scheduleAvailabilityExceptions"`
	ScheduleAvailabilityExceptionsAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"scheduleAvailabilityExceptionsAggregate"`
	StartTime string `graphql:"startTime"`
}
