// Code generated by generateql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// BoolAggExp is the BoolAggExp model.
type BoolAggExp struct {
	Count         graphql.Int64 `graphql:"_count"`
	CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	BoolAnd       *bool         `graphql:"bool_and"`
	BoolOr        *bool         `graphql:"bool_or"`
	Every         *bool         `graphql:"every"`
}
