// Code generated by generateql. DO NOT EDIT.

package schema

import (
	"encoding/json"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// IdentityMembershipSummaries is the IdentityMembershipSummaries model.
type IdentityMembershipSummaries struct {
	Id           string `graphql:"id"`
	IdentityUser struct {
		AvatarUrl   *string `graphql:"avatarUrl"`
		CreateTime  string  `graphql:"createTime"`
		DisplayName *string `graphql:"displayName"`
		Email       *string `graphql:"email"`
		Etag        *string `graphql:"etag"`
		Id          string  `graphql:"id"`
		Locale      *string `graphql:"locale"`
		Name        string  `graphql:"name"`
		TimeZone    *string `graphql:"timeZone"`
		UpdateTime  string  `graphql:"updateTime"`
	} `graphql:"identityUser"`
	OrgDisplayName       *string `graphql:"orgDisplayName"`
	Organisation         *string `graphql:"organisation"`
	OrganisationResource struct {
		BillingEmail *string          `graphql:"billingEmail"`
		CreateTime   string           `graphql:"createTime"`
		DisplayName  string           `graphql:"displayName"`
		Etag         *string          `graphql:"etag"`
		Id           string           `graphql:"id"`
		MemberCount  *graphql.Int64   `graphql:"memberCount"`
		Name         string           `graphql:"name"`
		Settings     *json.RawMessage `graphql:"settings"`
		Slug         *string          `graphql:"slug"`
		State        *string          `graphql:"state"`
		UpdateTime   string           `graphql:"updateTime"`
	} `graphql:"organisationResource"`
	Role   *string `graphql:"role"`
	UserId string  `graphql:"userId"`
}
