// Code generated by generate-ql. DO NOT EDIT.

package schema

// InsertResourceOfferingsResponse is the InsertResourceOfferingsResponse model.
type InsertResourceOfferingsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		CreateTime  string  `graphql:"createTime"`
		Description *string `graphql:"description"`
		DisplayName string  `graphql:"displayName"`
		Duration    *string `graphql:"duration"`
		Etag        *string `graphql:"etag"`
		Id          string  `graphql:"id"`
		Name        string  `graphql:"name"`
		PriceId     *string `graphql:"priceId"`
		PricingUnit *string `graphql:"pricingUnit"`
		ResourceId  string  `graphql:"resourceId"`
		State       *string `graphql:"state"`
		UpdateTime  string  `graphql:"updateTime"`
	} `graphql:"returning"`
}
