// Code generated by generate-ql. DO NOT EDIT.

package schema

// InsertScheduleBufferSettingsResponse is the InsertScheduleBufferSettingsResponse model.
type InsertScheduleBufferSettingsResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndDelta   *string `graphql:"endDelta"`
		Gap        *string `graphql:"gap"`
		Id         string  `graphql:"id"`
		MaxAdvance *string `graphql:"maxAdvance"`
		MinNotice  *string `graphql:"minNotice"`
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}
