// Code generated by generate-ql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// InsertBookingMoneysResponse is the InsertBookingMoneysResponse model.
type InsertBookingMoneysResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		CurrencyCode *string        `graphql:"currencyCode"`
		Id           string         `graphql:"id"`
		Nanos        *int32         `graphql:"nanos"`
		Units        *graphql.Int64 `graphql:"units"`
	} `graphql:"returning"`
}
