// Code generated by generate-ql. DO NOT EDIT.

package schema

// InsertScheduleDateRangesResponse is the InsertScheduleDateRangesResponse model.
type InsertScheduleDateRangesResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndDate   string `graphql:"endDate"`
		Id        string `graphql:"id"`
		StartDate string `graphql:"startDate"`
	} `graphql:"returning"`
}
