// Code generated by generate-ql. DO NOT EDIT.

package schema

// Int4AggExp is the Int4AggExp model.
type Int4AggExp struct {
	Count         int64   `graphql:"_count"`
	CountDistinct int64   `graphql:"_count_distinct"`
	Avg           *string `graphql:"avg"`
	BitAnd        *int32  `graphql:"bit_and"`
	BitOr         *int32  `graphql:"bit_or"`
	BitXor        *int32  `graphql:"bit_xor"`
	Max           *int32  `graphql:"max"`
	Min           *int32  `graphql:"min"`
	Stddev        *string `graphql:"stddev"`
	StddevPop     *string `graphql:"stddev_pop"`
	StddevSamp    *string `graphql:"stddev_samp"`
	Sum           *int64  `graphql:"sum"`
	VarPop        *string `graphql:"var_pop"`
	VarSamp       *string `graphql:"var_samp"`
	Variance      *string `graphql:"variance"`
}
