// Code generated by generateql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// JsonbAggExp is the JsonbAggExp model.
type JsonbAggExp struct {
	Count         graphql.Int64 `graphql:"_count"`
	CountDistinct graphql.Int64 `graphql:"_count_distinct"`
}
