// Code generated by generateql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// OrganisationOrganisationStateAggExp is the OrganisationOrganisationStateAggExp model.
type OrganisationOrganisationStateAggExp struct {
	Count         graphql.Int64 `graphql:"_count"`
	CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	Max           *string       `graphql:"max"`
	Min           *string       `graphql:"min"`
}
