// Code generated by generate-ql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// OrganisationResourceAggExp is the OrganisationResourceAggExp model.
type OrganisationResourceAggExp struct {
	Count        graphql.Int64 `graphql:"_count"`
	BillingEmail struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"billingEmail"`
	CreateTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"createTime"`
	DisplayName struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"displayName"`
	Etag struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"etag"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	MemberCount struct {
		Count         graphql.Int64  `graphql:"_count"`
		CountDistinct graphql.Int64  `graphql:"_count_distinct"`
		Avg           *string        `graphql:"avg"`
		BitAnd        *graphql.Int64 `graphql:"bit_and"`
		BitOr         *graphql.Int64 `graphql:"bit_or"`
		BitXor        *graphql.Int64 `graphql:"bit_xor"`
		Max           *graphql.Int64 `graphql:"max"`
		Min           *graphql.Int64 `graphql:"min"`
		Stddev        *string        `graphql:"stddev"`
		StddevPop     *string        `graphql:"stddev_pop"`
		StddevSamp    *string        `graphql:"stddev_samp"`
		Sum           *string        `graphql:"sum"`
		VarPop        *string        `graphql:"var_pop"`
		VarSamp       *string        `graphql:"var_samp"`
		Variance      *string        `graphql:"variance"`
	} `graphql:"memberCount"`
	Name struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"name"`
	Settings struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	} `graphql:"settings"`
	Slug struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"slug"`
	State struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"state"`
	UpdateTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"updateTime"`
}
