// Code generated by generate-ql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// PromocodeResourceAggExp is the PromocodeResourceAggExp model.
type PromocodeResourceAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	AmountOffId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"amountOffId"`
	Code struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"code"`
	CreateTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"createTime"`
	Description struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"description"`
	Disabled struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		BoolAnd       *bool         `graphql:"bool_and"`
		BoolOr        *bool         `graphql:"bool_or"`
		Every         *bool         `graphql:"every"`
	} `graphql:"disabled"`
	DiscountType struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"discountType"`
	DisplayName struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"displayName"`
	Etag struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"etag"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	MaxRedemptions struct {
		Count         graphql.Int64  `graphql:"_count"`
		CountDistinct graphql.Int64  `graphql:"_count_distinct"`
		Avg           *string        `graphql:"avg"`
		BitAnd        *graphql.Int64 `graphql:"bit_and"`
		BitOr         *graphql.Int64 `graphql:"bit_or"`
		BitXor        *graphql.Int64 `graphql:"bit_xor"`
		Max           *graphql.Int64 `graphql:"max"`
		Min           *graphql.Int64 `graphql:"min"`
		Stddev        *string        `graphql:"stddev"`
		StddevPop     *string        `graphql:"stddev_pop"`
		StddevSamp    *string        `graphql:"stddev_samp"`
		Sum           *string        `graphql:"sum"`
		VarPop        *string        `graphql:"var_pop"`
		VarSamp       *string        `graphql:"var_samp"`
		Variance      *string        `graphql:"variance"`
	} `graphql:"maxRedemptions"`
	MinSubtotalId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"minSubtotalId"`
	Name struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"name"`
	PerCustomerLimit struct {
		Count         graphql.Int64  `graphql:"_count"`
		CountDistinct graphql.Int64  `graphql:"_count_distinct"`
		Avg           *string        `graphql:"avg"`
		BitAnd        *int32         `graphql:"bit_and"`
		BitOr         *int32         `graphql:"bit_or"`
		BitXor        *int32         `graphql:"bit_xor"`
		Max           *int32         `graphql:"max"`
		Min           *int32         `graphql:"min"`
		Stddev        *string        `graphql:"stddev"`
		StddevPop     *string        `graphql:"stddev_pop"`
		StddevSamp    *string        `graphql:"stddev_samp"`
		Sum           *graphql.Int64 `graphql:"sum"`
		VarPop        *string        `graphql:"var_pop"`
		VarSamp       *string        `graphql:"var_samp"`
		Variance      *string        `graphql:"variance"`
	} `graphql:"perCustomerLimit"`
	PercentOff struct {
		Count         graphql.Int64  `graphql:"_count"`
		CountDistinct graphql.Int64  `graphql:"_count_distinct"`
		Avg           *string        `graphql:"avg"`
		BitAnd        *int32         `graphql:"bit_and"`
		BitOr         *int32         `graphql:"bit_or"`
		BitXor        *int32         `graphql:"bit_xor"`
		Max           *int32         `graphql:"max"`
		Min           *int32         `graphql:"min"`
		Stddev        *string        `graphql:"stddev"`
		StddevPop     *string        `graphql:"stddev_pop"`
		StddevSamp    *string        `graphql:"stddev_samp"`
		Sum           *graphql.Int64 `graphql:"sum"`
		VarPop        *string        `graphql:"var_pop"`
		VarSamp       *string        `graphql:"var_samp"`
		Variance      *string        `graphql:"variance"`
	} `graphql:"percentOff"`
	RedeemEndTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"redeemEndTime"`
	RedeemStartTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"redeemStartTime"`
	RedemptionCount struct {
		Count         graphql.Int64  `graphql:"_count"`
		CountDistinct graphql.Int64  `graphql:"_count_distinct"`
		Avg           *string        `graphql:"avg"`
		BitAnd        *graphql.Int64 `graphql:"bit_and"`
		BitOr         *graphql.Int64 `graphql:"bit_or"`
		BitXor        *graphql.Int64 `graphql:"bit_xor"`
		Max           *graphql.Int64 `graphql:"max"`
		Min           *graphql.Int64 `graphql:"min"`
		Stddev        *string        `graphql:"stddev"`
		StddevPop     *string        `graphql:"stddev_pop"`
		StddevSamp    *string        `graphql:"stddev_samp"`
		Sum           *string        `graphql:"sum"`
		VarPop        *string        `graphql:"var_pop"`
		VarSamp       *string        `graphql:"var_samp"`
		Variance      *string        `graphql:"variance"`
	} `graphql:"redemptionCount"`
	State struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"state"`
	UpdateTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"updateTime"`
}
