// Code generated by generate-ql. DO NOT EDIT.

package schema

// ResourcePricingUnitAggExp is the ResourcePricingUnitAggExp model.
type ResourcePricingUnitAggExp struct {
	Count         int64   `graphql:"_count"`
	CountDistinct int64   `graphql:"_count_distinct"`
	Max           *string `graphql:"max"`
	Min           *string `graphql:"min"`
}
