// Code generated by generate-ql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// ScheduleDateRanges is the ScheduleDateRanges model.
type ScheduleDateRanges struct {
	EndDate               string `graphql:"endDate"`
	Id                    string `graphql:"id"`
	ResourceRateOverrides []struct {
		DateRangeId *string   `graphql:"dateRangeId"`
		Id          string    `graphql:"id"`
		OfferingId  string    `graphql:"offeringId"`
		PriceId     string    `graphql:"priceId"`
		Weekdays    []*string `graphql:"weekdays"`
	} `graphql:"resourceRateOverrides"`
	ResourceRateOverridesAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"resourceRateOverridesAggregate"`
	ScheduleAvailabilityExceptions []struct {
		CreateTime  string  `graphql:"createTime"`
		DateRangeId *string `graphql:"dateRangeId"`
		Id          string  `graphql:"id"`
		Kind        string  `graphql:"kind"`
		Name        string  `graphql:"name"`
		Reason      *string `graphql:"reason"`
		ResourceId  string  `graphql:"resourceId"`
		SpanCase    *string `graphql:"spanCase"`
		WindowId    *string `graphql:"windowId"`
	} `graphql:"scheduleAvailabilityExceptions"`
	ScheduleAvailabilityExceptionsAggregate struct {
		Count graphql.Int64 `graphql:"_count"`
	} `graphql:"scheduleAvailabilityExceptionsAggregate"`
	StartDate string `graphql:"startDate"`
}
