// Code generated by generate-ql. DO NOT EDIT.

package schema

// ScheduleResource is the ScheduleResource model.
type ScheduleResource struct {
	BuffersId             *string `graphql:"buffersId"`
	CancellationPolicyId  *string `graphql:"cancellationPolicyId"`
	Etag                  *string `graphql:"etag"`
	Id                    string  `graphql:"id"`
	Name                  string  `graphql:"name"`
	ScheduleBufferSetting struct {
		EndDelta   *string `graphql:"endDelta"`
		Gap        *string `graphql:"gap"`
		Id         string  `graphql:"id"`
		MaxAdvance *string `graphql:"maxAdvance"`
		MinNotice  *string `graphql:"minNotice"`
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"scheduleBufferSetting"`
	ScheduleCancellationPolicy struct {
		Id string `graphql:"id"`
	} `graphql:"scheduleCancellationPolicy"`
	ScheduleExceptions []struct {
		AvailabilityExceptionId string `graphql:"availabilityExceptionId"`
		Id                      string `graphql:"id"`
		ScheduleId              string `graphql:"scheduleId"`
	} `graphql:"scheduleExceptions"`
	ScheduleExceptionsAggregate struct {
		Count int64 `graphql:"_count"`
	} `graphql:"scheduleExceptionsAggregate"`
	ScheduleRecurringRules []struct {
		Closes     *string `graphql:"closes"`
		Id         string  `graphql:"id"`
		Opens      *string `graphql:"opens"`
		Rrule      string  `graphql:"rrule"`
		ScheduleId string  `graphql:"scheduleId"`
	} `graphql:"scheduleRecurringRules"`
	ScheduleRecurringRulesAggregate struct {
		Count int64 `graphql:"_count"`
	} `graphql:"scheduleRecurringRulesAggregate"`
	ScheduleStayConstraint struct {
		AdvanceMaxDays   *int32   `graphql:"advanceMaxDays"`
		AdvanceMinDays   *int32   `graphql:"advanceMinDays"`
		CheckinWeekdays  []string `graphql:"checkinWeekdays"`
		CheckoutWeekdays []string `graphql:"checkoutWeekdays"`
		Id               string   `graphql:"id"`
		MaxNights        *int32   `graphql:"maxNights"`
		MinNights        *int32   `graphql:"minNights"`
	} `graphql:"scheduleStayConstraint"`
	StayConstraintsId *string `graphql:"stayConstraintsId"`
}
