// Code generated by generate-ql. DO NOT EDIT.

package schema

// ScheduleBufferSettings is the ScheduleBufferSettings model.
type ScheduleBufferSettings struct {
	EndDelta          *string `graphql:"endDelta"`
	Gap               *string `graphql:"gap"`
	Id                string  `graphql:"id"`
	MaxAdvance        *string `graphql:"maxAdvance"`
	MinNotice         *string `graphql:"minNotice"`
	ScheduleResources []struct {
		BuffersId            *string `graphql:"buffersId"`
		CancellationPolicyId *string `graphql:"cancellationPolicyId"`
		Etag                 *string `graphql:"etag"`
		Id                   string  `graphql:"id"`
		Name                 string  `graphql:"name"`
		StayConstraintsId    *string `graphql:"stayConstraintsId"`
	} `graphql:"scheduleResources"`
	ScheduleResourcesAggregate struct {
		Count int64 `graphql:"_count"`
	} `graphql:"scheduleResourcesAggregate"`
	StartDelta *string `graphql:"startDelta"`
}
