// Code generated by generate-ql. DO NOT EDIT.

package schema

import (
	"github.com/oh-tarnished/generate-ql/runtime/go/graphql"
)

// ScheduleDateRangesAggExp is the ScheduleDateRangesAggExp model.
type ScheduleDateRangesAggExp struct {
	Count   graphql.Int64 `graphql:"_count"`
	EndDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"endDate"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	StartDate struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"startDate"`
}
