// Code generated by generateql. DO NOT EDIT.

package schema

// UpdateScheduleRefundTiersByIdResponse is the UpdateScheduleRefundTiersByIdResponse model.
type UpdateScheduleRefundTiersByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		CancellationPolicyId string `graphql:"cancellationPolicyId"`
		Cutoff               string `graphql:"cutoff"`
		Id                   string `graphql:"id"`
		RefundPercent        int32  `graphql:"refundPercent"`
	} `graphql:"returning"`
}
