// Code generated by generateql. DO NOT EDIT.

package schema

// UpdateBookingPriceComponentsByIdResponse is the UpdateBookingPriceComponentsByIdResponse model.
type UpdateBookingPriceComponentsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountId    *string `graphql:"amountId"`
		BookingId   string  `graphql:"bookingId"`
		Code        *string `graphql:"code"`
		DisplayName *string `graphql:"displayName"`
		Id          string  `graphql:"id"`
		Type        *string `graphql:"type"`
	} `graphql:"returning"`
}
