// Code generated by generate-ql. DO NOT EDIT.

package applicableresources

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeletePromocodeApplicableResourcesByIdResponse, error) {
	var out schema.DeletePromocodeApplicableResourcesByIdResponse
	args := map[string]any{
		"keyId": keyId,
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("deletePromocodeApplicableResourcesById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertPromocodeApplicableResourcesObjectInput, params InsertParams) (schema.InsertPromocodeApplicableResourcesResponse, error) {
	var out schema.InsertPromocodeApplicableResourcesResponse
	args := map[string]any{
		"objects": objects,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	res := <-h.gql.MutateFields("insertPromocodeApplicableResources", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdatePromocodeApplicableResourcesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdatePromocodeApplicableResourcesByIdResponse, error) {
	var out schema.UpdatePromocodeApplicableResourcesByIdResponse
	args := map[string]any{
		"keyId":         keyId,
		"updateColumns": updateColumns,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("updatePromocodeApplicableResourcesById", &out, args)
	return out, res.Error
}
