// Code generated by generateql. DO NOT EDIT.

package unitsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/propertyql/schemaql"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PropertyUnits query operations.
type QueryHandler interface {
	// List runs the "propertyUnits" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.PropertyUnits, error)
	// Find runs the "propertyUnits" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.PropertyUnits, error)
	// Aggregate runs the "propertyUnitsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.PropertyUnitsAggExp, error)
	// Get runs the "propertyUnitsById" query.
	Get(ctx context.Context, id string) (*schemaql.PropertyUnits, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PropertyUnits mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePropertyUnitsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeletePropertyUnitsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeletePropertyUnitsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPropertyUnits" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertPropertyUnitsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertPropertyUnitsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePropertyUnitsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdatePropertyUnitsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdatePropertyUnitsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdatePropertyUnitsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PropertyUnits subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "propertyUnits" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "propertyUnitsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "propertyUnitsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.PropertyUnits] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertPropertyUnitsResponse, schemaql.UpdatePropertyUnitsByIdResponse, schemaql.DeletePropertyUnitsByIdResponse] = (*mutationHandler)(nil)
