// Code generated by generateql. DO NOT EDIT.

package unitsql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyUnitsByIdResponse = schemaql.DeletePropertyUnitsByIdResponse
type InsertPropertyUnitsResponse = schemaql.InsertPropertyUnitsResponse
type PropertyUnits = schemaql.PropertyUnits
type PropertyUnitsAggExp = schemaql.PropertyUnitsAggExp
type UpdatePropertyUnitsByIdResponse = schemaql.UpdatePropertyUnitsByIdResponse
