// Code generated by generateql. DO NOT EDIT.

package membershipsummariesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs IdentityMembershipSummaries query operations.
type QueryHandler interface {
	// List runs the "identityMembershipSummaries" query.
	List(ctx context.Context, req ...*ListRequest) ([]schemaql.IdentityMembershipSummaries, error)
	// Find runs the "identityMembershipSummaries" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*schemaql.IdentityMembershipSummaries, error)
	// Aggregate runs the "identityMembershipSummariesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.IdentityMembershipSummariesAggExp, error)
	// Get runs the "identityMembershipSummariesById" query.
	Get(ctx context.Context, id string) (*schemaql.IdentityMembershipSummaries, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs IdentityMembershipSummaries mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteIdentityMembershipSummariesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteIdentityMembershipSummariesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *schemaql.DeleteIdentityMembershipSummariesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertIdentityMembershipSummaries" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertIdentityMembershipSummariesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *schemaql.InsertIdentityMembershipSummariesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateIdentityMembershipSummariesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateIdentityMembershipSummariesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (schemaql.UpdateIdentityMembershipSummariesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *schemaql.UpdateIdentityMembershipSummariesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs IdentityMembershipSummaries subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "identityMembershipSummaries" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "identityMembershipSummariesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "identityMembershipSummariesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[schemaql.IdentityMembershipSummaries] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, schemaql.InsertIdentityMembershipSummariesResponse, schemaql.UpdateIdentityMembershipSummariesByIdResponse, schemaql.DeleteIdentityMembershipSummariesByIdResponse] = (*mutationHandler)(nil)
