// Code generated by generateql. DO NOT EDIT.

package membershipsummariesql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

// QueryHandler runs IdentityMembershipSummaries query operations.
type QueryHandler interface {
	// Find runs the "identityMembershipSummaries" query.
	Find(ctx context.Context, obj CreateInput, req ...*FindRequest) ([]schemaql.IdentityMembershipSummaries, error)
	// Aggregate runs the "identityMembershipSummariesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*schemaql.IdentityMembershipSummariesAggExp, error)
	// Get runs the "identityMembershipSummariesById" query.
	Get(ctx context.Context, id string) (*schemaql.IdentityMembershipSummaries, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs IdentityMembershipSummaries mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteIdentityMembershipSummariesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (schemaql.DeleteIdentityMembershipSummariesByIdResponse, error)
	// Create runs the "insertIdentityMembershipSummaries" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (schemaql.InsertIdentityMembershipSummariesResponse, error)
	// Update runs the "updateIdentityMembershipSummariesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (schemaql.UpdateIdentityMembershipSummariesByIdResponse, error)
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs IdentityMembershipSummaries subscription operations.
type SubscriptionHandler interface {
	// OnFind runs the "identityMembershipSummaries" subscription.
	OnFind(ctx context.Context, obj CreateInput, req ...*OnFindRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "identityMembershipSummariesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "identityMembershipSummariesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}
