// Code generated by generateql. DO NOT EDIT.

package membershipsummariesql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/identityql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteIdentityMembershipSummariesByIdResponse = schemaql.DeleteIdentityMembershipSummariesByIdResponse
type IdentityMembershipSummaries = schemaql.IdentityMembershipSummaries
type IdentityMembershipSummariesAggExp = schemaql.IdentityMembershipSummariesAggExp
type InsertIdentityMembershipSummariesResponse = schemaql.InsertIdentityMembershipSummariesResponse
type UpdateIdentityMembershipSummariesByIdResponse = schemaql.UpdateIdentityMembershipSummariesByIdResponse
