// Code generated by generateql. DO NOT EDIT.

package buffersettings

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generateql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteScheduleBufferSettingsByIdResponse, error) {
	var out schema.DeleteScheduleBufferSettingsByIdResponse
	args := map[string]any{
		"keyId": graphql.Var(keyId, "String1"),
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ScheduleBufferSettingsBoolExp")
	}
	res := <-h.gql.MutateFields("deleteScheduleBufferSettingsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertScheduleBufferSettingsObjectInput, params InsertParams) (schema.InsertScheduleBufferSettingsResponse, error) {
	var out schema.InsertScheduleBufferSettingsResponse
	args := map[string]any{
		"objects": graphql.Var(objects, "[InsertScheduleBufferSettingsObjectInput!]"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ScheduleBufferSettingsBoolExp")
	}
	res := <-h.gql.MutateFields("insertScheduleBufferSettings", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateScheduleBufferSettingsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateScheduleBufferSettingsByIdResponse, error) {
	var out schema.UpdateScheduleBufferSettingsByIdResponse
	args := map[string]any{
		"keyId":         graphql.Var(keyId, "String1"),
		"updateColumns": graphql.Var(updateColumns, "UpdateScheduleBufferSettingsByIdUpdateColumnsInput"),
	}
	if params.PostCheck != nil {
		args["postCheck"] = graphql.VarPtr(params.PostCheck, "ScheduleBufferSettingsBoolExp")
	}
	if params.PreCheck != nil {
		args["preCheck"] = graphql.VarPtr(params.PreCheck, "ScheduleBufferSettingsBoolExp")
	}
	res := <-h.gql.MutateFields("updateScheduleBufferSettingsById", &out, args)
	return out, res.Error
}
