// Code generated by generate-ql. DO NOT EDIT.

package buffersettings

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, params ListParams) ([]schema.ScheduleBufferSettings, error) {
	var q struct {
		ScheduleBufferSettings []schema.ScheduleBufferSettings `graphql:"scheduleBufferSettings(limit: $limit, offset: $offset, order_by: $order_by, where: $where)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"limit":    params.Limit,
		"offset":   params.Offset,
		"order_by": params.OrderBy,
		"where":    params.Where,
	})
	return q.ScheduleBufferSettings, res.Error
}

func (h *queryHandler) Aggregate(ctx context.Context, params AggregateParams) (*schema.ScheduleBufferSettingsAggExp, error) {
	var q struct {
		ScheduleBufferSettingsAggregate *schema.ScheduleBufferSettingsAggExp `graphql:"scheduleBufferSettingsAggregate(filter_input: $filter_input)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"filter_input": params.FilterInput,
	})
	return q.ScheduleBufferSettingsAggregate, res.Error
}

func (h *queryHandler) ById(ctx context.Context, id string) (*schema.ScheduleBufferSettings, error) {
	var q struct {
		ScheduleBufferSettingsById *schema.ScheduleBufferSettings `graphql:"scheduleBufferSettingsById(id: $id)"`
	}
	res := <-h.gql.Query(&q, map[string]any{
		"id": id,
	})
	return q.ScheduleBufferSettingsById, res.Error
}
