// Code generated by generateql. DO NOT EDIT.

package resourceql

// CreateInput holds the settable fields for creating one MediaResource row.
type CreateInput struct {
	CreateTime   string `json:"createTime,omitzero"`
	Filename     string `json:"filename,omitzero"`
	Id           string `json:"id"`
	MimeType     string `json:"mimeType,omitzero"`
	Name         string `json:"name"`
	ThumbnailUrl string `json:"thumbnailUrl,omitzero"`
	Url          string `json:"url,omitzero"`
	Uuid         string `json:"uuid,omitzero"`
}

// UpdateInput holds the fields to change on a MediaResource row; each set field becomes a column update.
type UpdateInput struct {
	CreateTime   string `json:"createTime,omitzero"`
	Filename     string `json:"filename,omitzero"`
	Id           string `json:"id,omitzero"`
	MimeType     string `json:"mimeType,omitzero"`
	Name         string `json:"name,omitzero"`
	ThumbnailUrl string `json:"thumbnailUrl,omitzero"`
	Url          string `json:"url,omitzero"`
	Uuid         string `json:"uuid,omitzero"`
}
