// Code generated by generate-ql. DO NOT EDIT.

package timewindows

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteBookingTimeWindowsByIdResponse, error) {
	var out schema.DeleteBookingTimeWindowsByIdResponse
	args := map[string]any{
		"keyId": keyId,
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("deleteBookingTimeWindowsById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertBookingTimeWindowsObjectInput, params InsertParams) (schema.InsertBookingTimeWindowsResponse, error) {
	var out schema.InsertBookingTimeWindowsResponse
	args := map[string]any{
		"objects": objects,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	res := <-h.gql.MutateFields("insertBookingTimeWindows", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateBookingTimeWindowsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateBookingTimeWindowsByIdResponse, error) {
	var out schema.UpdateBookingTimeWindowsByIdResponse
	args := map[string]any{
		"keyId":         keyId,
		"updateColumns": updateColumns,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("updateBookingTimeWindowsById", &out, args)
	return out, res.Error
}
