// Code generated by generate-ql. DO NOT EDIT.

package timewindows

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteBookingTimeWindowsByIdResponse, error) {
	var q struct {
		DeleteBookingTimeWindowsById schema.DeleteBookingTimeWindowsByIdResponse `graphql:"deleteBookingTimeWindowsById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeleteBookingTimeWindowsById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertBookingTimeWindowsObjectInput, params InsertParams) (schema.InsertBookingTimeWindowsResponse, error) {
	var q struct {
		InsertBookingTimeWindows schema.InsertBookingTimeWindowsResponse `graphql:"insertBookingTimeWindows(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertBookingTimeWindows, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateBookingTimeWindowsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateBookingTimeWindowsByIdResponse, error) {
	var q struct {
		UpdateBookingTimeWindowsById schema.UpdateBookingTimeWindowsByIdResponse `graphql:"updateBookingTimeWindowsById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdateBookingTimeWindowsById, res.Error
}
