// Code generated by generateql. DO NOT EDIT.

package resourceql

import (
	"encoding/json"
)

// CreateInput holds the settable fields for creating one BounceResource row.
type CreateInput struct {
	Campaign            string          `json:"campaign,omitzero"`
	CampaignDisplayName string          `json:"campaignDisplayName,omitzero"`
	CreateTime          string          `json:"createTime,omitzero"`
	Email               string          `json:"email,omitzero"`
	Id                  string          `json:"id"`
	Meta                json.RawMessage `json:"meta,omitzero"`
	Name                string          `json:"name"`
	Source              string          `json:"source,omitzero"`
	Subscriber          string          `json:"subscriber,omitzero"`
	Type                string          `json:"type,omitzero"`
}

// UpdateInput holds the fields to change on a BounceResource row; each set field becomes a column update.
type UpdateInput struct {
	Campaign            string          `json:"campaign,omitzero"`
	CampaignDisplayName string          `json:"campaignDisplayName,omitzero"`
	CreateTime          string          `json:"createTime,omitzero"`
	Email               string          `json:"email,omitzero"`
	Id                  string          `json:"id,omitzero"`
	Meta                json.RawMessage `json:"meta,omitzero"`
	Name                string          `json:"name,omitzero"`
	Source              string          `json:"source,omitzero"`
	Subscriber          string          `json:"subscriber,omitzero"`
	Type                string          `json:"type,omitzero"`
}
