// Code generated by generateql. DO NOT EDIT.

package moneysql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/bookingql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type BookingMoneys = schemaql.BookingMoneys
type BookingMoneysAggExp = schemaql.BookingMoneysAggExp
type DeleteBookingMoneysByIdResponse = schemaql.DeleteBookingMoneysByIdResponse
type InsertBookingMoneysResponse = schemaql.InsertBookingMoneysResponse
type UpdateBookingMoneysByIdResponse = schemaql.UpdateBookingMoneysByIdResponse
