// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// ResourceRateOverridesAggExp is the ResourceRateOverridesAggExp model.
type ResourceRateOverridesAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	DateRangeId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"dateRangeId"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	OfferingId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"offeringId"`
	PriceId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"priceId"`
}
