// Code generated by generateql. DO NOT EDIT.

package scopeapplicableunitsql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeScopeApplicableUnitsByIdResponse = schemaql.DeletePromocodeScopeApplicableUnitsByIdResponse
type InsertPromocodeScopeApplicableUnitsResponse = schemaql.InsertPromocodeScopeApplicableUnitsResponse
type PromocodeScopeApplicableUnits = schemaql.PromocodeScopeApplicableUnits
type PromocodeScopeApplicableUnitsAggExp = schemaql.PromocodeScopeApplicableUnitsAggExp
type UpdatePromocodeScopeApplicableUnitsByIdResponse = schemaql.UpdatePromocodeScopeApplicableUnitsByIdResponse
