// Code generated by generateql. DO NOT EDIT.

package refundtiers

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusyql/types/schema"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/param"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error) {
	var out []schema.ScheduleRefundTiers
	args := map[string]any{}
	if params.Limit.IsPresent() {
		args["limit"] = graphql.VarPtr(params.Limit.Value(), "Int")
	}
	if params.Offset.IsPresent() {
		args["offset"] = graphql.VarPtr(params.Offset.Value(), "Int")
	}
	if !param.IsOmitted(params.OrderBy) {
		args["order_by"] = graphql.VarPtr(params.OrderBy, "[ScheduleRefundTiersOrderByExp!]")
	}
	if !param.IsOmitted(params.Where) {
		args["where"] = graphql.VarPtr(params.Where, "ScheduleRefundTiersBoolExp")
	}
	return h.gql.SubscribeFields("scheduleRefundTiers", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error) {
	var out *schema.ScheduleRefundTiersAggExp
	args := map[string]any{}
	if !param.IsOmitted(params.FilterInput) {
		args["filter_input"] = graphql.VarPtr(params.FilterInput, "ScheduleRefundTiersFilterInput")
	}
	return h.gql.SubscribeFields("scheduleRefundTiersAggregate", &out, args)
}

func (h *subscriptionHandler) OnById(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schema.ScheduleRefundTiers
	args := map[string]any{
		"id": graphql.Var(id, "String1"),
	}
	return h.gql.SubscribeFields("scheduleRefundTiersById", &out, args)
}
