// Code generated by generateql. DO NOT EDIT.

package unitslinkql

import (
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyUnitsLinkByIdResponse = schemaql.DeletePropertyUnitsLinkByIdResponse
type InsertPropertyUnitsLinkResponse = schemaql.InsertPropertyUnitsLinkResponse
type PropertyUnitsLink = schemaql.PropertyUnitsLink
type PropertyUnitsLinkAggExp = schemaql.PropertyUnitsLinkAggExp
type UpdatePropertyUnitsLinkByIdResponse = schemaql.UpdatePropertyUnitsLinkByIdResponse
