// Code generated by generate-ql. DO NOT EDIT.

package rateoverrides

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeleteResourceRateOverridesByIdResponse, error) {
	var out schema.DeleteResourceRateOverridesByIdResponse
	args := map[string]any{
		"keyId": keyId,
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("deleteResourceRateOverridesById", &out, args)
	return out, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertResourceRateOverridesObjectInput, params InsertParams) (schema.InsertResourceRateOverridesResponse, error) {
	var out schema.InsertResourceRateOverridesResponse
	args := map[string]any{
		"objects": objects,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	res := <-h.gql.MutateFields("insertResourceRateOverrides", &out, args)
	return out, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdateResourceRateOverridesByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdateResourceRateOverridesByIdResponse, error) {
	var out schema.UpdateResourceRateOverridesByIdResponse
	args := map[string]any{
		"keyId":         keyId,
		"updateColumns": updateColumns,
	}
	if params.PostCheck != nil {
		args["postCheck"] = params.PostCheck
	}
	if params.PreCheck != nil {
		args["preCheck"] = params.PreCheck
	}
	res := <-h.gql.MutateFields("updateResourceRateOverridesById", &out, args)
	return out, res.Error
}
