// Code generated by generate-ql. DO NOT EDIT.

package applicableofferings

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/inputs"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) DeleteById(ctx context.Context, keyId string, params DeleteByIdParams) (schema.DeletePromocodeApplicableOfferingsByIdResponse, error) {
	var q struct {
		DeletePromocodeApplicableOfferingsById schema.DeletePromocodeApplicableOfferingsByIdResponse `graphql:"deletePromocodeApplicableOfferingsById(keyId: $keyId, preCheck: $preCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":    keyId,
		"preCheck": params.PreCheck,
	})
	return q.DeletePromocodeApplicableOfferingsById, res.Error
}

func (h *mutationHandler) Insert(ctx context.Context, objects []inputs.InsertPromocodeApplicableOfferingsObjectInput, params InsertParams) (schema.InsertPromocodeApplicableOfferingsResponse, error) {
	var q struct {
		InsertPromocodeApplicableOfferings schema.InsertPromocodeApplicableOfferingsResponse `graphql:"insertPromocodeApplicableOfferings(objects: $objects, postCheck: $postCheck)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"objects":   objects,
		"postCheck": params.PostCheck,
	})
	return q.InsertPromocodeApplicableOfferings, res.Error
}

func (h *mutationHandler) UpdateById(ctx context.Context, keyId string, updateColumns inputs.UpdatePromocodeApplicableOfferingsByIdUpdateColumnsInput, params UpdateByIdParams) (schema.UpdatePromocodeApplicableOfferingsByIdResponse, error) {
	var q struct {
		UpdatePromocodeApplicableOfferingsById schema.UpdatePromocodeApplicableOfferingsByIdResponse `graphql:"updatePromocodeApplicableOfferingsById(keyId: $keyId, postCheck: $postCheck, preCheck: $preCheck, updateColumns: $updateColumns)"`
	}
	res := <-h.gql.Mutation(&q, map[string]any{
		"keyId":         keyId,
		"postCheck":     params.PostCheck,
		"preCheck":      params.PreCheck,
		"updateColumns": updateColumns,
	})
	return q.UpdatePromocodeApplicableOfferingsById, res.Error
}
