// Code generated by generateql. DO NOT EDIT.

package offeringsql

import (
	"context"
	"github.com/oh-tarnished/generateql/examples/freebusy/freebusyql/resourceql/schemaql"
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
	"github.com/oh-tarnished/generateql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error) {
	var out []schemaql.ResourceOfferings
	var r OnListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		args["limit"] = graphql.VarPtr(r.GetLimit(), "Int")
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[ResourceOfferingsOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "ResourceOfferingsBoolExp")
	}
	return h.gql.SubscribeFields(ctx, "resourceOfferings", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error) {
	var out *schemaql.ResourceOfferingsAggExp
	var r OnAggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		filterInput["limit"] = r.GetLimit()
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		filterInput["offset"] = r.GetOffset()
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		filterInput["order_by"] = r.GetOrderBy()
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		filterInput["where"] = r.GetWhere()
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "ResourceOfferingsFilterInput")
	}
	return h.gql.SubscribeFields(ctx, "resourceOfferingsAggregate", &out, args)
}

func (h *subscriptionHandler) OnGet(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schemaql.ResourceOfferings
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	return h.gql.SubscribeFields(ctx, "resourceOfferingsById", &out, args)
}
