// Code generated by generate-ql. DO NOT EDIT.

package freebusy

import (
	"github.com/oh-tarnished/generate-ql/examples/freebusy/booking"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/identity"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/organisation"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/prisma"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/promocode"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/resource"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/schedule"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
	"net/url"
)

// Service is a typed GraphQL client. Access operations via
// s.Query.<Domain>.<Resource>, s.Mutation..., and s.Subscription....
type Service struct {
	Query        QueryHandler
	Mutation     MutationHandler
	Subscription SubscriptionHandler
}

// QueryHandler groups every domain's query handlers.
type QueryHandler struct {
	Booking      booking.QueryHandler
	Identity     identity.QueryHandler
	Organisation organisation.QueryHandler
	Prisma       prisma.QueryHandler
	Promocode    promocode.QueryHandler
	Resource     resource.QueryHandler
	Schedule     schedule.QueryHandler
}

// MutationHandler groups every domain's mutation handlers.
type MutationHandler struct {
	Booking      booking.MutationHandler
	Identity     identity.MutationHandler
	Organisation organisation.MutationHandler
	Prisma       prisma.MutationHandler
	Promocode    promocode.MutationHandler
	Resource     resource.MutationHandler
	Schedule     schedule.MutationHandler
}

// SubscriptionHandler groups every domain's subscription handlers.
type SubscriptionHandler struct {
	Booking      booking.SubscriptionHandler
	Identity     identity.SubscriptionHandler
	Organisation organisation.SubscriptionHandler
	Prisma       prisma.SubscriptionHandler
	Promocode    promocode.SubscriptionHandler
	Resource     resource.SubscriptionHandler
	Schedule     schedule.SubscriptionHandler
}

// New connects to the endpoint described by opts and returns a Service.
func New(opts runtime.ConnectionOptions) (*Service, error) {
	conn, err := runtime.NewConnection(runtime.GraphQLConnClient)
	if err != nil {
		return nil, err
	}
	if _, err := conn.WithOpts(opts); err != nil {
		return nil, err
	}
	gql, err := conn.AsGraphQLConnectionType()
	if err != nil {
		return nil, err
	}
	return &Service{
		Query: QueryHandler{
			Booking:      booking.NewQuery(gql),
			Identity:     identity.NewQuery(gql),
			Organisation: organisation.NewQuery(gql),
			Prisma:       prisma.NewQuery(gql),
			Promocode:    promocode.NewQuery(gql),
			Resource:     resource.NewQuery(gql),
			Schedule:     schedule.NewQuery(gql),
		},
		Mutation: MutationHandler{
			Booking:      booking.NewMutation(gql),
			Identity:     identity.NewMutation(gql),
			Organisation: organisation.NewMutation(gql),
			Prisma:       prisma.NewMutation(gql),
			Promocode:    promocode.NewMutation(gql),
			Resource:     resource.NewMutation(gql),
			Schedule:     schedule.NewMutation(gql),
		},
		Subscription: SubscriptionHandler{
			Booking:      booking.NewSubscription(gql),
			Identity:     identity.NewSubscription(gql),
			Organisation: organisation.NewSubscription(gql),
			Prisma:       prisma.NewSubscription(gql),
			Promocode:    promocode.NewSubscription(gql),
			Resource:     resource.NewSubscription(gql),
			Schedule:     schedule.NewSubscription(gql),
		},
	}, nil
}

// NewFromURL connects using a full endpoint URL (e.g.
// "http://localhost:3280/graphql") and optional request headers, instead of a manual
// ConnectionOptions. Pass nil headers when none are needed.
func NewFromURL(endpoint string, headers map[string]string) (*Service, error) {
	u, err := url.Parse(endpoint)
	if err != nil {
		return nil, err
	}
	scheme := runtime.HTTPS
	if u.Scheme == "http" {
		scheme = runtime.HTTP
	}
	path := u.Path
	if path == "" {
		path = "/"
	}
	return New(runtime.ConnectionOptions{
		URL:     runtime.URLOptions{Scheme: scheme, Host: u.Host, Paths: []string{path}},
		Headers: headers,
	})
}
