// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// BookingTimeWindowsAggExp is the BookingTimeWindowsAggExp model.
type BookingTimeWindowsAggExp struct {
	Count   graphql.Int64 `graphql:"_count"`
	EndTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"endTime"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	StartTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"startTime"`
}
