// Code generated by generate-ql. DO NOT EDIT.

package resource

import (
	"context"
	"github.com/oh-tarnished/generate-ql/examples/freebusy/types/schema"
	"github.com/oh-tarnished/generate-ql/runtime/go/runtime"
)

type subscriptionHandler struct {
	gql *runtime.GraphQLClient
}

func (h *subscriptionHandler) OnList(ctx context.Context, params OnListParams) (*runtime.Subscription, error) {
	var out []schema.BookingResource
	args := map[string]any{}
	if params.Limit != nil {
		args["limit"] = params.Limit
	}
	if params.Offset != nil {
		args["offset"] = params.Offset
	}
	if params.OrderBy != nil {
		args["order_by"] = params.OrderBy
	}
	if params.Where != nil {
		args["where"] = params.Where
	}
	return h.gql.SubscribeFields("bookingResource", &out, args)
}

func (h *subscriptionHandler) OnAggregate(ctx context.Context, params OnAggregateParams) (*runtime.Subscription, error) {
	var out *schema.BookingResourceAggExp
	args := map[string]any{}
	if params.FilterInput != nil {
		args["filter_input"] = params.FilterInput
	}
	return h.gql.SubscribeFields("bookingResourceAggregate", &out, args)
}

func (h *subscriptionHandler) OnById(ctx context.Context, id string) (*runtime.Subscription, error) {
	var out *schema.BookingResource
	args := map[string]any{
		"id": id,
	}
	return h.gql.SubscribeFields("bookingResourceById", &out, args)
}
